### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by kolchy** [TorbenK/TK.CustomMap#1]
Hi there - great v1 of a nice custom map/pin implementation, I've branched a project I'm working on and implemented your lib. Here is some feedback:
- One of the key things that seems to be missing vs the 'native' Xamarin Forms map is the ability to click on the call out to fire an event. In my app for example, the user has a bunch of pins based on their location, the click on the pin to get some more info, then click on the call out to open the full details screen. 
- If I clear an ObservableCollection<TKCustomMapPin> before re-adding a bunch of pins, the new pins are added, but the old ones are not cleared. 
- The pins sit on top of the users current location, often hiding their location. 

I really like what you've got as a start, and happy to help test on a real world app if you would like :) Keep up the good work :+1: 

Cheers,
Kolchy

**Comment by kolchy** [comment]
Oh, one other thing I forgot that is also missing for my use case is the ability to bind another object to a pin. For example, I have a type Venue that I bind the ID to the XF pin, so when I click the call out, I know which model to load into the view...

Cheers!

**Comment by TorbenK** [comment]
Hi,

thanks for the feedback, I really appreciate! It would be great if you do further testings in your app. :-)
- I will have a look and implement a command for the click on the callout/info-window
- Seems like Action.Remove is not the correct action when Clear is called. I will take a look at that. Thanks for the report!
- If that is the case it seems to be the default behavior, but I'm not sure. Does this happen on both platforms? I will also take a look here!

For your last problem: I think you could simply derive from TKCustomPin and add the properties you like. Does this work for you?

**Comment by kolchy** [comment]
Hey Torben,

Thanks for getting back to me :) 2 things:
- Points 1 + 2 = GREAT! Let me know and I'll be more than happy to test!
- Point 3 - it seems in iOS the default pin does sit on top of the current user location image, so ignore this for now, I think ppl can just tweak either the pin marker or the map scale to get their desired result. 
- Point 4 - I had a quick test and it seems to work. If we can get an event hooked up to the callout/info-window, I should be able to replace the default Xamarin Forms map. 

Nice job! Let me know, happy to help test when you are ready...

Cheers,
Kolchy

**Comment by TorbenK** [comment]
Included in 1.1.0.

**Comment by kolchy** [comment]
Hey Torben - Just looking into adding custom properties to the pins. I've created an extended sample from yours that includes a pin that derives from from TKCustomMapPin and its available here (https://github.com/kolchy/TK.CustomMap). I add a simple int VenueId to a new class VenuePin that derives from TKCustomMapPin. In iOS (in simulator and on device) I get a blank pin (no image is shown). Would be great if you could take a look and let me know where I've gone wrong :)

Cheers,
Kolchy

**Comment by TorbenK** [comment]
Hi,

change that public ObservableCollection<VenuePin> Pins to ObservableCollection<TKCustomMapPin> and all your commands also to Command<TKCustomMapPin>. Inside the command you can then cast it back via (VenuePin)pin
