### ISSUE TITLE
Changing bindingcontext does not work very well

### ISSUE THREAD

**Issue by JeanCollas** [TorbenK/TK.CustomMap#105]
I have two map contexts that I switch with a button:
Context A = list of product A and a circle (the area concerned)
Context B = list of product B and a circle (the area concerned)
When switching contexts, it happens often that both circles appear on the map.

I would guess that there is a missing event unregistering.
I could not figure how to fix this yet...

**Comment by TorbenK** [comment]
Hey Jean, sorry for the late response.

> When switching contexts, it happens often that both circles appear on the map.

What do you mean by "it happens often"? You mean it sometimes works - sometimes not? Did you already debug? Do you maybe have a small repro project?

**Comment by JeanCollas** [comment]
Indeed I have changed some things in the renderer, I will do a diff soon :) (check also the pull request, not sure if it corrects everything but at least part of it!)

**Comment by TorbenK** [comment]
1.5.1.
