### ISSUE TITLE
Does this lib allow for zoom change?

### ISSUE THREAD

**Issue by eestein** [TorbenK/TK.CustomMap#106]
I can't find that option, only HasZoomEnabled. Is there a way to set the zoom manually? Thanks

**Comment by TorbenK** [comment]
I wonder where you found this option.

Checkout https://github.com/TorbenK/TK.CustomMap/issues/66.

**Comment by eestein** [comment]
Hey :)
Thanks for the info. I'm already doing that. I was just wondering if there was a property to manually set the zoom level, like `ZoomLevel = 5`. But thank you! And the info about the property I found on your wiki.

Cheers!
