### ISSUE TITLE
Binding pinClick, MapClick and PinSelect to events doesn't appear to work.

### ISSUE THREAD

**Issue by JoeTomkinson** [TorbenK/TK.CustomMap#110]
From what I can tell subscribing the pinselect, mapclick or pinclick events don't appear to work.

This is how I'm doing it:

```
  `mapView.SetBinding(TKCustomMap.CustomPinsProperty, "Pins");
            mapView.SetBinding(TKCustomMap.MapClickedCommandProperty, "MapClickedCommand");
            mapView.SetBinding(TKCustomMap.MapLongPressCommandProperty, "MapLongPressCommand");
            mapView.SetBinding(TKCustomMap.MapCenterProperty, "MapCenter");
            mapView.SetBinding(TKCustomMap.PinSelectedCommandProperty, "PinSelectedCommand");
            mapView.SetBinding(TKCustomMap.SelectedPinProperty, "SelectedPin");
            mapView.SetBinding(TKCustomMap.RoutesProperty, "Routes");
            mapView.SetBinding(TKCustomMap.PinDragEndCommandProperty, "DragEndCommand");
            mapView.SetBinding(TKCustomMap.CirclesProperty, "Circles");
            mapView.SetBinding(TKCustomMap.CalloutClickedCommandProperty, "CalloutClickedCommand");
            mapView.SetBinding(TKCustomMap.PolylinesProperty, "Lines");
            mapView.SetBinding(TKCustomMap.PolygonsProperty, "Polygons");
            mapView.SetBinding(TKCustomMap.MapRegionProperty, "MapRegion");
            mapView.SetBinding(TKCustomMap.RouteClickedCommandProperty, "RouteClickedCommand");
            mapView.SetBinding(TKCustomMap.RouteCalculationFinishedCommandProperty, "RouteCalculationFinishedCommand");
            mapView.SetBinding(TKCustomMap.TilesUrlOptionsProperty, "TilesUrlOptions");
            mapView.SetBinding(TKCustomMap.MapFunctionsProperty, "MapFunctions");
            mapView.IsRegionChangeAnimated = true;


            mapView.PinSelected += pinClicked;
            mapView.MapClicked += mapClicked;
            mapView.PinDragEnd += pinDragEnd;`
```

and the event methods for example the map click one are as below:

```
    `  private void mapClicked(object sender, TKGenericEventArgs<Position> e)
    {
        var loc_ = new Position(e.Value.Latitude, e.Value.Longitude); 

        mapView.Pins.Clear();

        var _pin = new Pin
        {
            Label = "Concern Location",
            Position = loc_
        };

        mapView.Pins.Add(_pin);
        mapView.MoveToRegion(MapSpan.FromCenterAndRadius(new Position(_pin.Position.Latitude, _pin.Position.Longitude), Distance.FromMiles(0.3)));
    }`
```

Any suggestions or is this a bug?

**Comment by TorbenK** [comment]
Looks totally fine to me, will check if I finally find some time to create 1.5.1.

**Comment by JoeTomkinson** [comment]
It looks implemented correctly to me as well from the base code, but I'm not sure if there's some interaction logic missing in forms but I couldn't for the life of me get those events to fire. I'll take another look with a fresh head this week. Thanks for getting back to me TorbenK.

**Comment by Lord-Link** [comment]
I'm also having a similar issue with the mapclick event not firing when binded it. Are there any updates on this?

**Comment by k4tos** [comment]
Hi, 

I downloaded the example [TK.CustomMap.Sample](https://github.com/TorbenK/TK.CustomMap/tree/master/Sample/TK.CustomMap.Sample/TK.CustomMap.Sample) and run the application in VS2015 for Android but don't fire the commands implementation for:

> CalloutClickedCommand, PinSelectedCommand, MapClickedCommand 

please can help me to solve this issue

Thanks and any help is really appreciated

**Comment by JeanCollas** [comment]
Check the pull requests (i have sent one for the samples) and other issues, you will find the answer :)

**Comment by corte** [comment]
MapClicked and MapLongPressed events won't fire for me as well. 
In the sample app works fine for me. As soon as I copy the whole code (without changing a single line) to my project, it stops working and I can't find out why.

HELP

**Comment by TorbenK** [comment]
Probably because you're doing something wrong.

Honestly, how should anyone be able to help you with that little information?

**Comment by corte** [comment]
Well I don't know as well. Just said that I copied the whole code and I have no idea what more information I can give. I even tried having every nuget package in the same version as the example, but nothing as well.
I gave up after all. This won't work
