### ISSUE TITLE
System.NullReferenceException in XF 2.3.1.114

### ISSUE THREAD

**Issue by cadastro2005** [TorbenK/TK.CustomMap#112]
I am creating a simple map and is generating the error below (XF and XFM: 2.3.1.114) but with the version X.F 2.3.0.107 the map is being created without problem.

![erro_tkmap](https://cloud.githubusercontent.com/assets/17800362/17668136/552f5f3e-62de-11e6-9137-4e79b50ee41e.png)

Class:
public class PrincipalView : ContentPage
    {
        private TKCustomMap _mapRegion;

```
    public PrincipalView()
    {
        Title = "Test";

        this.BindingContext = new PrincipalViewModel();

        _mapRegion = new TKCustomMap
        {
            MapCenter = new Position(-3.804865, -38.5508396),
        };

        Content = new StackLayout
        {
            Children =
                {
                    _mapRegion
                }
        };
    }
}
```

**Comment by cadastro2005** [comment]
![erro_2](https://cloud.githubusercontent.com/assets/17800362/17721926/587f59b0-6404-11e6-9576-b4e3f3c31272.png)

**Comment by TorbenK** [comment]
I'm pretty sure I saw that before and it was due to missing/wrong installation of the Goolgle Play Services.

**Comment by cadastro2005** [comment]
google play service is installed , but now I will reinstall using the Android SDK to perform the test .

**Comment by cadastro2005** [comment]
@TorbenK  
I reinstalled google play service ( Rev. 32 ) using the SDK Manager and the error continues. You have any recommendations?

**Comment by cadastro2005** [comment]
really was the problem google play service . I was not installed. inattention my !!! ; D
