### ISSUE TITLE
Custom pins not showing in ios 9.3

### ISSUE THREAD

**Issue by Lord-Link** [TorbenK/TK.CustomMap#113]
Previously my pins were showing in ios and they currently show in android but since i updated to ios 9.3 i cannot see the pins marked on the map. No error message is thrown nor does the app crash.

**Comment by TorbenK** [comment]
Is this happening in Debug mode?

**Comment by Lord-Link** [comment]
Yes its in debug mode. Also as a note last night I was trying to find out the cause and it suddenly fixed itself on ios (without any changes) and in android it stopped working... When I debug the code the pins get added but they never show. Could this be an issue in debug mode?

**Comment by TorbenK** [comment]
That sounds very strange. I was thinking of a linker problem, but if this happens in debug this is not the case.

Can you share your code where you adding your pins and the bindings?

**Comment by Lord-Link** [comment]
Sorry for the late reply I just got around to looking into the issue. Apparently the issue isn't with the plugin. I noticed that when get the coords using Xam.Forms.Geolocation to set my pins an android phone returns the coords with approx 6 decimal places while iphone returns the same locations coords with 13 decimal places. So when i open the map on an iphone it doesnt properly read the pins created in android and vice versa. Anyhow I'm gonna post this on another board since its not an issue with your plugin. Thanks for your reply!

**Comment by Lord-Link** [comment]
I'm reopening the issue because I tested the coords returned from both ios and android on google maps and they are just slightly off, meaning the issue isnt getting the coords its when they are displayed on different devices for some reason... I attempted truncating the iphone coords to see if they work on android and the same issue persists.

**Comment by Lord-Link** [comment]
I figured out the issue the iphone i was testing with is set to spanish and therefore stores the long and lat with commas while my android was configured in english and setting the values with decimal places. None the less the issue isn't with the plugin.
