### ISSUE TITLE
TkCustomPin.Image is not centered in the Pin LatLong

### ISSUE THREAD

**Issue by TioWidow** [TorbenK/TK.CustomMap#114]
I have problem setting the property "image" of a TkCustomPin.
When I set TkCustomPin an image of 128x128px is not centered in the Pin LatLong in LatLong ends up getting the upper left corner of the image.

When I insert a pin in the map with this image, it's an aspect of erroneously already displaced be that the corners are transparent.

Is there any way to solve this?

Original Image:
![markerselectx128](https://cloud.githubusercontent.com/assets/4378980/17755556/ed590caa-64b0-11e6-88bd-729e1ec6e325.png)

Sample image indicating where is the center of the image relative to pin
![markerselectx128](https://cloud.githubusercontent.com/assets/4378980/17755652/85f11ff2-64b1-11e6-9399-d3a95b49f1f6.jpg)

**Comment by TorbenK** [comment]
That what the `Anchor` property on the pin is for. Try to play around with it a little bit.

**Comment by TioWidow** [comment]
Thanks for your help and sorry for the inconvenience!

**Comment by TorbenK** [comment]
Bottom center should be something like 0.5/1.0
