### ISSUE TITLE
Custom map tiles 

### ISSUE THREAD

**Issue by Thranduillion** [TorbenK/TK.CustomMap#116]
Hello,

Is it possible to use custom map tiles with a template like this ? http://tile.stamen.com/terrain/{z}/{x}/{y}.jpg

I did not succeed. I tried this but I think that's not the correct way to do it : 

`var map = new TKCustomMap();
map.TilesUrlOptions = new TKTileUrlOptions("http://tile.stamen.com/toner/{z}/{x}/{y}.jpg", 512,512,1,10);`

Thanks a lot!

**Comment by TorbenK** [comment]
Did you read the summary?

```
/// <summary>
/// Gets the url for custom map tiles.  
/// <note type="note">Url must specify 3 placeholders({0}, {1}, {2}) which are used for providing x, y and zoom.</note>
/// </summary>
```
