### ISSUE TITLE
cant builed and get error after installing

### ISSUE THREAD

**Issue by GalFriD** [TorbenK/TK.CustomMap#118]
i installed this package and after that i tried to build my project and i got an error of java out of memory.
i changed the "java max heap size: ' to 1G
and then it works.
but after that after i deploy i get an exception that saying:
"java.lange.runtimexception":
unable to start activity compnentInfo.

have any idea why it happens?

**Comment by TorbenK** [comment]
Please make sure your Android SDKs are up to date.
