### ISSUE TITLE
Pin offset issue

### ISSUE THREAD

**Issue by dreamsystems** [TorbenK/TK.CustomMap#126]
Hi, when i set a `TKCustomMapPin` `Image` to a `TKCustomMapPin` and pass the
`TKCustomMapPin` `Position` as a value for a `TKCircle` `Center`, there is an offset between the pin and the circle. When the `TKCustomMapPin` `Image` is not set, all goes right.
Is there a way to bypass this issue ?
Thanks

<img src="https://cloud.githubusercontent.com/assets/17129852/18709313/d6c8fecc-7fff-11e6-8705-8f9a62ac3caa.png" width="200">

<img src="https://cloud.githubusercontent.com/assets/17129852/18709314/d6d316b4-7fff-11e6-905a-c5a69c690fd5.png" width="200">

**Comment by TorbenK** [comment]
Use the `Anchor` property. https://github.com/TorbenK/TK.CustomMap/issues/114

**Comment by dreamsystems** [comment]
Thanks.
