### ISSUE TITLE
Crash in Android 6.0

### ISSUE THREAD

**Issue by elyfran** [TorbenK/TK.CustomMap#128]
someone is getting use the android 6.0 normally?

**Comment by TioWidow** [comment]
Yes, I'm using normally in android 6. What are the difficulties you encountered?

**Comment by cadastro2005** [comment]
@TioWidow 

I am using the android 5.1.1 normally, but when used in android 6.0 is generated error.

**Comment by cadastro2005** [comment]
The problem is IsShowingUser=true. with this property the map crash.
