### ISSUE TITLE
Release 1.5.1

### ISSUE THREAD

**Issue by willowvil** [TorbenK/TK.CustomMap#129]
Hi,

Please could you let us know if you are going to release 1.5.1 version?

Congrats for the fantastic work.

Thanks.

**Comment by willowvil** [comment]
My need is to fix the current null target when:

map.PinSelectedCommand = new Command<TKCustomMapPin>(pin =>
{    });

**Comment by JeanCollas** [comment]
Isn't it the same issue?
https://github.com/TorbenK/TK.CustomMap/issues/75 
The signature of the command has changed, just the example is not up to date.

**Comment by TorbenK** [comment]
Probably beginning of november

**Comment by kikolopes90** [comment]
New update for Xamarin.Forms 2.3.3.168, does not work TK.CustomMap v1.5.0

**Comment by TorbenK** [comment]
Sorry for the long delay again. It's unfortunately really hard for me to find time to work on this. I will try to release a pre version as I can't find enough time to test everything.

**Comment by willowvil** [comment]
Great news! Keep waiting for new releases.

Thank you so much!
