### ISSUE TITLE
After moving to .Net Standard HttpClient conflicts

### ISSUE THREAD

**Issue by xalikoutis** [TorbenK/TK.CustomMap#131]
I moved my pcl project to .net standard 1.3 and when i reference "TK.CustomMap": "1.5.0" i get the following when i use HttpClient to call my rest API.

> Severity Code Description Project File Line Suppression State
> Error CS0433 The type 'HttpClient' exists in both 'System.Net.Http, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Net.Http, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

**Comment by xalikoutis** [comment]
Ok just forked, modernhttpclient is causing the problem. I removed it, it isn't needed. I ll make a PR

**Comment by TorbenK** [comment]
The modern http client is used calling the google places api.

**Comment by xalikoutis** [comment]
So standard httpclient can't be use? What's so special with google places api?

**Comment by TorbenK** [comment]
There is nothing special about the API, but the ModernHttpClient speeds things up quite a bit. I would love to remove as many unnecessary dependencies as possible though.

**Comment by nbsoftware** [comment]
I stumbled on quite the same issue, although my way to temporarily fix it was a bit different: I went to the packages' cache directory i.e. `%HOMEDRIVE%%HOMEPATH%\.nuget\packages\TK.CustomMap\1.5.0`, edit the `TK.CustomMap.nuspec` file and commented out (only!) the `Microsoft.Net.Http` dependency.

```
...        
<dependencies>
            <group>
                <dependency id="Xamarin.Forms.Maps" version="2.2.0.31" />
                <dependency id="Newtonsoft.Json" version="8.0.3" />
                <!--dependency id="Microsoft.Net.Http" version="2.2.29" /-->
                <dependency id="modernhttpclient" version="2.4.2" />
            </group>
            <group targetFramework="MonoAndroid1.0">
                <dependency id="Xamarin.Forms.Maps" version="2.2.0.31" />
                <dependency id="Xamarin.GooglePlayServices.Location" version="29.0.0.1" />
                <dependency id="modernhttpclient" version="2.4.2" />
            </group>
            <group targetFramework="Xamarin iOS1.0">
                <dependency id="Xamarin.Forms.Maps" version="2.2.0.31" />
                <dependency id="modernhttpclient" version="2.4.2" />
            </group>
        </dependencies>
...
```

I guess you might need to update your nuget repo file to a one that is compatible with both projects' structures (packages.config & .Net Standard's project.json). Haven't got a clue on how to do that yet, but it seems it is doable (if I'm not mistaken, project https://github.com/paulcbetts/refit for instance has updated it's package like so).

**Comment by TorbenK** [comment]
Next release will target net standard 1.5.. It should be compatible with both, PCL and netstandard.

**Comment by hardcodet** [comment]
I think ModernHttpClient is obsolete now - you can set native APIs in both Android and iOS projects, not?

**Comment by TorbenK** [comment]
Yes, I think that can be removed.

**Comment by TorbenK** [comment]
1.5.1.

**Comment by Beej126** [comment]
Thanks for that tip @nbsoftware ! Even up'ing to 1.5.1 i still needed to apply that Microsoft.Net.Http nuspec removal to get out of my error inferno... 

although ModernHttpClient may no longer be necessary, I'm using Xamarin.Forms.Theme.Dark which has ModernHttpClient dependency via Xamarin.Forms.Pages.
