### ISSUE TITLE
[UWP] Pins not visible

### ISSUE THREAD

**Issue by thomashagstrom** [TorbenK/TK.CustomMap#132]
For some reason pins don't show on UWP. Vanilla map with pins work. With TK CustomMap the map shows and all but no pins.

**Comment by TorbenK** [comment]
There is no renderer for UWP currently.

**Comment by vincentcastagna** [comment]
@TorbenK 
I just started to build on UWP and pin are not showing on bing map. I did not see any image property in the UWP renderer, so I tried w/o any image for the pin, but still pins are not showing on map (but adding them to collection works). This is a known behavior ? 
Thanks.

**Comment by TorbenK** [comment]
Because the default bing maps pin is very limited, there is a custom user control which is used on UWP. It is called `TKCustomBingMapsPin`. There are still some limitations but a lot of things are working. Dragging is not very smooth though.

UWP is still very much a preview.

**Comment by vincentcastagna** [comment]
Alright. But how should I then use this ? All my logic is in my .NET standard class library, TKCustomBingMapsPin is what's marker is for android. I don't understand what causes the fact that it does not display on the map ? 
Ty for your time
