### ISSUE TITLE
Center Map in iOS

### ISSUE THREAD

**Issue by hakamTaha** [TorbenK/TK.CustomMap#133]
in my Xamarin.Form application, android version is working well, but the for iOS it is always centered in 'Rome'.
I have tried the project sample, 'CalloutSample' but I got the same problem in iOS. 
I'm using version 1.5.0

**Comment by TorbenK** [comment]
I can't reproduce this. Please make sure everything is setup correctly.

**Comment by ballbrian** [comment]
I can second this. If you want a code example, I can provide them.  The binding works on android but not on ios for MapCenter.

**Comment by mayooresan** [comment]
I have maps in couple of screens in my app. The map center works just fine when the map is shown for the first time. If I navigate to another screen with map then the map doesn't show at all. Always the map shows Rome :(
