### ISSUE TITLE
Pins not initially visible when using MapType.Satellite (ios)

### ISSUE THREAD

**Issue by brenaud** [TorbenK/TK.CustomMap#139]
Everything works fine with with Street view, but when setting the map type to Satellite, the pins I initially put on the map are not visible until I move the map around a bit (usually so the pin is outside my visible range and then back)

Code I used:

```
public SamplePage()
{
    InitializeComponent();

    var ny = new Position(40.7142700, -74.0059700);
    Pins = new ObservableCollection<TKCustomMapPin>();
    Pins.Add(new TKCustomMapPin() { Position = ny });

    mapView = new TKCustomMap(MapSpan.FromCenterAndRadius(ny, Distance.FromKilometers(1)));
    mapView.CustomPins = Pins;
    //Following line breaks it:
    //mapView.MapType = MapType.Satellite;

    Content = mapView;
}
```

So far I got around it by waiting half a second before switching to Satellite... but I'm hoping there's a more elegant way to do it :)

**Comment by TorbenK** [comment]
Possibly caused by #90

**Comment by TorbenK** [comment]
1.5.1
