### ISSUE TITLE
Disable CustomPin animation

### ISSUE THREAD

**Issue by nbsoftware** [TorbenK/TK.CustomMap#143]
As I am dropping quite a number of Pins on my Map, I can't figure out a way to disable the "pin drop" animation altogether... it is taking too much time.

Equivalent code with basic XF Maps is a lot quicker because it doesn't animate the Pins addition.

**Comment by TorbenK** [comment]
As this is a feature on iOS only, I will not add it to the PCL. I think about adding a static setting to the iOS renderer though.

So far, you can create your own renderer derived from `TKCustomMapRenderer` for iOS, override `GetViewForAnnotation` and set `AnimatesDrop` to `false`. You can have a look at the callout sample too.

**Comment by TorbenK** [comment]
Added in 1.5.1-pre1
