### ISSUE TITLE
Draw the route on the map

### ISSUE THREAD

**Issue by elyfran** [TorbenK/TK.CustomMap#144]
how can I draw the route on the map covering only the streets? I'm sending the coordinates and draw on the map is passing over the houses.

thx

**Comment by TorbenK** [comment]
This should not happen. Are you using `TKRoute` or any own route calculation service?

`TKRoute` is using Google Directions(Android) and MKDirections(iOS). if they deliver route coordinates going through houses, I would think this is a bug on either of this APIs.

Which platform is this happening? Do you can share those coordinates?

**Comment by elyfran** [comment]
@TorbenK 

I was using TKPolyline as required for various positions for the route. With TkRouter can inform various positions?

**Comment by TorbenK** [comment]
No you can only add one source/destination to a `TKRoute`. You can, of couse, add multiple though.

if you use `TKPolyline` to draw the lines, how do you calculate the route?

**Comment by elyfran** [comment]
@TorbenK 

I get a list of routes of vehicles and need to draw on the map the car route. you have any idea how I can do this?

**Comment by TorbenK** [comment]
You get a calculated route? Simply add the `TKPolyline` with the calculated `Position`s.

If not, add multiple `TKRoute` instances, it will calculate the route for you. Event though it might not be the optimal route you can just go from source -> destination -> source -> destination...and so on.

**Comment by elyfran** [comment]
got it. thx

**Comment by egarim** [comment]
@elyfran  did you manage to drow the route using several points with latitude and longitude?
