### ISSUE TITLE
TK.CustomMap is not working ios

### ISSUE THREAD

**Issue by sunilyts** [TorbenK/TK.CustomMap#145]
Hi,

TK.CustomMap is working fine in Android while in ios it is not working.

Steps :
When user come map, long press we are showing popup, that popup is not showing on map.

Exact issue : MapFunctios - > throwing object reference null error,.
below line
this.MapFunctions.MoveToMapRegion(MapSpan.FromCenterAndRadius(position, Distance.FromMeters(80)), true);

Please reply if any anybody have solution.

Thanks,
Sunil Rana

**Comment by TioWidow** [comment]
I am using without problems on latest version of IOS.

The only bug I've had is bug #90  of the latest version, but everything else is working, including that function.

In some cases to call this function I needed to put inside that thread:

`Device.BeginInvokeOnMainThread(() =>{   .......   });`

Seeing the error does not seem to be your problem, tried to replicate in a new project?
