### ISSUE TITLE
Map crashed in tabbed page in Android

### ISSUE THREAD

**Issue by Nick1611** [TorbenK/TK.CustomMap#146]
Hi Torben,

I put the custom map inside a tab page. After switching from tab to tab for a few times (say, tab map, tab 1, tab 2, tab map), the map crashed with error "System.NullReferenceException: Object reference not set to an instance of an object.". It seems related to the tab page being destroyed and recreated when it is switched. It happens quite randomly, sometimes right after 1 switch and sometimes happens after a few switches.

To isolate other possibilities, I have created a project with just a few pages:
- 1 tab page holding 3 content pages
- 2 tab pages with just 1 label for switching purpose
- 1 tab page with build-in Xamarin map
- 1 tab page with the custom map
All xaml pages have just one label or one map item only.

When I included the build-in map page in the tab, there was no problem no matter how many times I switched. The map was found re-created sometimes as it move to default location.

When the custom map page was included (without the build-in map page), the error occurred after a few switches. After switching a few times, sometimes it won't crash immediately, but will crash after moving the map to other location manually.

I found the binding of mapregion does not work too. It may be due to the same issue that the map was in a tabbed page.

Is there anything missing that I should initialize the custom map? or any workaround if it is a bug?

Thanks.

Tabbed Page

```
<?xml version="1.0" encoding="utf-8" ?>
<TabbedPage xmlns="http://xamarin.com/schemas/2014/forms"
            xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
            xmlns:local="clr-namespace:TestTKMapInTab"
            x:Class="TestTKMapInTab.TabPage">
  <local:TestPage1 />
  <local:TestPage2 />
  <local:TKMapPage />
  <!--<local:MapPage />-->
</TabbedPage>

```

Tab 1
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="TestTKMapInTab.TestPage1" Title ="Tab 1">
  <Label Text="Tab 1" />
</ContentPage>

```

Tab 2

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="TestTKMapInTab.TestPage2" Title="Tab 2">
  <Label Text="Tab 2" />
</ContentPage>

```

Tab Map

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:maps="clr-namespace:Xamarin.Forms.Maps;assembly=Xamarin.Forms.Maps"
             x:Class="TestTKMapInTab.MapPage" Title="Map">
  <maps:Map />
</ContentPage>
```

Tab Custom Map

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:customMap="clr-namespace:TK.CustomMap;assembly=TK.CustomMap"
             x:Class="TestTKMapInTab.TKMapPage" Title="TKMap">
  <customMap:TKCustomMap />
</ContentPage>

```

**Comment by TorbenK** [comment]
Hey,

thanks for the detailed report. Can you do the following:

Get the dev branch and try if this is already fixed. If not, please provide the sample project. Thanks!

**Comment by JeanCollas** [comment]
I know I fixed this issue on my app, don't remember if I submitted anything about it... 
I will check this week.

**Comment by JeanCollas** [comment]
Hop:

```
  static TKCustomMap MainMap;

  ...
  if (MainMap == null)
  {
    TKCustomMap mapView;
    ....
    MainMap = mapView;
  }
```

I guess this is due to tabs functioning for memory optimization, there may be another way to unloading them, but I didn't find it (I didn't look much as this solution solved the issue).

**Comment by Nick1611** [comment]
Thank you very much for the quick response. I tried the development branch with no luck. Not sure if I did something wrong. The app can't be load. It has error "System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation." when loading the tabbed page. It stopped at "this.LoadFromXaml....." of the TabPage.xaml.g.cs

What I have done:
- remove tkmap nuget package from portable and droid projects.
- add development branch portable and droid project to my solution.

TestTKMapInTab.TabPage.xaml.g.cs

```

namespace TestTKMapInTab {
    using System;
    using Xamarin.Forms;
    using Xamarin.Forms.Xaml;


    public partial class TabPage : global::Xamarin.Forms.TabbedPage {

        [System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Build.Tasks.XamlG", "0.0.0.0")]
        private void InitializeComponent() {
            this.LoadFromXaml(typeof(TabPage));
        }
    }
}
```

I am working on loading the the project to github for your reference. However, it is taking forever to download the github desktop. I will get that done asap.

@JeanCollas I am testing it with a simple tabbed page. In fact, I am using the map in mvvm (freshmvvm). Will I be able to do something like your suggestion with all definition and binding specified in xaml?

I agreed that it is likely due to the tabs functioning for memory optimization. It loads the next tab before it is selected, and probably unload it if another tab (that is not right next to it) is selected.

Thanks.

**Comment by Nick1611** [comment]
New to github :( finally uploaded the project. hope it works:

https://github.com/Nick1611/TestTKMapInTabStableRelease

This is the original testing project with the custom map stable release. Please let me know if anything else I could provide to help investigating the issue.

Thanks.

**Comment by JeanCollas** [comment]
I would also have prefered to set everything in XAML, however I couldn't find a way. Therefore I just let it "as is".
Below few bits of my code that may help you:

```
if (MainMap != null)
      if (!_baseLayout.Children.Contains(MainMap))
      {
          this._baseLayout.Children.Add(
                    MainMap,
                    Constraint.Constant(0),
                    Constraint.Constant(0),
                    heightConstraint: Constraint.RelativeToParent((r) => r.Height),
                    widthConstraint: Constraint.RelativeToParent((r) => r.Width));
```

...

```
    private void RegisterMapBindings(TKCustomMap mapView)
    {
        mapView.SetBinding(TKCustomMap.CustomPinsProperty, "Pins");
        mapView.SetBinding(TKCustomMap.MapClickedCommandProperty, "MapClickedCommand");
        mapView.SetBinding(TKCustomMap.MapLongPressCommandProperty, "MapLongPressCommand");
        mapView.SetBinding(TKCustomMap.PinSelectedCommandProperty, "PinSelectedCommand");
        mapView.SetBinding(TKCustomMap.SelectedPinProperty, "SelectedPin");
        mapView.SetBinding(TKCustomMap.CirclesProperty, "Circles", mode: BindingMode.TwoWay);


        mapView.SetBinding(TKCustomMap.CalloutClickedCommandProperty, "BaseContext.CalloutClickedCommand");
        mapView.SetBinding(TKCustomMap.MapRegionProperty, "BaseContext.MapRegion");
    }
```

**Comment by TorbenK** [comment]
Please try if this is still the case with 1.5.1

Reopen if this still happens.
