### ISSUE TITLE
Route is not calculated

### ISSUE THREAD

**Issue by MichalDrwal** [TorbenK/TK.CustomMap#148]
I want get route directions from one point to another. 

Here is my MainPage Class

`  
       ObservableCollection<TKRoute> routes = new ObservableCollection<TKRoute>();
        ObservableCollection<TKRoute> lRoutesCollection = new ObservableCollection<TKRoute>();
        public MainPage()
        {
            InitializeComponent();
            customMap.RouteCalculationFinished += CustomMap_RouteCalculationFinished;
        }
        private void CustomMap_RouteCalculationFinished(object sender, TKGenericEventArgs<TKRoute> e)
        {
        }

        void OnClick(object sender, EventArgs e)
        {
            SetMyLocation();

        }

        private void SetMyLocation()
        {
            MoveMapToMyLocation();
            var route = new TKRoute();
            route.TravelMode = TKRouteTravelMode.Driving;
            var myposition = new Position(37.79752, -122.40183);
            var toposition = new Position(37.776831, -122.394627);
            route.Source = myposition;
            route.Destination = toposition;
            route.Color = Color.Blue;
            route.TravelMode = TKRouteTravelMode.Any;
            route.LineWidth = 2;
            routes.Add(route);
             customMap.Routes = routes;
          
            customMap.MoveToRegion(MapSpan.FromCenterAndRadius(new Position(37.79752, -122.40183), Distance.FromMiles(1.0)));
        }`

But after adding routes to the map, the bool "IsCalculated" is always false and I get no steps. What am I doing wrong?
My Google APIs are correct because I get directions when I paste the URL with my API to the browser.

Thanks in advance.

**Comment by TorbenK** [comment]
Do you get any error?

**Comment by mbharodia** [comment]
I am facing exactly the same issue. I am initializing the map the similar way as the author of this issue does. I have added RouteCalculationFailedCommand and RouteCalculationFinishedCommand. Neither of them are getting called. So, I am not sure whether there are errors; however, there are no exceptions thrown. I have made sure that I have App.cs property set up as suggested in the  samples. I am running and debugging this code on an emulator provided in Android SDK. I am using API 23. I really appreciate any help to resolve the issue.

**Comment by mbharodia** [comment]
I found the issue. Required NuGet package in Android project was not properly installed. It was missing Xamarin.GooglePlayServices.Location. I uninstalled this package and installed it again. It is working now. Thanks.

**Comment by mennetorelli** [comment]
Hello,
I am facing the same issue as above, but unfortunately reinstalling the package didn't help me. The routes seem to be added correctly to the map, but the bool "IsCalculated" remains false. I don't get any exceptions, so I don't know what's going wrong...
Thanks in advance

**Comment by edouardRego** [comment]
Hello,

I'm facing the same issue as well... Distance and TravelTime is always set "0".
Need help...
