### ISSUE TITLE
Assign ID to each pin to identify them -> CalloutClickedCommand

### ISSUE THREAD

**Issue by willowvil** [TorbenK/TK.CustomMap#151]
Hi,

Is it possible to assign an ID to each pin to identify them on the CalloutClickedCommand?

```
mapView.CalloutClickedCommand = new Command<TKCustomMapPin>(p =>
{

});
```

Thank you!

**Comment by willowvil** [comment]
If not, would be possible to assign an ID to the "Subtitle" but hidding it in the callout? Maybe a renderer?

**Comment by TorbenK** [comment]
Well, you can always just derive from `TKCustomMap` and work with your own implementation. I will probably add a `object Tag` to the pin though.

**Comment by ballbrian** [comment]
I had to add to a object Tag for one of the projects I did.  I can submit a pull request for that.

**Comment by jfversluis** [comment]
@ballbrian that would be great! If you could create one we will look into it.
