### ISSUE TITLE
1.5.1-pre1 Released

### ISSUE THREAD

**Issue by TorbenK** [TorbenK/TK.CustomMap#155]
I just release 1.5.1-pre1 on [NuGet](https://www.nuget.org/packages/TK.CustomMap/1.5.1-pre1). 

Note: I said I will target .netstandard, I have to revert this. This version is targeting PCL Profile 259 still.

Please report any problems regarding this version here. If your bugs are fixed, please close them.

**Comment by rachelleahr** [comment]
@TorbenK thank you! Everything is working perfectly now

**Comment by TioWidow** [comment]
Good Work.!

**Comment by jfversluis** [comment]
@TorbenK are there any plans for a UWP version? :)

I might need it in a little while, else I will try to have a go at it

**Comment by TorbenK** [comment]
@jfversluis well, it was planned. But as I said plenty of times here, I don't have the time to implement this. It would be great if somebody else goes ahead and does it.

I'm also looking for people able to manage this project alongside me(merging PRs, fixing bugs, updating NuGet and all those stuff).

**Comment by jfversluis** [comment]
@TorbenK Well, if you would have me I can help out a bit. I do have to implement some features for UWP already, so I could give it a try 😄

**Comment by kartaltr** [comment]
Good Work!
