### ISSUE TITLE
Include official Maps sources

### ISSUE THREAD

**Issue by JeanCollas** [TorbenK/TK.CustomMap#156]
As since the start of this project, the official Maps project has been open-sources.
As it is never updated, I think this would be a nice thing to include it into the project (see for example this project https://github.com/amay077/Xamarin.Forms.GoogleMaps )
This would reduce the overhead work and make things cleaner.
I know this is some work, but it can be done by steps, and improve significantly the performances/stability.
It also simplifies the bindings.

**Comment by TorbenK** [comment]
Hi Jean,

I don't really understand, where do you want to include the project?

**Comment by jfversluis** [comment]
If you wish to elaborate, please reopen
