### ISSUE TITLE
Position Pin in map iOS

### ISSUE THREAD

**Issue by andreluiz1987** [TorbenK/TK.CustomMap#157]
Hello,

First of all I'd like to thank you for your work as TK.CustomMap.

I'm using TK.CustomMap and I noticed that on iOS the pin marking is not correct.
In my implementation I get the coordinates of my server and plot the point on the map, I'm doing
The tracking of an object.

Run in the Android the positions are correct, exactly on the street.

In ios the pin stay outside street, look at the image:
![map-1](https://cloud.githubusercontent.com/assets/4265196/21234402/a98fbfdc-c2d9-11e6-92bd-e9da0a5a61c2.png)

The curious thing is that if I start to zoom, the icon appears to be approaching the street.
![map-2](https://cloud.githubusercontent.com/assets/4265196/21234479/f42a9634-c2d9-11e6-8e65-a6a3ac76f815.png)

I do not know if it's because of the base of the map or other things. As on Android the map is from Google and it works, I imagined that it was the map used in iOS, it seems to be OpenStreetMaps.

**Comment by TorbenK** [comment]
Hello,

this is a known issue but you can fix it by adjusting the `Anchor` property. See here: https://github.com/TorbenK/TK.CustomMap/issues/114

**Comment by andreluiz1987** [comment]
Thk, its work!!!
