### ISSUE TITLE
How to use custom callouts

### ISSUE THREAD

**Issue by rachelleahr** [TorbenK/TK.CustomMap#160]
How can I implement a custom view to display on the pin callout?

**Comment by jfversluis** [comment]
Did you check the [sample](https://github.com/TorbenK/TK.CustomMap/tree/Development/CalloutSample) app for that?

**Comment by willowvil** [comment]
@jfversluis I don´t know how to use your link info to achieve something like this:

![sin titulo](https://cloud.githubusercontent.com/assets/19213951/21769702/55bc4a46-d680-11e6-9603-ef63823c1092.png)

**Comment by TorbenK** [comment]
You need to create such a callout view on the native renderers. The sample callout app shows you how to get started.

**Comment by willowvil** [comment]
Thanks, it is clear!
