### ISSUE TITLE
How to show callout without pinclick

### ISSUE THREAD

**Issue by vincentcastagna** [TorbenK/TK.CustomMap#162]
Hello,

Is there a way to show the callout on a pin without having to click / select it. What I want is to display the callout on different event such as drag end of a map.

Thanks.

**Comment by TorbenK** [comment]
If you set the `SelectedItem` to the pin on `DragEnd` the callout should show up. But technically this is also a selection, so the answer is no. Not currently.

**Comment by vincentcastagna** [comment]
Thanks for the fast answer. What do you mean by set the SelectedItem to the pin ? 

I've got a command which does this : 

`public Command PannedCommand`
      `  {`
            `get`
          `  {`
               ` return new Command(() =>`
              `  {`
                   ` var temporaryPin = new TKCustomMapPin`
                   ` {`
                          `  Position = new Position(this.MapCenter.Latitude, this.MapCenter.Longitude),`
                          `  Title = "Ajouter un point",`
                            `ShowCallout = true,`
                            `Image = ImageSource.FromFile("ic_launcher.png"),`
                           ` //Center pin on layout`
                            `Anchor = new Point(0.5,0.5),`
                       ` };`
                  `  this._pins.Add(temporaryPin);`
               ` });`
           ` }`
        `}`

So I tried to ass this line in my command but doesnt work  : 
` this.selectedPin = temporaryPin;` 
Thanks.

**Comment by TorbenK** [comment]
```
public Command<TKCustomMapPin> DragEndCommand
{
	get 
	{
		return new Command<TKCustomMapPin>(pin => 
		{
			SelectedPin = pin; // this should force the callout to show up
		});
	}
}
```

**Comment by vincentcastagna** [comment]
Ok considering DragEndCommand on a pin. 

What I want is to set the SelectedPin to the one I just added on the map on PannedCommand. 
So, is the callout showing when the selectedPin is set, or is it set only if a selectedPin is clicked AND set ?

PannedCommand is a command from another package (MR.Gestures) that permits to detect drag end on a map. 

Thanks !

**Comment by TorbenK** [comment]
If your pin collection is observable and selectedPin is bound correctly, what you do should work. The callout should show as soon as you set the `SelectedPin`.

**Comment by vincentcastagna** [comment]
Okay so that does work but just once.

If you take my previous function, I added that after pin instanciation : 

`this._pins.Add(temporaryPin);` 
 ` SelectedPin = temporaryPin;` 

Ive got another command that RemoveAt the last _pins added (the temporary pin) when dragging (PanningCommand). When panning ends, its again the PannedCommand that is called
, but the callout does not popup. 

EDIT : I think that even if I delete the pin, the selectedPin is still set. Is there a way to unbound a selectedpin ? 

EDIT 2 : Nope, thats not the problem, the selectedPin is null if I remove the pin ...

**Comment by vincentcastagna** [comment]
I've managed a workaround for this and changed the flow of my application. For those who could be interessted, forget about adding an action in the callout, instead use a button that will pop where ever you want and use a command that will do the logic you want. The purpose of a callout is not really to do some logic but more to display info.

Thanks anyway for your help.

**Comment by jfversluis** [comment]
@Umar3x maybe you would like to share how, for future reference for others?

**Comment by vincentcastagna** [comment]
I've found why it was showing only one time when I was selected it once ... I'm a tard :D. I did realize that I was not binding mapClicked in which you'll have to set this.selectedPin = null to make the pin again not selected. In this way I'm now able to make the callout pop when an event occurs.
