### ISSUE TITLE
CustomInfoWindow get properties inherit class from TKCustomMapPin

### ISSUE THREAD

**Issue by vincentcastagna** [TorbenK/TK.CustomMap#165]
Hello all,

I'm building a customInfoWindow in my CustomMapRenderer following exemple of xamarin forms and the one given in this sample.

I have a CustomPin class that extends the TKCustomMapPin. 

```
   public class CustomPin : TKCustomMapPin
    {
        public Object Object { get; set; }

    }
```

What I want is to access  object's properties from my CustomPin class in the CustomRenderer : 

```
 Android.Views.View GoogleMap.IInfoWindowAdapter.GetInfoContents(Marker marker)
        {
 var pin = this.GetPinByMarker(marker);
            if (pin == null) return null;
 var infoTitle = view.FindViewById<TextView>(Resource.Id.InfoWindowTitle);
//Here get object properties but I only got those from TKCustomMapPin class, "Object" inacessible          
infoTitle.Text = pin.Object.Text;
 }
```

But I dont think the TKCustomMapRenderer.GetPinByMarker can get me what I want as it returns the pin property and not the customPin itself ... I know its probably not a "TKPackage's matter" but probably I'm missing something :) .

Thanks.

**Comment by vincentcastagna** [comment]
Well I think I was not clear and I've managed to make it work ...

I simply had to cast the returns of GetPinByMarker like that : 

` CustomPin realCustomPin = (CustomPin) customPin;`

But I've got another question @TorbenK  ... Is it possible to override GetPinByMarker in my CustomMapRenderer, thus I could cast the return of the function directly, would be more "clean" instead of casting the call ... But seems not exposed as it is not virtual ? (I'm beginning in c# and xamarin)

**Comment by TorbenK** [comment]
No, even if it would be virtual, you wont be able to change the signature.

You can simply create your own method, something similar to this:

`CustomPin GetRealCustomPinByMarker(Marker marker) => GetPinByMarker(marker) as CustomPin;`

**Comment by vincentcastagna** [comment]
Eh eh did not think about that ... Thank you very much !
