### ISSUE TITLE
Position image TKCustomMapPin

### ISSUE THREAD

**Issue by willowvil** [TorbenK/TK.CustomMap#166]
Hi,

When using TKCustomMapPin, my custom pin image is positioned under the coordinate (red point). Any idea?

![sin titulo](https://cloud.githubusercontent.com/assets/19213951/21770482/c1a0c70c-d683-11e6-8790-54a2ed16edba.png)

Thanks.

**Comment by TorbenK** [comment]
https://github.com/TorbenK/TK.CustomMap/issues/114

**Comment by willowvil** [comment]
Thanks!
