### ISSUE TITLE
Pin click, strange behavior

### ISSUE THREAD

**Issue by willowvil** [TorbenK/TK.CustomMap#167]
Hi,

I have two pins (A and B) on a map, and the following function:

```
map.PinSelectedCommand = new Command<TKCustomMapPin>(p =>
{
      DisplayAlert("PIN Selected", p.ID,"OK");
});
```

When I click on each of the pins, the alert is displayed correctly. However, if I first click on the A pin, then I zoom in on the map, and I click again on the A pin, the alert is no longer displayed. After the zoom, I have to first click on the B pin and at that moment the A pin is again clickable.

Thanks.

**Comment by TorbenK** [comment]
Probably because the pin is still selected.

Try to listen for property change of `MapRegion` and set `SelectedPin = null`. That should do it I guess.
