### ISSUE TITLE
Pin with custom images moves when zooming

### ISSUE THREAD

**Issue by juanse417** [TorbenK/TK.CustomMap#169]
*I'm using TK.CustomMap.Sample to show the issue*

When using a custom image for the pin. And you zoom out, the Pins are not staying in the right coordinates. They appear to "move".

**Screenshots with Custom Images:**
![simulator screen shot 11 ene 2017 13 13 11](https://cloud.githubusercontent.com/assets/7356344/21860895/b4740868-d800-11e6-946f-8237e143cf06.png)
![simulator screen shot 11 ene 2017 13 13 29](https://cloud.githubusercontent.com/assets/7356344/21860894/b4737bf0-d800-11e6-9c56-64c7456bb771.png)

The pins should not exit the circle

Now the normal functionality can be achieve by using the system one (with out custom image)

**Screenshot with System Pin:**
![simulator screen shot 11 ene 2017 13 15 42](https://cloud.githubusercontent.com/assets/7356344/21860899/b99f4122-d800-11e6-9c50-006bc97a2943.png)
![simulator screen shot 11 ene 2017 13 15 53](https://cloud.githubusercontent.com/assets/7356344/21860898/b99e7a8a-d800-11e6-999f-e3c61f0106f0.png)

As you can tell the system pins doesn't exit the circle.

The same is happening with Android

**Comment by TorbenK** [comment]
See #114

**Comment by juanse417** [comment]
My bad then.
So, I think there should be an update to the wiki to make the property more obvious.

**Comment by juanse417** [comment]
I have made the changes to the Wiki. 
Hope it helps!

**Comment by TorbenK** [comment]
Awesome, thank you!

And yes, the wiki is uncompleted and out of date. Feel free to update it whenever you want. I'll add you as contributor.
