### ISSUE TITLE
The library doesn't work with Xamarin.Forms.Maps 2.3.3.180 stable

### ISSUE THREAD

**Issue by sleonidy** [TorbenK/TK.CustomMap#170]
Hi,
When upgrading to Xamarin.Forms.Maps 2.3.3.180 , the library doesn't work correctly.
* Pins doesn't show on map.
* Map centered always on Rome

Thanks

**Comment by TorbenK** [comment]
Did you try 1.5.1-pre1?

**Comment by sleonidy** [comment]
Yes,
I tried it with 1.5.1-pre1 and 1.5.0.
Both of them failing to show Pins

**Comment by TorbenK** [comment]
Platform? Build Configuration? 

Works fine using the sample.

**Comment by sleonidy** [comment]
Hi,
The problem solved by itself. 
I have updated dependencies to the latest versions and now everything is working.
Thanks for help.
