### ISSUE TITLE
Deselect a pin on map not working

### ISSUE THREAD

**Issue by afrokick** [TorbenK/TK.CustomMap#173]
Hi. I want to deselect a pin after it was clicked. But mapView.SelectedPin = null; not working.

In my case, i clicked on pin, and after 3 seconds I want to deselect it(hide a tooltip). But after mapView.SelectedPin = null; PinSelected event not fire. At first I should click somewhere on map and then click on pin.

**Comment by afrokick** [comment]
Hi. I want to deselect a pin after it was clicked. But mapView.SelectedPin = null; not working.

In my case, i clicked on pin, and after 3 seconds I want to deselect it(hide a tooltip). But after mapView.SelectedPin = null; PinSelected event not fire. At first I should click somewhere on map and then click on pin.

**Comment by TorbenK** [comment]
Does this happen on iOS and Android, or is this a platform specific issue?

**Comment by afrokick** [comment]
@TorbenK tested only on iOS

**Comment by afrokick** [comment]
now I wrote a hack
`if (mapView.SelectedPin != null)
 { var pins = (this.BindingContext as MapViewModel).Pins;
var p = mapView.SelectedPin;
pins.Remove(mapView.SelectedPin);
pins.Add(p);
}`
As I understood, it's work because **NotifyCollectionChangedAction.Remove**(TKCustomMapRenderer.cs:304) occurred and **this.Map.RemoveAnnotation(annotation);**(TKCustomMapRenderer.cs:322) executed for selected pin.
