### ISSUE TITLE
Initial map position - MoveToRegion

### ISSUE THREAD

**Issue by willowvil** [TorbenK/TK.CustomMap#176]
Hi,

I´m just creating a new map (Android) and setting the initial position. However, some times the map is centered correctly, but most of the times simply no.

```
var mapView = new TKCustomMap()
{ 
	MapType = MapType.Street,
	IsRegionChangeAnimated = true
};
mapView.MoveToRegion(MapSpan.FromCenterAndRadius(new Position(40.4630d, -3.74922d), Distance.FromKilometers(500)));
```

Correct
![a](https://cloud.githubusercontent.com/assets/19213951/22429714/ced47d86-e70b-11e6-9d45-6b3130f9ae92.png)

No correct (in this case always go to the same position)
![b](https://cloud.githubusercontent.com/assets/19213951/22429750/e3fa95a6-e70b-11e6-87c3-cb5cc82b3229.png)

Thanks!!!

**Comment by masodev** [comment]
@willowvil In my case using  mapView.MapCenter = Position; prior using mapView.MoveToRegion solved the issue.

**Comment by TorbenK** [comment]
For the initial position you should pass it in the constructor.

**Comment by willowvil** [comment]
@masodev  @TorbenK  thanks for responses. MapCenter on constructor make the trick. But then, how can I set zoom?

**Comment by TorbenK** [comment]
Since you can pass a `MapSpan` in the constructor, you should be able to do something like `MapSpan.FromDistance`.

**Comment by 1NESLEiN** [comment]
Setting this from code works, but how, if possible, am I able to set the initial position using XAML?
I've tried using
`<x:Arguments>...</x:Arguments>`
Yet I don't know what to include between the tags. If this is not possible, how am I able to set the initial position then? Binding `MapCenter` works only the second time.

**Comment by TorbenK** [comment]
Well, theoretically it should be possible by passing a `<Xamarin.Forms.Maps:MapSpan>`. It is pretty unhandy though. 

I plan to add the following constructor in the next release, which should make it easy:

```
/// <summary>
/// Creates a new instance of <see cref="TKCustomMap"/>
/// </summary>
/// <param name="initialLatitude">The initial latitude value</param>
/// <param name="initialLongitude">The initial longitude value</param>
/// <param name="distanceInKilometers">The initial zoom distance in kilometers</param>
public TKCustomMap(double initialLatitude, double initialLongitude, double distanceInKilometers) : 
	base(MapSpan.FromCenterAndRadius(new Position(initialLatitude, initialLongitude), Distance.FromKilometers(distanceInKilometers)))
{ }
```
