### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by willowvil** [TorbenK/TK.CustomMap#178]
Hi,

I´m facing a memory leak problem on my app, but I don´t know if it is due to Tk.Custommap or just a garbage collect issue (xamarin).

From page A, I open page B where there is a map. If I open and close page B several times (about 12), my app breaks

Is there a method to dispose Tk.Custommap? I have tried to set null but unsuccessfully.

Thanks.

**Comment by TorbenK** [comment]
Do you ran out of memory or what kind of exception is raised? Can you share a repro project?

**Comment by willowvil** [comment]
Testing in real device: LG G2. And yes, it seems to ran out of memory. It happens when pageB is opened and closed about 12 times.

Repro files:

[Repro files.zip](https://github.com/TorbenK/TK.CustomMap/files/741770/Repro.files.zip)

Thanks.

**Comment by willowvil** [comment]
Hi,

Please I would appreciate if someone could test my repro files to analyze the problem.

Thanks!

**Comment by jfversluis** [comment]
There is no apparent reason for a crash to happen.
Could you post the full stack trace when a crash occurs?
