### ISSUE TITLE
PlacesAutoComplete - await TKNativePlacesApi.Instance.GetPredictions 

### ISSUE THREAD

**Issue by Grodart** [TorbenK/TK.CustomMap#180]
Hi there,
i can't make PlacesAutoComplete work :/
When i instanciate an Autocomplete in my projet like that : `new PlacesAutoComplete { ApiToUse = PlacesAutoComplete.PlacesApi.Native }; `  then type some Search in the SearchBar, it stops at  "`result = await TKNativePlacesApi.Instance.GetPredictions(this.SearchText, this.Bounds);`" with the following error :  

> system.NullReferenceException: Object reference not set to an instance of an object.
>   at MyProject.PlacesAutoComplete+<SearchPlaces>d__32.MoveNext () [0x001ac] in C:\Users\user\Source\Repos\MyProject\MyProject\PlacesAutoComplete.cs:200 

I can't find out why :/
When i start from the Sample (downloaded from the github) and delete everything but Autocomplete functions, it works great.

Everything works great but not placesAutoComplete, i'm missing something for sure but i can't see anything wrong comparing to the sample.

Sorry but i'm a little newbie with xamarin forms and C#, if someone can provide the minimum code/parameters/configurations to make Autocomplete works, it would be awesome!

Thank you very much :)

**Comment by jfversluis** [comment]
Can you show the relevant code you are using to try and make this work in your project?

It seems something is `null`, maybe you can debug through your code and check the values of all variables that can be null?

**Comment by Grodart** [comment]
Thank you jfversluis for your response,
I think there is a conflict between my NuGets, Modernhttpclient is involved :/
I'll try to find out with which one it bug.

Actually, it looks like there is nothing to do with code :)
Thank you!

**Comment by dijiadu** [comment]
Hi Grodart, I'm having the same issue. How did you resolve this?
