### ISSUE TITLE
Add Route doesnt work

### ISSUE THREAD

**Issue by Hussamalsh** [TorbenK/TK.CustomMap#181]
Hi
i tried to test your sample and when i click add route its doesn't do anything!!
thank you in advance

**Comment by jfversluis** [comment]
Hi @Hussamalsh 

Thank you for your message! But I am afraid we need a bit more info on this.
On what platform? Define 'doesn't do anything'? What do you expect it to do? Have you tried something in code to fix it? Etc.

Thank you!

**Comment by Hussamalsh** [comment]
Hi @jfversluis 
I tested this on Xamarin forms (portable) on android. But its works now, it was my bad, i typed the wrong API key. But now i have another problem. The polyline between two destinations is just straight line and not highlighting the route between two destinations  :( .

**Comment by Hussamalsh** [comment]
why you closed it ?

**Comment by TorbenK** [comment]
I just read the first sentence. My bad.

What exactly are you doing? When you simply add one polyline then obviously this is just a straight line.

**Comment by Hussamalsh** [comment]
How to have a highlighted route between two destinations ?

**Comment by TorbenK** [comment]
@Hussamalsh 

just follow the sample.
