### ISSUE TITLE
CalloutClickedCommand not work in release Mode

### ISSUE THREAD

**Issue by albilaga** [TorbenK/TK.CustomMap#182]
As title said, I bind my CalloutClickedCommand and it work in debug mode but it don't work in release mode.

I am using Xamarin.Forms and Xamarin.Forms.Maps with version 2.3.3.180 and TK.CustomMap with version 1.5.1

I set my binding like this `mapView.SetBinding(CustomMap.CalloutClickedCommandProperty, "CalloutClickedCommand");`

and in my ViewModel I have CalloutClickedCommand like this
```
public Command<TKCustomMapPin> CalloutClickedCommand
		{
			get
			{
				return new Command<TKCustomMapPin>(async mp =>
				{
                                 //Do something
                                }
                       }
                }
```

**Comment by TorbenK** [comment]
Make sure you call `TKCustomMapRenderer.InitMapRenderer();` on IOS.

**Comment by albilaga** [comment]
I already call it in AppDelegate and the problem occur in Android. I didn't check yet in iOS

**Comment by TorbenK** [comment]
I can't reproduce it. The only thing I can imagine is that things get removed by the linker when compiling against Release.
