### ISSUE TITLE
problem with search bar

### ISSUE THREAD

**Issue by thaabitv** [TorbenK/TK.CustomMap#184]
im trying to intergrate an auto complete places search bar with my map fragment but having trouble doing so, trying to test out this project but getting errors in xamarin studio where things like "CalculatedRoute" are underlined in red  like the class doesnt exist, happens with quite a few things like "Position", "_httpClient" etc.. any help on this?  this is on android.

**Comment by TorbenK** [comment]
That seems like you are missing some NuGet packages.
