### ISSUE TITLE
iOS Crash when changing overlay properties

### ISSUE THREAD

**Issue by lgjenero** [TorbenK/TK.CustomMap#186]
Hi @TorbenK!
Great library, made my life so much easier.

I came across an issue that crashes the library when you try to change properties of overlays on iOS before those overlays are shown on the map for the first time.
In my case it was changing the TKPolyline LineWidth.
The crash happens on line 947 in TK.CustomMap/TK.CustomMap.iOSUnified/TKCustomMapRenderer.cs
Here's the excerpt: 
```				
if (e.PropertyName == TKPolyline.ColorPropertyName)
{
    item.Value.Renderer.FillColor = item.Value.Overlay.Color.ToUIColor();
    item.Value.Renderer.StrokeColor = item.Value.Overlay.Color.ToUIColor();
}
else if (e.PropertyName == TKPolyline.LineWidthProperty)
{
    item.Value.Renderer.LineWidth = item.Value.Overlay.LineWidth;
}
```

I have added a check before the block to see if the Renderer is null and this seems to fix the issue.
It should be pretty easy to reproduce:
1.) Add TKPolyline to map but make sure it is not inside the current map region.
2.) Change the TKPolyline LineWidth

**Comment by lgjenero** [comment]
I've created a PR for this:
https://github.com/TorbenK/TK.CustomMap/pull/187

**Comment by TorbenK** [comment]
Thank you for the PR, you'll be added to the readme. Please use Dev branch next time. I merged it manually.
