### ISSUE TITLE
iOS callback icon is not showing v1.5.1

### ISSUE THREAD

**Issue by RanaInside** [TorbenK/TK.CustomMap#191]
Both on simulator and actual device: TKCustomMapPin with ShowCallout = true; clicking the pin shows details but not "Info icon"

Downgraded it to v1.5.0 and then it works as expected;

Sorry that I can't do any further analysis right now to figure out what's going on, but will try later on over the weekend.

**Comment by TorbenK** [comment]
`IsCalloutClickable`

**Comment by RanaInside** [comment]
really; checking it now... 

awesome; thanks.
