### ISSUE TITLE
what is the maximum TKRoute points I can set on the map to draw a detailed route?

### ISSUE THREAD

**Issue by gsaldana** [TorbenK/TK.CustomMap#192]
Hi Torben, first of all I want to thank you for this awesome map control, it has been really helpful in my apps.

Well, now the question:
I'm trying to draw a very detailed route into the map, the application is receiving around 400 positions. 

Why so many positions ?? Well, I'm trying to trace the specific route that are following some users, so I'm using TravelMode.Walking to achieve this.

But the problem comes when the map finishes to draw the lines, it only shows a little segments of the complete route.

I don't know if it is because I'm using a free "license" of Google Maps API or because I'm skipping some configurations of the control or there is a limit for the TKRoute points into the control.

Can you help me with this question please??

thanks in advance ;)

**Comment by TorbenK** [comment]
Are you able to provide a sample project?

**Comment by gsaldana** [comment]
Well, this project specific project, I don't think so, but I'll try to provide you the part where I'm manipulating the data to draw the points into the map, ok? let me make a sample project to reproduce this issue.

**Comment by gsaldana** [comment]
Hi Torben, here is the link for my TKCustomMap Sample where you could see te behavior I described previously.

https://github.com/nazgul87/TKMapSample

Thanks in advance

**Comment by gsaldana** [comment]
Hi Torben, is there any update about this topic?

**Comment by lnaie** [comment]
Using polylines should be more optimal.
