### ISSUE TITLE
Places IOS using Google places

### ISSUE THREAD

**Issue by jcesarmm** [TorbenK/TK.CustomMap#193]
Hello @TorbenK 

You made a great library! congratulations
I'm working on an app using your control but the NativeApi for autocomplete in IOS not working good for Colombia. (I think, the IOS team not have a complete databases of places for my country as Google)

It is possible to restrict the autocomplete to position (like NativeApi on your android project) but using the GoogleApi? (I would like to use the autocomplete control de GoogleApi in my Android and IOS projects)

I've tried to modify the file GmsPlace.cs on the request for Google places but It did not work as expected....

/// <summary>
        /// Build the query string for predictions
        /// </summary>
        /// <param name="searchText">The search text</param>
        /// <returns>The Query string</returns>
        private string BuildQueryPredictions(string searchText, Position position, double radio)
        {
            return string.Format("{0}?input={1}&location={2},{3}&radio={4}&key={5}", UrlPredictions, searchText, position.Latitude, position.Longitude, radio, _apiKey);
        }

**Comment by TorbenK** [comment]
What did not work?

You should be able to use the Google API but you have to be careful about license violations.
