### ISSUE TITLE
Missing GooglePlayService dll

### ISSUE THREAD

**Issue by DannyDenver** [TorbenK/TK.CustomMap#195]
After downloading from nuget, I got this error: 

Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'GooglePlayServicesLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'GooglePlayServicesLib.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute()	goD4DMobile.Droid	

I tried adding the googleservices from nuget and it didnt work. Then I deleted the TK.CustomMap and I still get the same error. Which GoogleServices package should I download and which version?

**Comment by TorbenK** [comment]
What Xamarin.Forms version do you use?

**Comment by DannyDenver** [comment]
I am using version 2.3.3.193.

**Comment by DannyDenver** [comment]
I rolled it back and redownloaded tk.CustomMap and Xamarin.Forms.Maps. 

I've gotten the map to show up in the view but cant get the click event to fire: 

namespace goD4DMobile
    {
    public partial class Map : ContentPage
        {
        public Map()
            {
            InitializeComponent();

            CreateView();
}
        private  void CreateView()
            {
            //var autoComplete = new PlacesAutoComplete { ApiToUse = PlacesAutoComplete.PlacesApi.Native };
            //autoComplete.SetBinding(PlacesAutoComplete.PlaceSelectedCommandProperty, "PlaceSelectedCommand");

            var newYork = new Position(40.7142700, -74.0059700);
            var mapView = new TKCustomMap(MapSpan.FromCenterAndRadius(newYork, Distance.FromKilometers(2)));
            mapView.IsShowingUser = true;
            mapView.SetBinding(TKCustomMap.CustomPinsProperty, "Pins");
            mapView.SetBinding(TKCustomMap.MapClickedCommandProperty, "MapClickedCommand");
            mapView.SetBinding(TKCustomMap.MapLongPressCommandProperty, "MapLongPressCommand");
            mapView.SetBinding(TKCustomMap.MapCenterProperty, "MapCenter");
            mapView.SetBinding(TKCustomMap.PinSelectedCommandProperty, "PinSelectedCommand");
            mapView.SetBinding(TKCustomMap.SelectedPinProperty, "SelectedPin");
            mapView.SetBinding(TKCustomMap.RoutesProperty, "Routes");
            mapView.SetBinding(TKCustomMap.PinDragEndCommandProperty, "DragEndCommand");
            mapView.SetBinding(TKCustomMap.CirclesProperty, "Circles");
            mapView.SetBinding(TKCustomMap.CalloutClickedCommandProperty, "CalloutClickedCommand");
            mapView.SetBinding(TKCustomMap.PolylinesProperty, "Lines");
            mapView.SetBinding(TKCustomMap.PolygonsProperty, "Polygons");
            mapView.SetBinding(TKCustomMap.MapRegionProperty, "MapRegion");
            mapView.SetBinding(TKCustomMap.RouteClickedCommandProperty, "RouteClickedCommand");
            mapView.SetBinding(TKCustomMap.RouteCalculationFinishedCommandProperty, "RouteCalculationFinishedCommand");
            mapView.SetBinding(TKCustomMap.TilesUrlOptionsProperty, "TilesUrlOptions");
            mapView.SetBinding(TKCustomMap.MapFunctionsProperty, "MapFunctions");
            mapView.IsRegionChangeAnimated = true;

            mapView.MapClicked += mapClicked;
            mapView.MapLongPress += longPress;
        
            mapView.MapClicked += (sender, e) => {

                var loc_ = new Position(e.Value.Latitude, e.Value.Longitude);


            };

            this.Content = mapView;
            //return mapView;
            }

     private void longPress(object sender, TKGenericEventArgs<Position> e)
            {
            var loc_ = new Position(e.Value.Latitude, e.Value.Longitude);
}
      
 private void mapClicked(object sender, TKGenericEventArgs<Position> e)
            {
            var loc_ = new Position(e.Value.Latitude, e.Value.Longitude);
}

My goal is to get the gps coordinates of where they click or longpress.

**Comment by TorbenK** [comment]
There is a bug. See #198

**Comment by TorbenK** [comment]
Duplicate.
