### ISSUE TITLE
Android CustomPin do not change IsDraggable status after render

### ISSUE THREAD

**Issue by CFerndp** [TorbenK/TK.CustomMap#196]
Hi!
I developed a Xamarin Forms app with this plugin. I made a map with one Pin and when I change IsDraggable property after render, the change does not work.

Any idea what's happend?

Regards

Cristian.

**Comment by TorbenK** [comment]
That seems to be a bug. Thanks for reporting.

**Comment by CFerndp** [comment]
Thank you for your work :)
