### ISSUE TITLE
New PlayServices libraries need Places DLL

### ISSUE THREAD

**Issue by hardcodet** [TorbenK/TK.CustomMap#197]
FYI: I just upgraded your library to use the latest XF preview, and referenced the latest GooglePlayServices packages (42.1001.0) since the hardcoded dependency on the outdated 23.* libs has finally been removed.

The package did compile out of the box except for the fact that you will have to reference the Places library here, so I guess there will be a breaking change:
https://www.nuget.org/packages/Xamarin.GooglePlayServices.Places/

The sample app didn't compile anymore and hit me with a bunch of weird exceptions, but hey, when did Xamarin "just work", right ;)

**Comment by Thijmen** [comment]
Did you get it working? I want to use Firebase but somehow CustomMap keeps me from using it.

**Comment by TorbenK** [comment]
Well, problem is that Xamarin.Forms.Maps has a hard dependency on Maps 29.0.0.1, so upgrading wont work currently. We have to wait for Xamarin to update this.

**Comment by hardcodet** [comment]
That hard dependency has been removed with Xamarin Forms 2.3.4. We finally get to use the latest and greatest.
