### ISSUE TITLE
CalloutClickedCommand not working

### ISSUE THREAD

**Issue by Lord-Link** [TorbenK/TK.CustomMap#200]
I was wondering if the CalloutClickedCommand is bindable since the documentation doesnt say its bindable?

> CalloutClickedCommand
> 
> Is getting executed when the callout of a pin gets tapped. On Android the whole callout is clickable, on iOS there will be a disclosure image visible on the right top.

I am attempting to bind this command but the function never gets executed when i click the callout. I have also attempted to attach the event directly with no success.

> Binding the event
`map.SetBinding(TKCustomMap.CalloutClickedCommandProperty, "CalloutClickedCommand");`

> Function when binding
`private async Task Callout_Clicked()
{
    ...
}`

> Directly setting the event
`map.CalloutClicked += Callout_Clicked;`

> Function when attaching event
`private void Callout_Clicked(object sender, EventArgs e)
{
    ...
}`

**Comment by TorbenK** [comment]
Check `IsCalloutClickable` on your pin.

**Comment by Lord-Link** [comment]
@TorbenK Thank you this was the issue.

**Comment by pamela032709** [comment]
opps! nevermind. I found it.
 is like a decade after but Im having the same exact issue. I don't have that property IsCalloutClickable, only have access to the CalloutClickedCommand is that the same? cause I click the pin and it only raises the title,not the event on the command.
