### ISSUE TITLE
How to create page GooglePlaces

### ISSUE THREAD

**Issue by stefancvetkovic** [TorbenK/TK.CustomMap#205]
Hi,
I downloaded your code, but I have some errors, and I am trying to use your code and logic in a separate soluton.

Can you give me a hint how to create GooglePlacePage with map view and what I need to call in order to autocomplete search from google api?
thanks!

**Comment by TorbenK** [comment]
Should be in the sample. What errors do you get?

**Comment by stefancvetkovic** [comment]
java.lang.IllegalArgumentException: already added :  Lcom/google/android/gms/location/places/zzl;
in project	CalloutSample.Droid
I am looking for this item, but I can't find it.
Also if I remove CalloutSample, and deploy other Android project (TK.CustomMap.Sample.Droid), I cant view anywhere autocomplete field. 
I use latest stable xamarin forms.
Thanks in advance.

**Comment by stefancvetkovic** [comment]
Heelo again. I fixed it, but I cant to show autocomplete search bar with map together?
relative layout just doesnt work.any hint?

**Comment by TorbenK** [comment]
No, works fine for me. Note that this is not part of the library, this is just a quick sample of an autocomplete implementation using the places api.

**Comment by stefancvetkovic** [comment]
Thanks.
I found out how to implement search bar. Just, please can you tell me how to add automatic pins? On which event should I put code?tnx

**Comment by TorbenK** [comment]
Sorry, I'm not sure what you mean by "auomatic pins".
