### ISSUE TITLE
nuget install for UWP

### ISSUE THREAD

**Issue by johnm01** [TorbenK/TK.CustomMap#208]
A follow on from'MapClicked does not fire'  I found that creating a simple maptest, the Mapclicked fires in Android and Ios - but I am working with UWP also for desktop and Win10 phone - where mapclicked does not work.
After installing TK.custommap into the solution, a reference to TK.Custommap.dll appears in the UWP project BUT there is no reference to TKCustommap.UWP.dll it in UWP project. Therefore the map defaults to XamFormsMap and therefore doesn't fire mapclicked.

The sample solution creates its own TK.CustomMap.UWP.dll and I have simply put in a reference to that compiled dll - this allows the mapclicked to fire correctly on UWP (proving that its the absence of TK.custommap.UWP causing the problem) but of course one has to change the dll depending on whether compiling for Desktop or ARM. (yes I should be able to import the raw code of the assemblies from the sample into my Project but I get so many errors, one loses the will to live)- I have tried to limit the import to just the TK.Custommap.UWP project - this reduces the errors on dlls not found but produces an apparently unrelated error 'Conflicting values for resource file ....Xamarin.forms.platform.uap.TabbedPagestyle.xbf' makepri     ARgghhhh - i didn;t touch anything to do with a tabbed page!!!!!

Is there any chance the nuget package could install the appropriate TK.custommap.UWP in the first place?? 

Alternatively any suggestions how and what(classes)   I should import from the sample solution in order to avoid practically every reference showing a warning and saying package not installed or producing seemingly unrelated rubbish?

**Comment by TorbenK** [comment]
Sorry, not much time recently. (I say that a lot actually)

UWP is not included in the NuGet yet because it is still in development. There will be a pre-release of 2.0 with UWP support when Xamarin.Forms 2.4 goes stable, at least that is what I planned. Also stated [here](https://github.com/TorbenK/TK.CustomMap/issues/202).

**Comment by johnm01** [comment]
Torben many many thanks - I've been messing around with monotouch and Android since xamarin was Novell and my current gripe is that one spends most of ones time trying sort out obscure errors in VS. - hence the efrustration creeping in.  I came upon your stuff and I find your style and explanation so so straightforward and easy to grasp. The product is superb. Look forward to the UWP edition - I can live with my workaround for now
