### ISSUE TITLE
google place search above the tkCustom map

### ISSUE THREAD

**Issue by abdulbasitnawab** [TorbenK/TK.CustomMap#212]
Hi
I have configured the places api and it is now showing hints in auto complete. I am using search bar above the tkcustommap. The issue i have is that when i click on auto complete suggestion, it is clicking on the map which is below the auto complete.

**Comment by abdulbasitnawab** [comment]
I solved the issue by making the focus event handler with delegate, Once the search box gets focus I change the width of the underneath absolute layout to fill screen. and when unfocussed i give it original width.

**Comment by poseydonfba** [comment]
You could post an example of your code, I'm having the same problem, thanks ...

**Comment by abdulbasitnawab** [comment]
Hi
 Sure let me explain the details.
First in the places auto complete API you have to make a public focus event handler. below are the changes i make in places auto complete API file
public delegate void FocusEventHandler(object source, FocusEventArgs e);
		public event FocusEventHandler SearchBarFocused;
public void searchFocus(object sender, FocusEventArgs e) { 
        	OnSearchBarFocused(e);
		}

		protected virtual void OnSearchBarFocused(FocusEventArgs e)
		{
			if (SearchBarFocused != null)
				SearchBarFocused(this, e);
		}

Then in the c# file  of the main page where you are displaying maps with search bar like

searchTo.SearchBarFocused += getFocussed;

public void getFocussed(object source, FocusEventArgs e)
		{
			if (e.IsFocused == true)
			{

				var c = BoundsConstraint.FromExpression((Expression<Func<Rectangle>>)(() => new Rectangle(0, 0, mapContainer.Width, 400)), new View[0]);

				RelativeLayout.SetBoundsConstraint(_searchStack, c);
				mapContainer.ForceLayout();

			}

			else
			{
				var c = BoundsConstraint.FromExpression((Expression<Func<Rectangle>>)(() => new Rectangle(0, 0, mapContainer.Width, 40)), new View[0]);

				RelativeLayout.SetBoundsConstraint(_searchStack, c);
				mapContainer.ForceLayout();
			}

		}
The logic behind is that when you click (focus) int he search bar it will draw a rectangle above the map to hide the map, and on unfocus it will be removed.
The _searchStack in XAML is follow
<StackLayout VerticalOptions="FillAndExpand" x:Name="_searchStack" BackgroundColor="Transparent"  Orientation="Vertical" HeightRequest="40"
					RelativeLayout.XConstraint="{ConstraintExpression Type=RelativeToParent,Property=AnchorX, Factor=0, Constant=0}"
					RelativeLayout.YConstraint="{ConstraintExpression Type=RelativeToParent,Property=AnchorY, Factor=0, Constant=0}"
					RelativeLayout.WidthConstraint="{ConstraintExpression Type=RelativeToParent,Property=Width, Factor=1, Constant=0}"
					RelativeLayout.HeightConstraint="{ConstraintExpression Type=RelativeToParent,Property=Height, Factor=0, Constant=40}"
				/>
Hope it will help.

**Comment by poseydonfba** [comment]
Thanks for replying, it helped me, it's now working normal......

**Comment by abdulbasitnawab** [comment]
Great. That's nice to hear.
