### ISSUE TITLE
icon image

### ISSUE THREAD

**Issue by johnm01** [TorbenK/TK.CustomMap#213]
should changing the image of the (TKcustomPin) pin icon be as simple as 

 mypin.Image=Device.OnPlatform("Icon-Small.png", "icon.png", "notcomplete.png");

because 
a) when I do this in my own adapted code it crashes (obviously some flaw in my code and  
b) when I try to alter the TKcustomsample code it simply ignores it and uses the default icon  (I've  just marginally changed the samplecode - added an embedded image (as content in UWP) and called it as above in the 'longpress' method.

fact is I cant see how to change the image
I note that TKCustomPin.Image is actually an image source so I've tried (to no avail)
mypin.Image = imagesource("notcomplete.png");

Does the image have to be specially constituted?  (the one I am trying to substitute is 36x36 just like the default) 
I have tested that the images exist - they can be displayed using xamarin.Forms.Image.

Any idea what I'm doing wrong,  ladies and gentlemen?

**Comment by TorbenK** [comment]
UWP is not included in the current NuGet.

This should work if you use the dev branch though.

**Comment by johnm01** [comment]
Sorry didn't make myself totally clear
I am also testing on Android and the same things happen - I cannot seem to be able to change the icon image
thanks all the same Torbent - I continue to be in awe of your excellent  addon - I find mapping so complex

**Comment by TorbenK** [comment]
Are you using the latest XF? There seem to be several issues on Android with the newest release. Besides that, it should work what you are doing.

**Comment by johnm01** [comment]
Hi Torbent- I am using the latest 1.5.2. pre 1.   On Android if I try to set an icon image it falls over with unhandled exception (interesting not where I set the icon but seems to call MapCenter fromthe sampleviewmodel code several times then expires with the following output message.
If I eliminate the icon image - works fine - The certificate is set in the Android manifest 
and I have tried old and new ways viz:-
 
    <meta-data android:name="com.google.android.maps.v2.API_KEY" android:value="mykey" />-


As I said it doesn't fall over at the line I assign an icon image but seems to fall out after several calls to MapCenter - I've tried remming out the binding to Mapcenter to no avail




I think the problem is somewhere else -


  _:00.924 I/DynamiteModule(17630): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:2
04-21 14:09:00.924 I/DynamiteModule(17630): Selected remote version of com.google.android.gms.googlecertificates, version >= 2
04-21 14:09:00.932 W/System  (17630): ClassLoader referenced unknown path: /data/user/0/com.google.android.gms/app_chimera/m/0000000f/n/armeabi_

**Comment by johnm01** [comment]
Hi TK 
I have got the icon now working in the original TXsample  file under Android - I simply 'boilerplated' sa  me code into my App so I can't think what's going on to give the above 'unhandled' in my app. Ah well back to the beginning - try another copy and paste and see how it goes
