### ISSUE TITLE
Crash on second viewing of the maps control

### ISSUE THREAD

**Issue by Bobisback** [TorbenK/TK.CustomMap#214]
Xamarin Forms 2.3.4.231
Android Target and compile are 7.1
TK Maps is at 1.5.2 pre1

If I open the maps it works fine. if I go back and then open the map again, sometimes I get a crash that is below.

	04-24 00:17:38.425 I/MonoDroid(26032): UNHANDLED EXCEPTION:
	04-24 00:17:38.485 I/MonoDroid(26032): System.NullReferenceException: Object reference not set to an instance of an object.
	04-24 00:17:38.485 I/MonoDroid(26032):   at TK.CustomMap.Droid.TKCustomMapRenderer.SetSelectedItem () [0x00020] in <5b9d79f7c2904332851a10b98f67661f>:0 
	04-24 00:17:38.485 I/MonoDroid(26032):   at TK.CustomMap.Droid.TKCustomMapRenderer.FormsMapPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x0003f] in <5b9d79f7c2904332851a10b98f67661f>:0 
	04-24 00:17:38.485 I/MonoDroid(26032):   at (wrapper delegate-invoke) <Module>:invoke_void_object_PropertyChangedEventArgs (object,System.ComponentModel.PropertyChangedEventArgs)
	04-24 00:17:38.485 I/MonoDroid(26032):   at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x0000a] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:136 
	04-24 00:17:38.485 I/MonoDroid(26032):   at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Element.cs:380 
	04-24 00:17:38.485 I/MonoDroid(26032):   at TK.CustomMap.TKCustomMap.OnPropertyChanged (System.String propertyName) [0x00000] in <5e06433f227d45a6805d7e38cca5c59c>:0 
	04-24 00:17:38.485 I/MonoDroid(26032):   at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.BindableObject+SetValueFlags attributes, System.Boolean silent) [0x000f4] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:589 
	04-24 00:17:38.485 I/MonoDroid(26032):   at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.BindableObject+SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:386 
	04-24 00:17:38.485 I/MonoDroid(26032):   at Xamarin.Forms.BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget) [0x001f9] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindingExpression.cs:173 
	04-24 00:17:38.485 I/MonoDroid(26032):   at Xamarin.Forms.BindingExpression.Apply (System.Boolean fromTarget) [0x0003e] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindingExpression.cs:55 
	04-24 00:17:38.485 I/MonoDroid(26032):   at Xamarin.Forms.BindingExpression+BindingExpressionPart.<PropertyChanged>b__47_0 () [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindingExpression.cs:539 
	04-24 00:17:38.485 I/MonoDroid(26032):   at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/4009/3a62f1ea/source/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36 
	04-24 00:17:38.485 I/MonoDroid(26032):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in /Users/builder/data/lanes/4009/3a62f1ea/source/monodroid/src/Mono.Android/platforms/android-25/src/generated/Java.Lang.IRunnable.cs:81 
	04-24 00:17:38.485 I/MonoDroid(26032):   at (wrapper dynamic-method) System.Object:2abcefc8-99d3-4511-9f33-36e6613f3163 (intptr,intptr)
	04-24 00:17:38.485 D/Mono    (26032): Assembly Ref addref HockeySDK.AndroidBindings[0xec844340] -> System[0xd909f2c0]: 19
	04-24 00:17:38.505 W/art     (26032): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
I tried to debug your code with no luck. I could not walk through it. Judging by looking through it the only thing you do not check for null is the markers list in your SetSelectedItem method. Any ideas what could be going on here?

Thanks,
Sean

P.S I tried putting the symbol files to get a line number or something but I had no luck. When I put the pdb files in the bin folder it did not seem to help at all.

**Comment by Bobisback** [comment]
Below is my code 

        private async void GetMapCenter()
        {
            var userLocation = await locator.GetPositionAsync(10000);
            MapCenter = new Position(userLocation.Latitude, userLocation.Longitude);
            var addresses = await geocoder.GetAddressesForPositionAsync(MapCenter);
            var address = addresses.FirstOrDefault();
            var pin = new TKCustomMapPin()
            {
                Position = MapCenter,
                Title = address,
                ShowCallout = true,
                IsDraggable = true
            };

            Pins.Add(pin);
            SelectedPin = pin;
            MapRegion = MapSpan.FromCenterAndRadius(SelectedPin.Position, Distance.FromKilometers(1));
        }

It is crashing just after the last line of code. But it is on a different unhanded thread then this code. It appears to be crashing during a on property changed event.

**Comment by Bobisback** [comment]
<img width="790" alt="screen shot 2017-04-24 at 12 35 11 am" src="https://cloud.githubusercontent.com/assets/2651822/25323755/31e75fb2-2887-11e7-954e-614e598d1146.png">


So for some reason on line 547 FormsMap is null when this is getting called which is causing a crash.

I recompiled the project with the following code added just before on line 547. Seems to work now though I am not sure why it is getting called when formsmap is null in the first place. So now that function looks like this:

	private void SetSelectedItem()
        {
            if (this._selectedMarker != null)
            {
                this._selectedMarker.HideInfoWindow();
                this._selectedMarker = null;
            }
            if (this.FormsMap == null)
            {
                return;
            }
            if (this.FormsMap.SelectedPin != null)
            {
                if (!this._markers.ContainsKey(this.FormsMap.SelectedPin)) return;

                var selectedPin = this._markers[this.FormsMap.SelectedPin];
                this._selectedMarker = selectedPin;
                if (this.FormsMap.SelectedPin.ShowCallout)
                {
                    selectedPin.ShowInfoWindow();
                }
                this.MapFunctions.RaisePinSelected(this.FormsMap.SelectedPin);
            }
        }

This may be related to this issue, both issues are happening on the on property changed event. https://github.com/TorbenK/TK.CustomMap/issues/103

Also I noticed that the function SetSelectedItem is being called 2 or 3 times with FormsMap as null before finally it is called and it is not null. So something fishy is going on. The above fix might be a good temp fix but we really need to figure out hte reason why it is null in the first place.

**Comment by Bobisback** [comment]
Yes I can confirm that there is many cases where this is crashing now. I am getting forms map null errors in almost every property that I change. Some of the properties there are checks for it but most of them there are not.

**Comment by TorbenK** [comment]
Please try the dev branch. It should work again.

**Comment by Bobisback** [comment]
So now it is not crashing but on the second view and sometimes the first view it is not zooming into the user. i am not sure if it is related.

**Comment by ryanharding** [comment]
I am experiencing the same sort of behavior. 

My map causes an exception consistently the second time I try open the view containing the control.

My project is xaml c# with a MVVM pattern.

This happens if I try bind to the CustomPins on the control. 

I've tried setting the ObservableCollection<TKCustomMapPin> to a new ObservableCollection<TKCustomMapPin>() on page load, however still throws an exception the second time i come view the page.

I have updated to the latest version v1.6.1 (was happening before as well)

**Comment by TorbenK** [comment]
That's sad. Would you be able to share the project, or a small repro project?

**Comment by ryanharding** [comment]
HI @TorbenK

In building a quick small repro project for you and running it to reproduce my issues. I noticed it wasn't happening anymore. It seems it was a nuget bug with not properly cleaning and referencing the updated packages in VS2017. 

Removing, cleaning and re-adding your nuget package fixed the issue.

Sorry for the inconvenience and thanks for the cool control.

**Comment by TorbenK** [comment]
Great to hear that it works! 

Closing this.
