### ISSUE TITLE
Get Geolocation when clicking on PlacesAutocomplete's predictions

### ISSUE THREAD

**Issue by Grodart** [TorbenK/TK.CustomMap#215]
Hi there,
i would like to know if we can get the clicked prediction's geolocation (Latitude & Longitude) using PlacesAutoComplete?

When i use PlacesAutoComplete, i'm only able to get the 2 following fields : 
  - Description
  - Subtitle

I'm using PlacesAutoComplete on top of a tkCustomMap.
I would like to add a Pin on the map when i Click on an autocomplete prediction. 
Is that possible? 

Thank you very much for all your help :)

**Comment by abdulbasitnawab** [comment]
Hi
Yes this is achievable. I have done the similar thing. The thing is if you are using GMSPlaces for search Yes it will provide you Description and Subtitle then you have to pass this place id to a separate call to get its location info. 
There are three type of searches OSM, Native and Google places.
The first two response contains latitude and longitude. For google places you have to make another call and pass the place id to get its location.
Once you get this latitude and longitude you can add a new pin on that location.

**Comment by abdulbasitnawab** [comment]
Below is the code snippet
`public Command<IPlaceResult> ToSelectedCommand
		{
			get
			{
				return new Command<IPlaceResult>(async (p) =>
				{

					GmsPlacePrediction placeResult = (GmsPlacePrediction)p;
					this._toPlace = placeResult;
					var location = await GmsPlace.Instance.GetDetails(placeResult.PlaceId);
					this._to = new Xamarin.Forms.Maps.Position(Convert.ToDouble(location.Item.Geometry.Location.Latitude), Convert.ToDouble(location.Item.Geometry.Location.Longitude));

					// draw pin 
					PinsList.Clear();
					var pin = new TK.CustomMap.TKCustomMapPin();
					pin.ID = "1";
					pin.Position = _to;
					pin.DefaultPinColor = Color.Green;
					pin.Title = this._toPlace.Description;
					PinsList.Add(pin);
                                        // navigate to new pin
					var mspan = Xamarin.Forms.Maps.MapSpan.FromCenterAndRadius(
						new Xamarin.Forms.Maps.Position(_to.Latitude, _to.Longitude), Xamarin.Forms.Maps.Distance.FromMiles(DISTANCE));

					map.MapRegion = mspan;
					map.MoveToMapRegion(mspan, true);
				});


			}
		}`

**Comment by Grodart** [comment]
Sorry for the delay, i wasn't able to work on it before :)
Your snippet did the trick ! 
Thank you very much abdulbasitnawab, you saved me a lot of time!
