### ISSUE TITLE
Open callout without click in pin

### ISSUE THREAD

**Issue by andreluiz1987** [TorbenK/TK.CustomMap#217]
I wonder if it's possible to open the callout without having to click on the marker.

**Comment by vincentcastagna** [comment]
Heya, I opened a thread few weeks ago : 

https://github.com/TorbenK/TK.CustomMap/issues/162

I managed to get it work on the emulator ... but on my test phone on android 6.0 (galaxy A5 samsung) it seems not to work. The callout is showing when I add the first pin on the map, and when I add another one (following first adding action), call out does not pop ... I don't understand why it works on emulator and not on real phone.

**Comment by andreluiz1987** [comment]
I managed to solve, I downloaded the project and made a method that opens the Callout, I also created a property in the TkCustomMapPin class.

**Comment by TorbenK** [comment]
@andreluiz1987 If you have a solution which covers atleast Android and iOS, a PR will be appreciated.

**Comment by andreluiz1987** [comment]
Okay, I'll do it today.

**Comment by andreluiz1987** [comment]
done
