### ISSUE TITLE
TK.CustomMap not work on api => 23

### ISSUE THREAD

**Issue by sabetghadam** [TorbenK/TK.CustomMap#219]
hi
TK.CustomMap  not work on api => 23 why ?

app hold and no response in map page

**Comment by abdulbasitnawab** [comment]
What is your Minimum android version and Target Android version?
Did you give the required permissions.

**Comment by jfversluis** [comment]
Are you receiving any error messages? Also please check your application output closely. There may be some silent error messages in there as well.

**Comment by sabetghadam** [comment]
compile is 7.1 
minimal is 4.0.3 (15)
target is 6
http://snap.ashampoo.com/6c4nJWz1

only rash when start mapview.
after login and start mapview only i see white screen and crash app.

My computer teamweaver .
600 222 726 / 3333

**Comment by Bobisback** [comment]
I am having the same issue as this, but I cannot not test it very well since I am having issues running maps on a emulator.

**Comment by abdulbasitnawab** [comment]
I am using Minimum version 4.2 and target 7.1 and its working well. Did you add a google map key?

**Comment by sabetghadam** [comment]
see this video http://snap.ashampoo.com/9DgMOIaV
Abdul i lost ur email can u send me email to tarraharshad@gmail.com

**Comment by sabetghadam** [comment]
logs after crash :
05-09 10:05:56.091 D/Mono    ( 2188): DllImport attempting to load: '/system/lib/liblog.so'.
05-09 10:05:56.097 D/Mono    ( 2188): DllImport loaded library '/system/lib/liblog.so'.
05-09 10:05:56.097 D/Mono    ( 2188): DllImport searching in: '/system/lib/liblog.so' ('/system/lib/liblog.so').
05-09 10:05:56.097 D/Mono    ( 2188): Searching for '__android_log_print'.
05-09 10:05:56.097 D/Mono    ( 2188): Probing '__android_log_print'.
05-09 10:05:56.097 D/Mono    ( 2188): Found as '__android_log_print'.
05-09 10:05:56.098 I/MonoDroid( 2188): UNHANDLED EXCEPTION:
Thread started: <Thread Pool> #18
Thread started: <Thread Pool> #19
05-09 10:05:56.117 D/Mono    ( 2188): [0xd7ebf930] worker starting
Thread started: <Thread Pool> #20
05-09 10:05:56.126 D/Mono    ( 2188): [0xd707f930] worker starting
Thread started: <Thread Pool> #21
Thread started: <Thread Pool> #22
05-09 10:05:56.141 D/Mono    ( 2188): [0xd7ebf930] hill climbing, change max number of threads 5
05-09 10:05:56.143 D/Mono    ( 2188): [0xd6dbf930] worker starting
Thread started: <Thread Pool> #23
05-09 10:05:56.154 D/Mono    ( 2188): [0xd65fe930] worker starting
05-09 10:05:56.160 D/Mono    ( 2188): [0xd66ff930] worker starting
05-09 10:05:56.175 I/MonoDroid( 2188): System.NullReferenceException: Object reference not set to an instance of an object.
05-09 10:05:56.176 I/MonoDroid( 2188):   at Xamarin.Forms.Maps.Android.MapRenderer.OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x00050] in <ce78a47981e5432b9ec8845afc9e5775>:0 
05-09 10:05:56.176 I/MonoDroid( 2188):   at TK.CustomMap.Droid.TKCustomMapRenderer.OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x00000] in <57ce468fe7e14b1aa37760c3f4794f8a>:0 
05-09 10:05:56.176 I/MonoDroid( 2188):   at Xamarin.Forms.Platform.Android.FormsViewGroup.n_OnLayout_ZIIII (System.IntPtr jnienv, System.IntPtr native__this, System.Boolean p0, System.Int32 p1, System.Int32 p2, System.Int32 p3, System.Int32 p4) [0x00008] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android.FormsViewGroup\obj\Release\generated\src\Xamarin.Forms.Platform.Android.FormsViewGroup.cs:240 
05-09 10:05:56.176 I/MonoDroid( 2188):   at (wrapper dynamic-method) System.Object:4259f25f-34c7-4457-b028-dc54403454e8 (intptr,intptr,bool,int,int,int,int)
05-09 10:05:56.186 D/Mono    ( 2188): [0xd707f930] hill climbing, change max number of threads 14
05-09 10:05:56.190 W/art     ( 2188): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
05-09 10:05:56.194 D/Mono    ( 2188): DllImport searching in: '__Internal' ('(null)').
05-09 10:05:56.194 D/Mono    ( 2188): Searching for 'java_interop_jnienv_throw'.
05-09 10:05:56.194 D/Mono    ( 2188): Probing 'java_interop_jnienv_throw'.
05-09 10:05:56.194 D/Mono    ( 2188): Found as 'java_interop_jnienv_throw'.
An unhandled exception occured.

**Comment by Bobisback** [comment]
So I updated to the latest dev branch and this was fixed. My guess is it is related to this bug: https://github.com/TorbenK/TK.CustomMap/issues/214

**Comment by sabetghadam** [comment]
i added via nuget pluhin .how to replace on vs nuget ?

**Comment by Bobisback** [comment]
You have to manually compile it, then get the dlls that vs creates and either reference them yourself or do like I do and add them to the respective libs folder in the nuget packages folder.

I also had to make some other changes through beyond what the dev branch has because I was still getting all kinds of crashes on android.

P.S if you do anything with pins, circles, or polygons I was getting crashes so I had to add some code to deal with this as well. It is all working great now.

**Comment by sabetghadam** [comment]
i get error from ur code , i can't compile . and where is dll in ur project folder ?

**Comment by Bobisback** [comment]
ya, first of all this is not my code. And second of all it looks like you are running into the crashes I was getting that I fixed with some more checks. Go into the android map renederer and anywhere you see access to FormsMap without a null check put one in. This fixed my crashes.

The above is done in the project that you get from this github.

The dlls are in the bin folder where all dlls go when you compile a VS project.

**Comment by TorbenK** [comment]
If you take the latest dev branch, which fixes the issue with the latest `Xamarin.Forms.MapRenderer` implementing `IOnMapReadyCallback` by using [this](https://forums.xamarin.com/discussion/92565/android-ionmapreadycallback-forms-2-3-4) "hack", it should not be neccessary to add extra checks.

**Comment by sabetghadam** [comment]
i get this error message in crash azur report
TKCustomMapRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e)

System.MissingMethodException: Method 'Android.Gms.Maps.MapView.get_Map' not found.

**Comment by sabetghadam** [comment]
TKCustomMapRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e)
System.MissingMethodException: Method 'Android.Gms.Maps.MapView.get_Map' not found.

Method 'Android.Gms.Maps.MapView.get_Map' not found.

1
TKCustomMapRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e)
2
VisualElementRenderer`1[TElement].SetElement (TElement element) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:193
3
IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:129
4
Platform.CreateRenderer (Xamarin.Forms.VisualElement element) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\Platform.cs:289
5
VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:74
6
VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:207
7
VisualElementPackager.Load () C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:58
8
VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:337
9
VisualElementRenderer`1[TElement].SetElement (TElement element) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:196
10
IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:129
11
Platform.CreateRenderer (Xamarin.Forms.VisualElement element) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\Platform.cs:289
12
VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:74
13
VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:207
14
VisualElementPackager.Load () C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:58
15
VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:337
16
VisualElementRenderer`1[TElement].SetElement (TElement element) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:196
17
IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:129
18
Platform.CreateRenderer (Xamarin.Forms.VisualElement element) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\Platform.cs:289
19
VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:74
20
VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:207
21
VisualElementPackager.Load () C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:58
22
VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:337
23
VisualElementRenderer`1[TElement].SetElement (TElement element) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:196
24
IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:129
25
Platform.CreateRenderer (Xamarin.Forms.VisualElement element) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\Platform.cs:289
26
VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:74
27
VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:207
28
VisualElementPackager.Load () C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:58
29
VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:337
30
VisualElementRenderer`1[TElement].SetElement (TElement element) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:196
31
IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:129
32
Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Support.V4.App.FragmentManager fragmentManager) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\Platform.cs:325
33
FragmentContainer.OnCreateView (Android.Views.LayoutInflater inflater, Android.Views.ViewGroup container, Android.OS.Bundle savedInstanceState) C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\AppCompat\FragmentContainer.cs:66
34
Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_inflater, System.IntPtr native_container, System.IntPtr native_savedInstanceState)
35
(wrapper dynamic-method) System.Object:d872e820-7bc0-4dc5-b648-3ab68376c8c2 (intptr,intptr,intptr,intptr,intptr)

**Comment by TorbenK** [comment]
please test 1.6.0-pre1

**Comment by sabetghadam** [comment]
where is this ? in nuget i see 1.5 only

**Comment by TorbenK** [comment]
https://www.nuget.org/packages/TK.CustomMap/1.6.0-pre1

**Comment by sabetghadam** [comment]
after update i see this error new :
Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Xamarin.GooglePlayServices.Places, Version=1.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Xamarin.GooglePlayServices.Places.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	Kabby.Droid

**Comment by TorbenK** [comment]
yes, i think i forgot the dependency. you need to install the package manually.

**Comment by sabetghadam** [comment]
how to i add this ?

**Comment by TorbenK** [comment]
https://www.nuget.org/packages/Xamarin.GooglePlayServices.Places/

**Comment by sabetghadam** [comment]
after install see this :
Severity	Code	Description	Project	File	Line	Suppression State
Error		error: package com.google.android.gms.location.places.ui does not exist
		com.google.android.gms.location.places.ui.PlaceSelectionListener	Kabby.Droid	C:\Projects\Kabby\SourceCode\v4\Kabby\Kabby\Kabby\Droid\obj\Debug\android\src\mono\com\google\android\gms\location\places\ui\PlaceSelectionListenerImplementor.java	8

**Comment by sabetghadam** [comment]
hello ? stil problem

**Comment by sabetghadam** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Xamarin.GooglePlayServices.Places, Version=1.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Xamarin.GooglePlayServices.Places.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	Kabby.Driver.Droid

**Comment by sabetghadam** [comment]
i sent ur code to recycle only wasted time and dirty support. everybody never use this i lost 4k only for use this.
