### ISSUE TITLE
How to navigate to a Pin (or list of pins )

### ISSUE THREAD

**Issue by vincentcastagna** [TorbenK/TK.CustomMap#220]
Hello,

I would like to allow a user to navigate from his position to a given pin (or later to the list of pins that my Api will retrieve as Google/osm retrieves a list of adress).

These pins don't hold an adress but only  Latitude and Longitude (on a Point object (x,y). 

How could I manage to naviguate to one given pin by clicking on a single button passing latitude and longitude of the given pin. Something like that, but in my app : http://maps.google.com/?daddr=37.788463,-122.392545

Btw, I just need clews :)

Thanks.

**Comment by TorbenK** [comment]
Pick one:

```
/// <summary>
/// Bindable Property of <see cref="MapCenter"/>
/// </summary>
public static readonly BindableProperty MapCenterProperty = BindableProperty.Create(
	nameof(MapCenter),
	typeof(Position),
	typeof(TKCustomMap),
	default(Position),
	defaultBindingMode: BindingMode.TwoWay);

/// <summary>
/// Bindable Property of <see cref="MapRegion"/>
/// </summary>
public static readonly BindableProperty MapRegionProperty = BindableProperty.Create(
	nameof(MapRegion),
	typeof(MapSpan),
	typeof(TKCustomMap),
	defaultBindingMode: BindingMode.TwoWay);
	
/// <summary>
/// Moves the visible region of the map to cover all positions
/// </summary>
/// <param name="positions">The positions to fit the visible region</param>
void FitMapRegionToPositions(IEnumerable<Position> positions, bool animate = false);
		
/// <summary>
/// Moves the visible region to the specified <see cref="MapSpan"/>
/// </summary>
/// <param name="region">Region to move the map to</param>
/// <param name="animate">If the region change should be animated or not</param>
void MoveToMapRegion(MapSpan region, bool animate);
		
/// <summary>
/// Moves the visible region to the specified collection <see cref="MapSpan"/>
/// </summary>
/// <param name="regions">Regions to move the map to</param>
/// <param name="animate">If the region change should be animated or not</param>
void FitToMapRegions(IEnumerable<MapSpan> regions, bool animate);
```

I do something like this in the sample, when the pin is selected the camera is centered on top of it.

https://github.com/TorbenK/TK.CustomMap/blob/Development/Sample/TK.CustomMap.Sample/TK.CustomMap.Sample/ViewModels/SampleViewModel.cs#L489

**Comment by vincentcastagna** [comment]
Yep, thanks for you fast answering ^^ 

I think my question was not clear ... I want that , when the user will click on the button it will draw the route that he has to take (by car) to go to this pin from his current location with instructions just like in your sample. I read it but I don't see the snippet that I can extract from your sample to navigate to a Longitude/Lattitude position instead of placeAutocomplete given by Google/Osm. 

Thanks Torben.

**Comment by TorbenK** [comment]
See my edit.

**Comment by vincentcastagna** [comment]
Sorry Torben, that's not really my question :). You show me the snippet that will change the focus of the "camera" when a pin is selected. My UI is as fellow  and will probably be clearer to you to understand my needs => 

When a user will select a pin, the pin is selected. I'm listening to  this event in my page, and when the pin is selected I show to the user 5 buttons. One of this button is a button called "Navigate To" => That means I want to guide the user with instructions and the route (drawn on the map) he has to follow to get there only with Latitude and Longitude as Geoloc information. 

Sorry If I was not clear ... Or probably I dont understand myself haha.

Thanks.

**Comment by TorbenK** [comment]
Well, indeed, I am not sure if I understand the question correctly. 

Here is what I think you're asking for:

- User clicks on the pin
- Add a `TKRoute` and let it be calculated
- Display the instructions using the `TKStep` array included in the calculated `TKRoute`

There is a sample where I extract the instructions out the the `TKRoute` and display it in a `WebView`.

https://github.com/TorbenK/TK.CustomMap/blob/Development/Sample/TK.CustomMap.Sample/TK.CustomMap.Sample/ViewModels/HtmlInstructionsViewModel.cs

**Comment by vincentcastagna** [comment]
Yep thats exactly what I want, to calculate the best route and draw it one the map (but the route form current position the a given pin). 

What I want to achieve is from current position to pin. In the sample, in the addRouteViewModel.cs, the route is drawn between two pins, and not from current location. So my source is current location ... Should I simulate/create a pin to my current location ? 

Btw, I guess there is no way to achieve a turn by turn naviguation mode such as google maps native app is doing ? 

Thanks

**Comment by TorbenK** [comment]
Just pass the user position as source, you do not need a pin.

No, that is not possible and also not allowed by the terms of use. You can start the build in navigation on the device though.
