### ISSUE TITLE
How to use route on this map

### ISSUE THREAD

**Issue by Micnick** [TorbenK/TK.CustomMap#221]
I need your help to implement route on this map

**Comment by vincentcastagna** [comment]
I asked same question yesterday. 

See sample given in this repository. You need to implement property in your viewModel : 

https://github.com/TorbenK/TK.CustomMap/blob/Development/Sample/TK.CustomMap.Sample/TK.CustomMap.Sample/ViewModels/SampleViewModel.cs#L288

You need this command in your view model : 
https://github.com/TorbenK/TK.CustomMap/blob/Development/Sample/TK.CustomMap.Sample/TK.CustomMap.Sample/ViewModels/AddRouteViewModel.cs#L70

And bind your map on this property and this command in your MapPage. 

```
 _customMap.SetBinding(TKCustomMap.RoutesProperty, "Routes");
 _customMap.SetBinding(TKCustomMap.AddRouteCommand, "AddRouteCommand");
```

**Comment by Micnick** [comment]
tanks for the answer, but on my map instance, the RoutePin property no found, only use TKCustomMapPin

**Comment by TorbenK** [comment]
`RoutePin` comes from the sample project. 

Anyway, you do not need any pin to add a route.
