### ISSUE TITLE
MyMap.IsShowingUser no show

### ISSUE THREAD

**Issue by Micnick** [TorbenK/TK.CustomMap#224]
Configure the MyMap.IsShowing User property but does not display anything on the map

**Comment by TorbenK** [comment]
I guess you are talking about Android.

If you use the latest XF, you need to manually build the assemblies using the dev branch. Otherwise you need to use XF 2.3.

**Comment by Micnick** [comment]
I'm initializing the IsShowingUser property from the PCL project, just initialize the property to true, but the control is not displayed, should I do something extra in the android and ios projects? Or it should only work by initializing the property to true

**Comment by TorbenK** [comment]
Probably this issue: #228

**Comment by rohitvipin** [comment]
Work around : 
private GoogleMap _googleMap;
public override void OnMapReady(GoogleMap googleMap)
 {
            googleMap.UiSettings.MyLocationButtonEnabled =
            googleMap.MyLocationEnabled = Element?.IsShowingUser ?? false;
            base.OnMapReady(googleMap);
            _googleMap = googleMap;
 }

protected override void OnElementPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
{
            base.OnElementPropertyChanged(sender, e);
            if (e?.PropertyName == Map.IsShowingUserProperty.PropertyName)
            {
                if (_googleMap != null)
                {
                    _googleMap.MyLocationEnabled = Element?.IsShowingUser ?? false;
                }
            }
}
