### ISSUE TITLE
FYI: Circument the IsMapReady hack

### ISSUE THREAD

**Issue by hardcodet** [TorbenK/TK.CustomMap#226]
Hi there

I just ran into the same issue as you did with the closed MapReady callback on Android and noticed the reflection hack you put in. FYI, I just created a private wrapper class that I registered instead to customize my map - that worked like a charm:

    public class MapReadyListener : Java.Lang.Object, IOnMapReadyCallback
    { 
        public void OnMapReady(GoogleMap googleMap)
        {
            //my custom stuff went here
        }
    }

And in the renderer, I registered that one accordingly:

    protected override void OnElementChanged(ElementChangedEventArgs<Map> e)
    {
        base.OnElementChanged(e);
        Control?.GetMapAsync(myMapListener);
    }

I initially didn't get this to work due to the callback never being called, but extending Java.Lang.Object did the trick. If this is helpful, please grab the snippet. Otoh, if this may be brittle in some cases, I'd be happy to header about that, too :)

**Comment by TorbenK** [comment]
Interesting. Thank you!
