### ISSUE TITLE
MoveToRegion not working

### ISSUE THREAD

**Issue by maxdiable** [TorbenK/TK.CustomMap#228]
hi, this is may code:
    var newYork = new Position(40.7142700, -74.0059700);
            m_map = new TKCustomMap(MapSpan.FromCenterAndRadius(newYork, Distance.FromKilometers(2)));

            m_map.MoveToRegion(MapSpan.FromCenterAndRadius(new Xamarin.Forms.Maps.Position(52.219147, 6.893663), Distance.FromMiles(3)).WithZoom(9));

            this.Content = m_map;

but MoveToRegion not working.. not made zoom
any idea ?

br
Max

**Comment by TorbenK** [comment]
Sorry for beeing late. This is most due to XF 2.3.4, you either take the dev branch or downgrade to XF 2.3.3. I will try to release a version compatible with 2.3.4 this week though.

**Comment by maxdiable** [comment]
ok 
tanks :)
