### ISSUE TITLE
How to get Distance Rout

### ISSUE THREAD

**Issue by Micnick** [TorbenK/TK.CustomMap#229]
I need capture the Distance Rout to show it on a label, how do i this?
tanks

**Comment by vincentcastagna** [comment]
@Micnick 

Check the sample here it is : 

https://github.com/TorbenK/TK.CustomMap/blob/Development/Sample/TK.CustomMap.Sample/TK.CustomMap.Sample/ViewModels/HtmlInstructionsViewModel.cs

If you want the distance you got it in route.Steps.Distance in the foreach loop as example. Implement it and/or use it your own way.
