### ISSUE TITLE
CustomPins.Add and Clear

### ISSUE THREAD

**Issue by TioWidow** [TorbenK/TK.CustomMap#23]
After upgrading the version of the package (to last), the methods add and clear the CustomPins Collection were removed, what happened?

```
TKCustomMap map;
var CustomPin = new TKCustomMapPin ();
CustomPin.ShowCallout = true;
CustomPin.DefaultPinColor = Color.Red;
CustomPin.Position = new Xamarin.Forms.Maps.Position (item.Y,item.X);
CustomPin.Title = item.Value.ToString ();
CustomPin.Subtitle = item.Endereco;
map.CustomPins.Add(CustomPin);
```

**Comment by TorbenK** [comment]
Hi,

`CustomPins` was changed from `ObservableCollection` to `IEnumerable`. That lets you not just bind `ObservableCollection` but everyhting which implements `IEnumerable`. On `IEnumerable` there are no `Add`, `Remove` or `Clear` functions available. 

Change your code like this to make it exactly work like before:

``` CSharp
ObservableCollection<TKCustomMapPin> myList = new ObservableCollection<TKCustomMapPin>();
map.CustomPins = myList;

var CustomPin = new TKCustomMapPin ();
CustomPin.ShowCallout = true;
CustomPin.DefaultPinColor = Color.Red;
CustomPin.Position = new Xamarin.Forms.Maps.Position (item.Y,item.X);
CustomPin.Title = item.Value.ToString ();
CustomPin.Subtitle = item.Endereco;

myList.Add(CustomPin);

```

**Comment by TioWidow** [comment]
Thank you for your attention and for your great work

**Comment by TorbenK** [comment]
You are very much welcome
