### ISSUE TITLE
iOS NativePlacesApi throws NullReferenceException if Phone Number or Url is null

### ISSUE THREAD

**Issue by djadu** [TorbenK/TK.CustomMap#230]
NativePlacesAPI implementation for iOS needs null check for PhoneNumber and Url (this has been done on Android).

The following lines should be replaced
`InternationalPhoneNumber = i.PhoneNumber.ToString(),`
`Website = i.Url.ToString()`

Correction is
`InternationalPhoneNumber = i.PhoneNumber,`
`Website = i.Url?.ToString()`

**Comment by TorbenK** [comment]
Thanks, I'll add the fix in the next release.

**Comment by TorbenK** [comment]
1.6.0-pre3 includes the fix
