### ISSUE TITLE
Route Not displaying

### ISSUE THREAD

**Issue by sktdeepak** [TorbenK/TK.CustomMap#231]
i ran through the sample application,Pin point is displayed and route not displayed, has someone face similar situation like this?

[
![screenshot_20170717-123332](https://user-images.githubusercontent.com/14029491/28313740-a04bf558-6bd5-11e7-9295-8749a5afc59b.png)
](url)

**Comment by TorbenK** [comment]
probably missing the API key.

**Comment by sktdeepak** [comment]
Thanks For your response, that was the problem, Now fixed that issue
