### ISSUE TITLE
Project GUIDs are not unique

### ISSUE THREAD

**Issue by garie** [TorbenK/TK.CustomMap#236]
You must have started with an existing project to make this project because the project GUIDs you've used are not unique. I tried to include your projects in a solution with some other open source projects and they cannot be added at the same time. This makes it difficult to use the development branch for a workaround.

IDs that are not unique:
* 14C534B6-1984-41A9-A384-D3A5508588E3
* AD2D2DB4-E781-4CF1-9B62-3AAD264F196D
* D525F236-6A2D-4010-B1CC-4A4B8581C90B

Some of the projects using the same IDs:
* https://github.com/molinch/Xam.Plugins.ManageSleep
* https://github.com/ufuf/AdvancedTimer
* https://github.com/HoussemDellai/AdMobView-XamarinForms
* https://github.com/HoussemDellai/CrossVideoPlayer
* https://github.com/jamesmontemagno/ImageCirclePlugin
* https://github.com/jamesmontemagno/xamarin.forms-toolkit
* https://github.com/alexrainman/SegmentedControl

**Comment by TorbenK** [comment]
i dont even understand this.
