### ISSUE TITLE
Map doesn't move to its current location sometimes

### ISSUE THREAD

**Issue by snehaljadhavgit** [TorbenK/TK.CustomMap#238]
**I'm using this line of code for getting  current location. But it doesn't work sometimes, so map is unable to redirect to its current location.**  

**var position = await CrossGeolocator.Current.GetPositionAsync(20000);**

 **MyMap.MoveToRegion(MapSpan.FromCenterAndRadius(new Position(position.Latitude, position.Longitude), Distance.FromKilometers(0.5)));**

**Please give me solution as soon as possible.**

**Comment by garie** [comment]
I have noticed the same behavior. I was able to get around this by calling both Move functions. Sometimes one works and sometimes the other works.

```
MyMap.MoveToRegion(span);
MyMap.MoveToMapRegion(span, true);
```

**Comment by snehaljadhavgit** [comment]
Actually the exception occurs when i try to get the current position.
