### ISSUE TITLE
improve the UpdateImage method (code provided)

### ISSUE THREAD

**Issue by MithrilMan** [TorbenK/TK.CustomMap#24]
Hi, i want to contribute improving how you handle the UpdateImage call (at least on Android platform, don't know if IOS already handle ImageSource by stream flawless

anyway, you have on TKCustomMapRenderer.cs in Android platform, two methods

```
private async Task UpdateImage(TKCustomMapPin pin, MarkerOptions markerOptions)
private async Task UpdateImage(TKCustomMapPin pin, Marker marker)
```

there you check to see if the user wants a custom image and load it, this way

```
if (pin.Image != null)
                {
                    Android.Graphics.Bitmap icon = null;

                    if (pin.Image is FileImageSource)
                    {
                        icon = await new FileImageSourceHandler().LoadImageAsync(pin.Image, this.Context);
                    }
                    else
                    {
                        icon = await new ImageLoaderSourceHandler().LoadImageAsync(pin.Image, this.Context);
                    }
                    bitmap = BitmapDescriptorFactory.FromBitmap(icon);
                }
```

the problem is that i need to use a StreamImageSource because i generate runtime a bitmap (with rotation and tilt) and if i just set the Image property of the TKCustomMapPin (you allow it), then i fall into your "else" that try to use an ImageLoaderSourceHandler, that rise an exception

so my solution is easy and works, just add to your TKCustomMapRenderer class this method

```
private static IImageSourceHandler GetHandler(ImageSource source) {
         IImageSourceHandler returnValue = null;
         if (source is UriImageSource) {
            returnValue = new ImageLoaderSourceHandler();
         }
         else if (source is FileImageSource) {
            returnValue = new FileImageSourceHandler();
         }
         else if (source is StreamImageSource) {
            returnValue = new StreamImagesourceHandler();
         }
         return returnValue;
      }
```

and then replace

```
if (pin.Image != null)
                {
                    Android.Graphics.Bitmap icon = null;

                    if (pin.Image is FileImageSource)
                    {
                        icon = await new FileImageSourceHandler().LoadImageAsync(pin.Image, this.Context);
                    }
                    else
                    {
                        icon = await new ImageLoaderSourceHandler().LoadImageAsync(pin.Image, this.Context);
                    }
                    bitmap = BitmapDescriptorFactory.FromBitmap(icon);
                }
```

on both UpdateImage methods, to this

```
if (pin.Image != null) {
               var handler = GetHandler(pin.Image);
               Android.Graphics.Bitmap icon = await handler.LoadImageAsync(pin.Image, this.Context).ConfigureAwait(false);

               bitmap = BitmapDescriptorFactory.FromBitmap(icon);
            }
```

that's more elegant (don't duplicate code) and works even for StreamImageSource

bye

**Comment by TorbenK** [comment]
Hi,

Looks totally fine. Feel free to create a pull request and I will add you as contributer. Thanks!

**Comment by MithrilMan** [comment]
ok when I'll find time i'll fork and do that
there are even some other features i'd like to add, like the icon anchor because in my case it's in the middle of the icon and not in the default marker position

**Comment by TorbenK** [comment]
I added support for `StreamImageSource` and also took your very valid point to remove the redundant code. I added it as extension methods. You can check them out here:

iOS(ToImage): https://github.com/TorbenK/TK.CustomMap/blob/master/TK.CustomMap/TK.CustomMap.iOSUnified/Extensions.cs

Android(ToBitmap):
https://github.com/TorbenK/TK.CustomMap/blob/master/TK.CustomMap/TK.CustomMap.Android/Extensions.cs

I added you as contributer on the readme. Feel free to add any further ideas and/or pull requests.

**Comment by MithrilMan** [comment]
nice, tested and it's working, glad to help in future too
