### ISSUE TITLE
Map not ready with FitMapRegionToPositions

### ISSUE THREAD

**Issue by jeremymelchor** [TorbenK/TK.CustomMap#240]
I'm trying to initiliaze the map with the camera fit on two positions.
According to #103 , we need to call it in OnAppearing otherwise we receive an Object reference not set to an instance of an object.

But i'm getting a Map not ready exception.
Is there a way to be notified when the map is ready so i can update the camera ?

**Comment by TorbenK** [comment]
@patchimou sorry for the late reply. I gues that this i an Android-only problem right?

**Comment by jeremymelchor** [comment]
@TorbenK Yes it was on android indeed, but I don't work on the project anymore, so I can't give you more information
