### ISSUE TITLE
Not shows Zoom and ShowinUser

### ISSUE THREAD

**Issue by angelru** [TorbenK/TK.CustomMap#241]
Hello, I have the next code:

            TKCustomMap mapView = new TKCustomMap
            {
                IsShowingUser = true,
                HasZoomEnabled = true,
                HasScrollEnabled = true,
                IsRegionChangeAnimated = true
            };

`Content = mapView;`

But not shows the zoom and user's current location button

**Comment by vincentcastagna** [comment]
Which Xamarin forms Map version are you using ?

I had the same issue with latest release of xamarin forms map 2.3.4.270 so I came back to 2.3.3.193. 
Perhaps we should wait for an upgrade of TK according to this release ... or its a xamarin forms map prob.
Ive opened a thread on xam forum if you want => https://forums.xamarin.com/discussion/102776/update-xamarin-forms-and-maps-regression#latest

**Comment by angelru** [comment]
Many thanks @Umar3x

**Comment by Umar3x** [comment]
@TorbenK  Still there mate ? Is there any chance for the package to be compatible with XF 2.3.4 ? 

Related to https://github.com/TorbenK/TK.CustomMap/issues/228
