### ISSUE TITLE
custom image orientation (fix included)

### ISSUE THREAD

**Issue by MithrilMan** [TorbenK/TK.CustomMap#242]
I'm generating a on-the-fly image for my pins, that reflect their current orientation on the map, all works fine but when the user rotate the map (now i'm talking about android, not sure what happen on iOS yet)  using the two finger gesture, the orientation on the pin on the screen stay the same and don't adhere to map orientation.

To fix this issue, you can just add 
`markerWithIcon.Flat(true);`

into the AddPin method in TKCustomMapRenderer class (in android project)

I think this should be the default behavior or at least you should add a "Flat" property in the TKCustomMapPin class (e.g. pin.IsFlat)

**Comment by TorbenK** [comment]
thanks
