### ISSUE TITLE
Crash Map

### ISSUE THREAD

**Issue by sktdeepak** [TorbenK/TK.CustomMap#243]
I am testing with Samsung Galaxy Note 3, Android 5.0 , SM-N9005 .

When i open map app crashed (unfortunately stopped working).

i tested with some other device like moto,lenovo and other latest samsung devices works fine

**Comment by vincentcastagna** [comment]
@sktdeepak 

You may have an error to communicate here ? Set your debug settings to show all. Which version of Android are your others devices running on ?

**Comment by sktdeepak** [comment]
in south african region only map was crashing.... checked with samsung and huawei..

**Comment by sktdeepak** [comment]
Sorry , i resolved this issue. issue is not with tk.custommap. Due to region charsh was happened

**Comment by sktdeepak** [comment]
Sorry , i resolved this issue. issue is not with tk.custommap. Due to region crash was happened
