### ISSUE TITLE
FUTURE . Is this package still/will be maintain ? 

### ISSUE THREAD

**Issue by vincentcastagna** [TorbenK/TK.CustomMap#245]
@TorbenK 
@jfversluis 
@JeanCollas 

Hello, 
Is there any plan for this package to be updated ? I got some trouble for last xamarin forms map update ... especially in the customRenderer for OnElementPropertyChanged due to last update 

Method 'Android.Gms.Maps.MapView.get_Map' not found

Plus others issues still open here. 

If not, which I could understand, would it be possible to tell it here as I'm going to do w/o this package.

Regards,

**Comment by JeanCollas** [comment]
Hi @Umar3x 
I have actually migrated to another project, you can find it here: https://github.com/JeanCollas/Xamarin.Forms.GoogleMaps
It is a fork of a fork of the official package.

I am working on updates at the moment, trying to migrate to latest Xamarin.Forms versions. I may update it today or tomorrow (on my own fork). It will probably also be followed with some features updates in the coming weeks. 

This fork includes map bindings and several other features, but probably some are missing as compared to this project if I don't use them.
The original fork is also maintained a bit more often.

**Comment by jfversluis** [comment]
Hi @Umar3x,

Personally, I would like to maintain this package very much. But it seems that there is a lot of consuming going on and not that much giving back to the community. Meaning that people are piling up a lot of issues, but aren't willing to locate and fix the problem theirselves and opening a pull request.

I'm not blaming anyone, it seems to happen a lot in the OSS world, but I hope you understand we are very busy as well. Any contributions are very welcome and together I'm sure we can create an awesome, stable, up-to-date package. But it seems the maintainers now are too busy to invest amounts of time that are requested by the issues at this time.

I am very sorry for that, but that is just the way it is at the moment.

**Comment by TorbenK** [comment]
Sorry for not posting anything past months. I will try to find time for this project again and update it to the latest XF release this month.

**Comment by vincentcastagna** [comment]
@JeanCollas , @jfversluis 
Hello ,

Thank you all for your fast answers. As you said its the OSS world and I did not blame any of you for this :), on the contrary, I use this package for my app as it provides all features I need, and thanks to you that you took your time developping it.
 I'll try to find some time too in parallel of my current project and try to do some PRs for issues I identified.

@TorbenK Nice to read that could be great. Thank you very much for your feedback.

**Comment by vincentcastagna** [comment]
Hello @JeanCollas 

I was just wondering why you migrated to another project as this one is already very complete with a lot of features. I don't say you should work on this one, as you do what you want of course and as far from now I'm not a contributor so my word as no real value (to you I mean and perhaps to other contributors).

And as said @jfversluis  this is the OSS world. But I know/hope that XF community won't turn in a JS like community where awesome packages (like this one) are implemented and then thrown away for another package with new bugs or same ones, same features but done in another way. This is confusing then when times come to choose a package for release production.

But I saw that one star was removed from here, which is a shame, as I think this package in the future of xamarin could be a very useful one, as it is already one, but I mean more and more ppl are using XF so the demand is growing. So why not concentratring on a package instead of spreading lot of others that has not yet been finished and provides less functionalities than this one. TKCustomMap just needs to be maintained with XF releases. 

As I said in my previous post I'm trying to investigate bugs I encouter to see what's wrong and perhaps will do a PR or post here a solution (I never did a PR so I'm kind of noob in this domain). And it will take me some times as I did not contribute to it so I must understand how the package is working inside.

Well anyway, thank you all for the job you done. I don't want to give you the feeling that I whine or I give you lessons, just I feel disappointed because so much work had been done so far.

Regards,

**Comment by TorbenK** [comment]
please check 1.6.0-pre1
