### ISSUE TITLE
[FIX - Workaround] Update to XF 2.4 & PlayServices 42.1021.1

### ISSUE THREAD

**Issue by vincentcastagna** [TorbenK/TK.CustomMap#246]
Hello all,

So I've been investigating for some probs concerning update to XF & XFM 2.4.0.282 and update of all PlayServices to 42.1021.1.

I managed to get everything work by cloning the actual repo and building the dlls by myself, so atm I get ride off nuget. To get it work I updated all packages for the TKCustomMap project (playServices & XF) and built again the dlls. 

For these issues : 
#241 => the is showing user is now working same for zoom/in out  buttons
#207 => now the error that was poping when adding a pin ("an item with the same key has already been added") is fixed  
#210 => Link assemblies on "sdk only" works when in release mode so no need now to skeep assemblies.

@TorbenK, @jfversluis   I guess if you want to update the package there is not so much work to do as it does not concern any part of your code, but more packages to update so I can't really do a PR for that ;) . Hope it will help you to maintain this awesome package.

Thank you for your time. Ihope that will help people that want to update to latest versions.

**Comment by straiser** [comment]
Is there a way to update nuget  soon? It's the only maps for xamarin forms with  implementation of google directions and I can't use it with firebase notification due to PlayServices and XF version. Workaround doesn't work for because I get  errors after adding dlls to project.

**Comment by vincentcastagna** [comment]
@straiser 
What are errors ?

**Comment by straiser** [comment]
A lot of "The "XamlCTask" task could not be initialized with its input parameters" and "ResolveLibraryProjectImports tasks failed unexpectedly"

**Comment by vincentcastagna** [comment]
For the first error I don't really see what it is ... could you provide more informations ? Have you clone the repo, clean the solution, updated all package of the repo (XF 2.4 XFM 2.4 and play services to 42.1021.1 ? Then building the dlls ?
For the second error, it appears most of the time when your project is too deep in your arbo I mean by that path of your project.

**Comment by TorbenK** [comment]
1.6.0-pre1 should work
