### ISSUE TITLE
Getting new position after drag and drop of Pin ?

### ISSUE THREAD

**Issue by swasti29** [TorbenK/TK.CustomMap#249]
how to get new position(longitude and latitude) after drag and drop the Pin

**Comment by TorbenK** [comment]
Use `PinDragEndCommand` or `PinDragEnd` event.

**Comment by vivekshah-zymr** [comment]
@swasti29 @TorbenK 
I am getting new Latitude and Longitude using PinDragEnd, but how can I fetch the address details of new dragged position as it may differ from the previous location. I am using 2.0.0-pre3 and testing on iOS 11.
