### ISSUE TITLE
Image not appearing in Custom Pin (Android)

### ISSUE THREAD

**Issue by sa3eedo12** [TorbenK/TK.CustomMap#250]
I just get an empty space whenever I use an image in a custom pin. I know the pins are being placed correctly because the map can zoom in to their positions. I can also see the default map pin when an image is not placed.

Please help, I've been trying to fix this issue for sometime but it wont work with me.

**Comment by TorbenK** [comment]
Can you share the relevant code? What type of images are you using? What is the build action performed on those images?

**Comment by sa3eedo12** [comment]
I'm using a PNG, I've tried a custom one and I tried the default xamarin icon. 
In the code I'm simply giving it the complete file name  new TKCustomMapPin() { Position = p, ID = s.Name, Title = s.Name, Anchor = new Point(x.First().Latitude, x.First().Longitude), ShowCallout = true, Subtitle = "Test", Image="Icon.png" };

I know that it's getting the image because it's not crashing, however I dont see anything when the app loads.

Thank you so much.

**Comment by TorbenK** [comment]
I hardly doubt that this is an issue with the control itself. Just because it does not crash, it's not said that the image is deployed correctly. 
Check your build action on the image and look at the sample project, there is an example using a custom image.

**Comment by sa3eedo12** [comment]
The build action is Android resource, I can also load the image anywhere else.
Is there a specific version of Xamarin Forms Maps that I'm supposed to be using for it to work?

**Comment by TorbenK** [comment]
The one defined in the nuspec. Again, please check the sample or provide a repro project. I don't know how to help otherwise, sorry.

**Comment by sa3eedo12** [comment]
Sure thing, should I mail it to you?

**Comment by TorbenK** [comment]
go ahead.

**Comment by sa3eedo12** [comment]
It appears that the Anchor was making the image get out of the view, sorry about that.
