### ISSUE TITLE
Android app crashes on map initializing

### ISSUE THREAD

**Issue by dinodzakmic** [TorbenK/TK.CustomMap#251]
Hello,

I've placed TKCustomMap in a new page with StackLayout as a root layout.
I've created new ViewModel and MyPins property in it.
When I try to bind CustomPins List or ObservableCollection with MyPins, app crashes and I get the following error: (please contact for more details, I can send you full stack trace if you want)

System.ArgumentException: An item with the same key has already been added.

10-27 11:15:52.796 W/DynamiteModule(29937): Local module descriptor class for com.google.android.gms.googlecertificates not found.
10-27 11:15:52.797 W/DynamiteModule(29937): Failed to load module via V2: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.dynamite.DynamiteModule$DynamiteLoaderClassLoader" on path: DexPathList[[zip file "/data/app/com.cito-1/base.apk"],nativeLibraryDirectories=[/data/app/com.cito-1/lib/arm, /system/fake-libs, /data/app/com.cito-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
10-27 11:15:52.822 I/DynamiteModule(29937): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:4

EDIT:
This occurs only if I add custom image in my TKCustomMapPin.

**Comment by TorbenK** [comment]
what version do you use?

**Comment by dinodzakmic** [comment]
1.5.1

**Comment by TorbenK** [comment]
Please try 1.6.0-pre6, that should be fixed.

**Comment by dinodzakmic** [comment]
I assume you moved to .NET Standard 2.0 since I can't update all my packages and resolve dependencies. I'll try with some workaround, will let you know if there's any progress. Thanks anyway!

**Comment by TorbenK** [comment]
Switched to .netstandard 1.1, if you use PCL, use Profile 111, which is the XF default when creating a new project. I recommend switching to netstandard though, which is pretty easy.

https://xamarinhelp.com/upgrade-pcl-net-standard-class-library/

**Comment by dinodzakmic** [comment]
Since this Image property on `TKCustomMapPin  `is type of `ImageSource`, could this be used with url images or just with native project resources? Basically, is this compile-time/run-time friendly?

**Comment by TorbenK** [comment]
yes, you can use `UriImageSource or` `StreamImageSource` if you want.
