### ISSUE TITLE
LongPress not working on Android if using EventHandler rather than Command

### ISSUE THREAD

**Issue by nbsoftware** [TorbenK/TK.CustomMap#255]
Hello,

Is it possible something has been modified within this area and having this impact.

Tested in Android 6, 7 & 8.
I'm compiling against the latest SDK (API 27).
Working fine in iOS.

I haven't gone through all the testing yet, specifically grab the latest sources and compile the sample to see how it goes. I will.

Just wanted to quickly ask, if by any chance this points to something in your mind.

**Comment by TorbenK** [comment]
Hello,

I just tried on a device using API 24 and it worked for me. Don't remember changing anything there lately.

**Comment by nbsoftware** [comment]
Alright then, I'll review my environment and make some further tests.
Thanks for this prompt response.

**Comment by nbsoftware** [comment]
Ok now I remember: a long time ago I had to change the source code of the renderer for Android, because I wasn't using the MapLongPressCommand, only a regular event handler:
```
        public void ActivateLongPress()
        {
            MyMap.MapLongPress += MyMap_MapLongPress;
        }
``` 
This was working fine in iOS (and still do) but wasn't on Android.
I had to change the ```TK.CustomMap\TK.CustomMap.Android\TKCustomMapRenderer.cs```

From
```
        private void OnMapLongClick(object sender, GoogleMap.MapLongClickEventArgs e)
        {
            if (this.FormsMap == null || this.FormsMap.MapLongPressCommand == null) return;

            var position = e.Point.ToPosition();
            this.MapFunctions.RaiseMapLongPress(position);
        }
```

to

```
        private void OnMapLongClick(object sender, GoogleMap.MapLongClickEventArgs e)
        {
            if (this.FormsMap == null) return;

            var position = e.Point.ToPosition();
            this.MapFunctions.RaiseMapLongPress(position);
        }
```

Do you think you could integrate such a change so that we are not forced to use the Command pattern?

Thanks

**Comment by TorbenK** [comment]
Since quite some time there are events available for literally everything. 

https://github.com/TorbenK/TK.CustomMap/blob/f0c9d004081df6371b7a8d7925674e3459772bb8/TK.CustomMap/TK.CustomMap/TKCustomMap.cs#L33

**Comment by nbsoftware** [comment]
I know. And that's what I'm using since the beginning.
But on Android, the event isn't raised because of the test:

```this.FormsMap.MapLongPressCommand == null```

i.e. even if the event handler is set, the event is not raised if the command is not set.
That's precisely my point.

Unless of course I'm mistaken and using it in a wrongly manner.
But again, my code works as expected on iOS.
Android doesn't unless I remove this test.

**Comment by vincentcastagna** [comment]
Just a question : 
Why do you need to use handler prior to command ?

**Comment by nbsoftware** [comment]
Because I’m reusing some old design.
I know the Command pattern should now be used in favor of event handlers to decouple things...
But I don’t have time to redesign it just now.
But hey, if event handlers are supported (a good thing !) I suppose they should work consistently, shouldn’t they?

**Comment by vincentcastagna** [comment]
Well yes it is supposed to work consistently. I had some probs two with design and was implementing handlers. I refactored it by using the messaging center in my viewModel (in a command or property) to handle design changes/animation (with a service injected with dependency service called in the subscribe method of messaginCenter). For gesture recognization I'm using MR.Gestures package and it works for me so perhaps you got some prob in your gesture implementation ... ?

**Comment by nbsoftware** [comment]
I don’t think so.
Again the shared code is working fine in iOS and doesn’t in Android unless I remove the test shown earlier in the renderer which seems to me to be a pretty simple fix.

**Comment by nbsoftware** [comment]
And having had a further look, of course it seems the case for several events on the Android renderer where the Command is checked against null before raising the event.
Again, that means that the event won't be raised if only the event handler has been set without setting the corresponding Command.
e.g.
```
private void OnUserLocationChange(object sender, GoogleMap.MyLocationChangeEventArgs e)
        {
            if (e.Location == null || this.FormsMap == null || this.FormsMap.UserLocationChangedCommand == null) return;
   
            var newPosition = new Position(e.Location.Latitude, e.Location.Longitude);
            this.MapFunctions.RaiseUserLocationChanged(newPosition);
        }
```
Moreover, this not consistent with the iOS renderer.
And with iOS, all is working pretty fine.

**Comment by TorbenK** [comment]
@nbsoftware 
You are absolutely right. Those are bugs and need to be fixed, which I just did.

**Comment by nbsoftware** [comment]
Great! Thanks @TorbenK
Do you think you'll publish a 1.6.1 nuget package with just that or should I still build my app from sources waiting for it? Actually I need to release a version of my app today... :/

**Comment by TorbenK** [comment]
I just published it. Should be available any time soon.

**Comment by nbsoftware** [comment]
Awesome!! Thanks
