### ISSUE TITLE
Help required for changing the icon for current location. 

### ISSUE THREAD

**Issue by VisakhRaman** [TorbenK/TK.CustomMap#259]
Hi guys,
I'm trying to use a custom image for the user's current location on the map. But the default pins are what shows for current location. 
On the image attached, I have the blue pin showing me the current location. 
I need to set a custom image instead of the blue pin.

Any help or suggestions are appreciated.
Thanks.
![skype map](https://user-images.githubusercontent.com/29707330/32481939-855231fc-c3bb-11e7-9a03-22cebac34368.jpg)

**Comment by TorbenK** [comment]
Suggestion: 

- Disable `IsShowingUser.`
- Track User-Position. (https://github.com/jamesmontemagno/GeolocatorPlugin)
- Add a Pin with an image at the current user-position.

**Comment by VisakhRaman** [comment]
Thanks man. 
I have applied an image on the location, but the image size remains constant at all zoom levels.
The image should resize itself as and when the user zooms right? 

And `IsShowingUser` doesnt remove the blue dot on the current location. How do I remove the (blue)location dot entirely?

**Comment by TorbenK** [comment]
No, pins never scale with the zoom level. If you want it to scale with the zoom level, you need to define an overlay. Currently images are not supported as overlay though. You can draw a `TKCircle`.

`IsShowingUser = false` should remove the dot. This a a XF.Maps default property. https://developer.xamarin.com/api/property/Xamarin.Forms.Maps.Map.IsShowingUser/

**Comment by VisakhRaman** [comment]
Thanks Torben. This fixed my problem.
