### ISSUE TITLE
Map is not visualize on Android

### ISSUE THREAD

**Issue by acaliaro** [TorbenK/TK.CustomMap#26]
Sorry @TorbenK I think it's a stupid question...but I don't find a solution.
I have created a Google API KEY for Debug and for Release. I have inserted my Key on AndroidManifest (tried with DEBUG and RELEASE), but the app is not show.
Which could be the problem?
Do I write the key also in 

```
        GmsPlace.Init("YOUR API KEY");
        GmsDirection.Init("YOUR API KEY");
```

**Comment by acaliaro** [comment]
I am using your demo on GitHub

**Comment by TorbenK** [comment]
1. Check if the Google Maps API for Android is activated for the specified API key
2. Check if Google Play Services is installed properly on your device

GmsPlace uses the Google Maps Places Browser API, you don't need that to display the map. I always recommend using the NativePlacesApi. Follow instructions on the readme for that.

GmsDirection initializes the Google Maps Directions API which is used for calculating routes. If you don't calculate routes, you don't need to do that.

Neither of this should stop the map from displaying.

**Comment by acaliaro** [comment]
Thanks @torbenk, how can I check point 1?

**Comment by TorbenK** [comment]
In your google developer console.
