### ISSUE TITLE
Reg : Adding Custom Pin Image 

### ISSUE THREAD

**Issue by sakthiaseer** [TorbenK/TK.CustomMap#260]
Hi Team,

I added custom pin image and getting following error in out put window. Here is the error details.

11-12 14:53:44.133 W/View    ( 5147): requestLayout() improperly called by md5497d5d63940cc55d309adb7f5044b052.AnimationNavigationRenderer{ee9c98e V.E...C.. ......ID 0,48-768,1184 #3} during second layout pass: posting in next frame
An unhandled exception occured.

11-12 14:53:45.166 W/DynamiteModule( 5147): Local module descriptor class for com.google.android.gms.googlecertificates not found.
11-12 14:53:45.166 W/DynamiteModule( 5147): Failed to load module via V2: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.dynamite.DynamiteModule$DynamiteLoaderClassLoader" on path: DexPathList[[zip file "/data/app/com.AROMTKMAP-1/base.apk"],nativeLibraryDirectories=[/data/app/com.AROMTKMAP-1/lib/x86, /data/app/com.AROMTKMAP-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
11-12 14:53:45.167 I/DynamiteModule( 5147): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:2
11-12 14:53:45.167 I/DynamiteModule( 5147): Selected remote version of com.google.android.gms.googlecertificates, version >= 2

Can you please help me with this?

Thanks,
Sakthi

**Comment by TorbenK** [comment]
please make sure your Android SDKs are up-to-date.

**Comment by javco** [comment]
No solution? Exact same problem here... google play services 8.1.0
