### ISSUE TITLE
Good API but I could not find Search for Address in the Sample code

### ISSUE THREAD

**Issue by JoseClua** [TorbenK/TK.CustomMap#262]
In the video there is this Search for address functionality but the Sample code does not have it. It has just Add to route, but I am struggling to create a Search.

Do you have a Search example that you could share?

Thanks

**Comment by vincentcastagna** [comment]
Hey,

You should find what you want there. 

https://github.com/TorbenK/TK.CustomMap/blob/Development/Sample/TK.CustomMap.Sample/TK.CustomMap.Sample/PlacesAutoComplete.cs

https://github.com/TorbenK/TK.CustomMap/blob/Development/Sample/TK.CustomMap.Sample/TK.CustomMap.Sample/ViewModels/AddRouteViewModel.cs

**Comment by JoseClua** [comment]
Yeah but the video shows a search entry in the main page (SamplePage) so I am trying to implement that based in AddRoute. I am struggling a bit. Or maybe I am just too lazy. Anyway I am having fun with it now. Thanks

**Comment by TorbenK** [comment]
The search bar or autocomplete is not part of the library. It's just an example of how it can be implemented using Xamarin.Forms ans the places api.
