### ISSUE TITLE
Map opens thousands of miles off.

### ISSUE THREAD

**Issue by BillyMartin1964** [TorbenK/TK.CustomMap#263]
When I open the map page in my Xamarin Forms app, the map will animate and take off to somewhere off the coast of Africa. I can hit the Google reset button on the map to bring it back, but I really don't want my users to have to do that.

It didn't happen when I was using a Custom Map renderer instead of TK CustomMaps, so I know it's not the code. Any ideas out there?

**Comment by TorbenK** [comment]
There is no reason why the control should do this by itself. Please check how you initiate the map and if you set/bind `MapRegion` or `MapCenter`.

You can also check out the sample project.

**Comment by BillyMartin1964** [comment]
Here his my code. Can you see anything?


using Xamarin.Forms;
using Xamarin.Forms.Xaml;
using Xamarin.Forms.Maps;
using System;
using HunterTracker.Helpers;
using HunterTracker.Models;
using HunterTracker.ViewModels;
using System.Collections.ObjectModel;
using TK.CustomMap;


namespace HunterTracker.Pages
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class HuntingAreaPicker : ContentPage
    {
        //double TempLatitude, TempLongitude;
        Distance radius;

        public TKCustomMapPin initPin;
        private ObservableCollection<TKCustomMapPin> _pins = new ObservableCollection<TKCustomMapPin>();
        public HuntingAreaPicker()
        {
            InitializeComponent();

            App.MapAdd = true;

            BindingContext = new LocationsViewModel();
            App.NewLatitude = 0;
            App.NewLongitude = 0;

            var mappedPosition = LocationsViewModel.GetRecentLocation(App.HTAccurracy);
            radius = new Distance(5000);

            if (mappedPosition.Latitude < 0 || mappedPosition.Longitude < 0)
            {
                mappedPosition = new Position(40,-86);
                radius = new Distance(500000);
            }

            var position = mappedPosition;

            //HuntingAreasMap.HeightRequest = App.ScreenHeight;
            //HuntingAreasMap.WidthRequest = App.ScreenWidth;
            HuntingAreasMap.SetBinding(TKCustomMap.CustomPinsProperty, "Pins");
            HuntingAreasMap.SetBinding(TKCustomMap.MapClickedCommandProperty, "MapClickedCommand");
            HuntingAreasMap.SetBinding(TKCustomMap.MapLongPressCommandProperty, "MapLongPressCommand");
            HuntingAreasMap.SetBinding(TKCustomMap.MapCenterProperty, "MapCenter");
            HuntingAreasMap.SetBinding(TKCustomMap.PinSelectedCommandProperty, "PinSelectedCommand");
            HuntingAreasMap.SetBinding(TKCustomMap.SelectedPinProperty, "SelectedPin");
            //HuntingAreasMap.SetBinding(TKCustomMap.RoutesProperty, "Routes");
            HuntingAreasMap.SetBinding(TKCustomMap.PinDragEndCommandProperty, "DragEndCommand");
            //HuntingAreasMap.SetBinding(TKCustomMap.CirclesProperty, "Circles");
            //HuntingAreasMap.SetBinding(TKCustomMap.CalloutClickedCommandProperty, "CalloutClickedCommand");
            //HuntingAreasMap.SetBinding(TKCustomMap.PolylinesProperty, "Lines");
            //HuntingAreasMap.SetBinding(TKCustomMap.PolygonsProperty, "Polygons");
            HuntingAreasMap.SetBinding(TKCustomMap.MapRegionProperty, "MapRegion");
            //HuntingAreasMap.SetBinding(TKCustomMap.RouteClickedCommandProperty, "RouteClickedCommand");
            //HuntingAreasMap.SetBinding(TKCustomMap.RouteCalculationFinishedCommandProperty, "RouteCalculationFinishedCommand");
            //HuntingAreasMap.SetBinding(TKCustomMap.TilesUrlOptionsProperty, "TilesUrlOptions");
            HuntingAreasMap.SetBinding(TKCustomMap.MapFunctionsProperty, "MapFunctions");

       

            HuntingAreasMap.IsRegionChangeAnimated = false;
            HuntingAreasMap.PinDragEnd += pinDragEnd;
            HuntingAreasMap.MapLongPress += mapLongPress;
            HuntingAreasMap.MapType = Xamarin.Forms.Maps.MapType.Hybrid;
            HuntingAreasMap.CustomPins = _pins;
            HuntingAreasMap.AnchorX = .05;
            HuntingAreasMap.AnchorY = .05;


            HuntingAreasMap.MoveToRegion(MapSpan.FromCenterAndRadius(mappedPosition, radius));

        }
        private void pinDragEnd(object sender, TKGenericEventArgs<TKCustomMapPin> e)
        {
            var tempPosition = e.Value.Position;
            App.NewLatitude = tempPosition.Latitude;
            App.NewLongitude = tempPosition.Longitude;            
        }
        private void mapLongPress(object sender, TKGenericEventArgs<Position> e)
        {
            if (App.MapAdd)
            {
                var tempPosition = e.Value;
                App.NewLatitude = tempPosition.Latitude;
                App.NewLongitude = tempPosition.Longitude;


                initPin = new TKCustomMapPin()
                {
                    IsDraggable = true,
                    Position = new Position(App.NewLatitude, App.NewLongitude),
                    IsVisible = true,
                    Image = "scentindicator4.png"                   
                };

               // this._pins.Remove(initPin);
                //await Task.Delay(1000);
                _pins.Add(initPin);
            }

            App.MapAdd = false;
        }

        public async void SaveLocationClicked(object sender, EventArgs e)
        {
            string SavedLocationName = LocationNameEntryBox.Text;

            if (App.NewLatitude == 0 || App.NewLongitude == 0)
            {
                await DisplayAlert("No Location Chosen", "Please press and hold the map at the desired location until the scent indicator appears", "Okay");
                return;
            }

            if (string.IsNullOrWhiteSpace(SavedLocationName))
            {
                await DisplayAlert("No Name Submitted", "You must submit a name for the saved location", "Okay");
                return;
            }


            HuntingLocation location = new HuntingLocation()
            {
                LocationName = SavedLocationName,
                CurrentLatitude = App.NewLatitude,
                CurrentLongitude = App.NewLongitude
            };

            SQLite.SQLiteConnection conn = new SQLite.SQLiteConnection(App.DbPath);

            conn.CreateTable<HuntingLocation>();
            var NumberofRows = conn.Insert(location);

            conn.Dispose();

            if (NumberofRows < 1)
            {
                await DisplayAlert("Error",
                    LocationNameEntryBox.Text + " at GPS Coordinates: " + App.NewLatitude + ", " + App.NewLongitude +
                    " was not saved", "Okay");
                //HuntingAreasMap.MapType = MapType.Hybrid;

            }
            else
            {
                await DisplayAlert("Location Saved",
                    LocationNameEntryBox.Text + " at GPS Coordinates: " + App.NewLatitude + ", " + App.NewLongitude +
                    " has been saved", "Okay");
                await Navigation.PopAsync();
            }
        }

        void ChooseMapType(object sender, EventArgs e)
        {
            var b = sender as Button;
            switch (b.Text)
            {
                case "Street View":
                    HuntingAreasMap.MapType = Xamarin.Forms.Maps.MapType.Hybrid;
                    MapType.Text = "Hybrid View";
                    break;
                case "Hybrid View":
                    HuntingAreasMap.MapType = Xamarin.Forms.Maps.MapType.Satellite;
                    MapType.Text = "Satellite View";
                    break;
                case "Satellite View":
                    HuntingAreasMap.MapType = Xamarin.Forms.Maps.MapType.Street;
                    MapType.Text = "Street View";
                    break;
            }
        }
    }
}
