### ISSUE TITLE
Clear method does not work in real device when a pin was dragged

### ISSUE THREAD

**Issue by JoseClua** [TorbenK/TK.CustomMap#264]
This issue happens just in a real device. In my case I am using iphone 5 with IOS 10.3.

This is my scenario:

In my app the user can only have one pin at a time.

So when he tries to add a second pin, instead of displaying Add Pin, it says Move Pin.

When he taps in Move Pin I do the following:

    this._pins.Clear();

    var pin = new TKCustomMapPin
    {
        Position = position,
        Title = string.Format("Pin {0}, {1}", position.Latitude,
        position.Longitude),
        ShowCallout = true,
        IsDraggable = true
    };
    this._pins.Add(pin);

This works fine in the emulators. But in the real device, only when the user had previously dragged the pin, it doesn't get cleared. So when he Moves the pin, he can still see the previous one, he can see two pins! After that the app crashes trying to do anything.

It seems like a bug in the Clear method that doesn't work when the pin got dragged before.

Please let me know if there is a work around for this issue, ok?

Besides that the API is working great and the business users are loving it.

Thanks

**Comment by TorbenK** [comment]
this is an old bug and should be fixed some tme ago, really wondering here which version you are using

**Comment by JoseClua** [comment]
I am using 1.5.1

**Comment by TorbenK** [comment]
I think it was fixed in 1.5.2-pre1 and is the same as #177 and #185.

**Comment by JoseClua** [comment]
Great! I upgraded to 1.6.1 and the bug is gone.

Thanks for your brilliant work!
