### ISSUE TITLE
System.InvalidOperationException: Map not ready on Android - V1.6.1

### ISSUE THREAD

**Issue by nbsoftware** [TorbenK/TK.CustomMap#265]
Hello,

This morning I've received a new crash log from a user - cf image below.

Any clue of what is going on?
Is there any way to wait for a Map to be ready if it is not yet?
First time I've got that exception.

Thanks

<img width="983" alt="screen shot 2017-11-17 at 11 42 41" src="https://user-images.githubusercontent.com/1502008/32943696-40bad92a-cb8d-11e7-82f0-1adc4f1d40a0.png">

**Comment by TorbenK** [comment]
unfortunately not yet

**Comment by nbsoftware** [comment]
Do you, even roughly, know what should be done and how to handle this?
I might have a look and issue a PR if I find some time to do so.

**Comment by nbsoftware** [comment]
Hmmm, I've googled a bit... doesn't seem too obvious at least in the way it should be exposed to the user. Not even sure that it should.

So for now I guess an ugly workaround would be to catch the exception in the user code (i.e. app's code) and then sleep & retry if the exception has been thrown... would it be good enough?

**Comment by nbsoftware** [comment]
Looking further into the Android Renderer, I can see that often at the beginning of many methods you simply return if `_googleMap` is `null`:

`if (this._googleMap == null) return;`

But for `FitMapRegionToPositions`, you are throwing an Exception:

`if (this._googleMap == null) throw new InvalidOperationException("Map not ready");`

Any reason why there is this difference?

Wouldn't it be better (well at least less worse) to silently return rather than throwing an exception to the user's face?

**Comment by TorbenK** [comment]
Questionable I think, as the method just wouldn't do anything, which probably is more confusing. At least if you are a developer.

May I aks where you call the function? I think if you call it in "OnAppearing" the map should be ready. We probably need an event though.

**Comment by nbsoftware** [comment]
I might agree with you but then it should be consistent. In `MoveToMapRegion` for instance, it just returns. And overall I'd prefer it is confusing for the developer rather than for the end user.

Yes, in OnAppearing and in another method which is called way after all things have initialized.

**Comment by TorbenK** [comment]
There is a MapReady event in 2.0.0-pre1

**Comment by nbsoftware** [comment]
Nice!
