### ISSUE TITLE
Map still opens thousands of miles off

### ISSUE THREAD

**Issue by BillyMartin1964** [TorbenK/TK.CustomMap#267]
I've tried everything from multi-level conditionals to hard coding the coordinates and the map still takes off for the west coast of Africa. It doesn't happen the first time I use the map, but when I go out of it to another page or two and then return.  I'm using a Master Detail Page, if thatsomehow makes a difference. It shouldn't be, but could this be a memory leak?

I put a "Center on Location" button on the page that takes it back to where it's supposed to be, so I know that the code is right. Tapping the button takes it right back to where it should have been in the first place.

It only happens in iOS. The Android version is launched and works great, but I'm ready to launch the iOS version and can't with these runaway maps.

Please don't shrug this off and close this issue without investigating it first. If you'd like my complete Solution, I'd be happy to send it to you, but please don't share it.

Thanks.

**Comment by BillyMartin1964** [comment]
Did more testing. In iOS, basically I can use a custom map once. I have 3 custom map pages, but no matter which one I use, the minute I leave that map and try to go into any of them, it just starts scrolling down and to the right from the United States all the way to the west coast of Africa.

If I shut down the app and use it again, I get one good map and then it's the same. I can use the the centering button I created to take it back to where it should be, so I'm sure it's nothing to do with the HuntingAreas.MoveToRegion(MapSpan.FromCenterAndRadius(mappedPosition, radius)).

I'm wondering if it has anything to do with the Master Detail Page and the map never getting flushed out of memory. Does anyone know how I can flush the map from memory.

**Comment by BillyMartin1964** [comment]
By rigging the maps, I was able to use the on property changed event of the map wandering to Africa as a catalyst to reset the map position. At first it looked hokey, but then I turned off animation and it's not noticeable at all. I hate this cheesy programming, but until a solution is found, it will have to do.

**Comment by TorbenK** [comment]
Hi Billy,

feel free to send me your solution or any reproduction case. I will look at it, but it will probably take some time. Happy that you found a workaround so far.

**Comment by BillyMartin1964** [comment]
Boy, do I have a problem. I solved the runaway map problem and launched. Now I realize that my on property changed hack makes it impossible for anyone to move the map without it self centering immediately. Where is a safe place I can send you the link to my solution?

**Comment by TorbenK** [comment]
You can give 2.0.0-pre1 a try.

**Comment by czuvich** [comment]
You need to construct the map with a MapSpan.

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Maps/Map.cs

**Comment by BillyMartin1964** [comment]
Does 2.0.0-pre1 seem to work any better?
