### ISSUE TITLE
iOS NullReferenceExceptionObject in UpdateRoutes (1.3.3 nuget)

### ISSUE THREAD

**Issue by CliffCawley** [TorbenK/TK.CustomMap#27]
It's intermittent so perhaps a race condition.

Callstack is:

`TK.CustomMap.iOSUnified.TKCustomMapRenderer.UpdateRoutes( Parameters) in 
TK.CustomMap.iOSUnified.TKCustomMapRenderer.OnMapPropertyChanged( Parameters) in 
Xamarin.Forms.BindableObject.OnPropertyChanged( Parameters) in 
TK.CustomMap.TKCustomMap.OnPropertyChanged( Parameters) in 
Xamarin.Forms.BindableObject.SetValueActual( Parameters) in 
Xamarin.Forms.BindableObject.SetValueCore( Parameters) in 
Xamarin.Forms.BindableObject.SetValue( Parameters) in 
Xamarin.Forms.BindableObject.SetValue( Parameters) in 
TK.CustomMap.TKCustomMap.set_Routes( Parameters) in ViewTimelineAndNavigationModel.AnonymousMethod__6() in ViewTimelineAndNavigationModel.cs:200`

Occurred when I was assigning a new list to the Routes property (the new Route list was empty):
`_mapView.Routes = Route;`

Again, I can't reproduce it every time, it just happens randomly which is why I suspect a threading issue.

**Comment by TorbenK** [comment]
Does this only happen on iOS? Was there a list of routes assigned before? Are you setting an ObservableCollection?

**Comment by CliffCawley** [comment]
I've only been able to test on iOS because I'm yet to get route finding working on Android. I always get RouteCalculationFailedCommand on android even though I'm sure I've checked the api key and play services. Is there a way to get more details error information from that event?

I initially assigned it an empty list (I was just using List<> instead of ObservableCollection) and then after retrieving route data from an external service, I built a new list and assigned that to the Route.

I just double checked and it looks like I'm doing the assignment once initially, then looks like I'm doing it again each time an individual leg of the route calculation completes (Not sure why I left that in, the map updates after each calculation, maybe was left over from trying to get it to work initially). It's the same List ref that's being assigned. If you're using a thread to retrieve the results and you get another request while still retrieving, that might be a problem.

I'll fix the multiple assignment in my code and see if it goes away, however if that's what's causing it you might see this issue again from other users.

_edited for clarity_

**Comment by CliffCawley** [comment]
Is there a way to know when all route calculation is done? I could count the number of RouteCalculationFinishedCommand and RouteCalculationFailedCommand events until I've received them all, but a final event would be nice so that I can do something with the mapview when it's 100% complete. (For example to hide a loading indicator after it's finished all route calculation)

**Comment by TorbenK** [comment]
I agree on both points. 

It should not crash, even though you probably don't need reset the route list every time. If you reset the whole list, the calculation will always be done completely for all routes again. I recommend using an observable collection and simply add/remove or clear the collection which will also update the map. Anyway, you are right that it should not crash.

I will add your suggestion for a complete route calculation finish command and more detailed error information for future enhancement.

**Comment by CliffCawley** [comment]
Just to add to this, I've removed the multiple assignments and am using an ObservableCollection and just using .Clear() and .Add() as you suggested, however I'm still randomly getting the NullReference exception. Here's the latest callstack:

`at TK.CustomMap.iOSUnified.TKCustomMapRenderer.UpdateRoutes (Boolean firstUpdate) [0x0008f] in <filename unknown>:0 
  at TK.CustomMap.iOSUnified.TKCustomMapRenderer.OnRouteCollectionChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x0012c] in <filename unknown>:0 
  at System.Collections.ObjectModel.ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x00012] in /Users/builder/data/lanes/2689/962a0506/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/System/compmod/system/collections/objectmodel/observablecollection.cs:286 
  at System.Collections.ObjectModel.ObservableCollection`1[T].OnCollectionReset () [0x00000] in /Users/builder/data/lanes/2689/962a0506/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/System/compmod/system/collections/objectmodel/observablecollection.cs:373 
  at System.Collections.ObjectModel.ObservableCollection`1[T].ClearItems () [0x00022] in /Users/builder/data/lanes/2689/962a0506/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/System/compmod/system/collections/objectmodel/observablecollection.cs:187 
  at System.Collections.ObjectModel.Collection`1[T].Clear () [0x00017] in /Users/builder/data/lanes/2689/962a0506/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/collections/objectmodel/collection.cs:87 
  atViewTimelineAndNavigationModel.GenerateTimelineModelData () [0x00013] in /ViewTimelineAndNavigationModel.cs:68 
  atReloadJobs () [0x00007] in /TabHomeToday.xaml.cs:48 
  atTabHomeToday.OnDataEvent (MessageDataEvent message) [0x0001a] in /TabHomeToday.xaml.cs:80`

**Comment by TorbenK** [comment]
Thanks for reporting this. Can you give me more insights of what exactly you are doing? Is it possible that you are nulling a TKRoute instance before calling Clear?

**Comment by CliffCawley** [comment]
I'll create a test project that reproduces it for you, hopefully I'll get some time over the next day or so.

**Comment by TorbenK** [comment]
That would be great, thanks Cliff.

**Comment by CliffCawley** [comment]
So I'm having some difficulty reproducing the same crash in a test project. I did find another crash for you though! :+1: 

I decided to add the full source to the first project and have reproduced it with full call stacks and line number info so I could create a patch for you and submit it. Basically Map and FormsMap are both null in the UpdateRoutes code.

I saw you do checks for them in other functions, perhaps it's just missing from here. I'd like to spend more time and figure out exactly what's going on, but I just can't find the time, sorry!

I'll just fix the code here and make sure it's all working then submit the fixes so you can check it out.

**Comment by TorbenK** [comment]
Should be fixed in 1.4.0
