### ISSUE TITLE
.Net Standard 2.0 - Nuget dependency

### ISSUE THREAD

**Issue by Binjaaa** [TorbenK/TK.CustomMap#274]
Hey,

Basically, it is just a question, not a bug. I can see that the library has been updated to .net standard 2.0 since version 1.6.1. :champagne: 
(https://github.com/TorbenK/TK.CustomMap/commit/0e3e1fd67c34a2278eb849efdadb188f341d1305)

Should I see the standard library 2.0 dependency in the dependency list on [TK.CustomMap nuget](https://www.nuget.org/packages/TK.CustomMap/1.6.1)?

Thank you.

**Comment by TorbenK** [comment]
Hey,

I actually reverted that back to netstandard 1.1 because of compatibility reasons with older PCL profiles.

**Comment by Binjaaa** [comment]
Cool stuff!

My intention was with the question to know that whether dependency list should contain the dependency for netstandard 1.1 or not. Actually, it doesn't have any info about the netstandard support/compatibility. 

It might be a TK.CustomMap or Nuget.org issue?

**Comment by TorbenK** [comment]
Yes, I think you are right, there should be a dependency on .netstandard nuget package. Thanks!
