### ISSUE TITLE
Dependency on Microsoft.Net.HTTP

### ISSUE THREAD

**Issue by ahmad-crossplatform** [TorbenK/TK.CustomMap#275]
Hello there , 
I have Project that is .netStandard 2.0 . and when installing the nuget package , i get the complain about the dependency on Microsoft.Net.HTTP as it does not support netStandard. 
So can you please remove it? as there is already System.Net.Http library that is supported out of the box.

**Comment by TorbenK** [comment]
Hello,

yes, the next pre-release has updated dependencies.

**Comment by ahmad-crossplatform** [comment]
Cool!! 
Any ETA ?

**Comment by TorbenK** [comment]
Should be available any time soon. I just published.
