### ISSUE TITLE
Link Assemblies Error with TK.CustomMap.Droid

### ISSUE THREAD

**Issue by BillyMartin1964** [TorbenK/TK.CustomMap#277]
Does anyone know how to solve this?

The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'System.Void TK.CustomMap.Droid.TKCustomMapRenderer::OnCameraChange(System.Object,Android.Gms.Maps.GoogleMap/CameraChangeEventArgs)' in assembly: 'TK.CustomMap.Android.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Xamarin.Forms.Maps.Android.MapRenderer::OnCameraChange(Android.Gms.Maps.Model.CameraPosition)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	HunterTracker.Android	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1629

**Comment by TorbenK** [comment]
Please try 2.0.0-pre3

**Comment by BillyMartin1964** [comment]
I tried to use 2.0.o-pre3 but it lit up like a Christmas tree.

I changed Custom pins property to pins property and that error went away, but then it couldn't decide if all of my variables should be of type Xamarin maps or TK maps. I made them all TK maps, but then it said TK maps didn't contain Long Press or Move to Region. I was stuck at that point.

Do you have a changes list and instructions for the upgrade?

**Comment by BillyMartin1964** [comment]
This is the code I'm talking about:

Title = huntingarea.LocationName;
            mappedPosition = new Position(huntingarea.CurrentLatitude, huntingarea.CurrentLongitude);
            radius = new Distance(100);

            //HuntingAreas.HeightRequest = App.ScreenHeight;
            //HuntingAreas.WidthRequest = App.ScreenWidth;
            HuntingAreas.SetBinding(TKCustomMap.CustomPinsProperty, "Pins");
            //  HuntingAreas.SetBinding(TKCustomMap.MapClickedCommandProperty, "MapClickedCommand");
            HuntingAreas.SetBinding(TKCustomMap.MapLongPressCommandProperty, "MapLongPressCommand");
            HuntingAreas.SetBinding(TKCustomMap.MapCenterProperty, "MapCenter");
            HuntingAreas.SetBinding(TKCustomMap.PinSelectedCommandProperty, "PinSelectedCommand");
            HuntingAreas.SetBinding(TKCustomMap.SelectedPinProperty, "SelectedPin");
            // HuntingAreas.SetBinding(TKCustomMap.RoutesProperty, "Routes");
            HuntingAreas.SetBinding(TKCustomMap.PinDragEndCommandProperty, "DragEndCommand");
            //   HuntingAreas.SetBinding(TKCustomMap.CirclesProperty, "Circles");
            //   HuntingAreas.SetBinding(TKCustomMap.CalloutClickedCommandProperty, "CalloutClickedCommand");
            //  HuntingAreas.SetBinding(TKCustomMap.PolylinesProperty, "Lines");
            //   HuntingAreas.SetBinding(TKCustomMap.PolygonsProperty, "Polygons");
            HuntingAreas.SetBinding(TKCustomMap.MapRegionProperty, "MapRegion");
            //  HuntingAreas.SetBinding(TKCustomMap.RouteClickedCommandProperty, "RouteClickedCommand");
            //   HuntingAreas.SetBinding(TKCustomMap.RouteCalculationFinishedCommandProperty, "RouteCalculationFinishedCommand");
            //   HuntingAreas.SetBinding(TKCustomMap.TilesUrlOptionsProperty, "TilesUrlOptions");
            // HuntingAreas.SetBinding(TKCustomMap.MapFunctionsProperty, "MapFunctions");
            HuntingAreas.SetBinding(TKCustomMap.RotationProperty, "Rotation");

            HuntingAreas.PropertyChanged += FindLocationPin;
            HuntingAreas.IsRegionChangeAnimated = false;
            HuntingAreas.PinDragEnd += pinDragEnd;
            HuntingAreas.MapType = MapType.Hybrid;
            HuntingAreas.CustomPins = _pins;
            HuntingAreas.PinsReady += Slider;

            HuntingAreas.MoveToRegion(MapSpan.FromCenterAndRadius(mappedPosition, radius));

**Comment by TorbenK** [comment]
Like you see in the nuget dependencies, there is no need for XF.Maps anymore. In fact, you should remove it. Major changes I made are listet in the nuget release as well.

**Comment by BillyMartin1964** [comment]
So 
            HuntingAreas.MoveToRegion(MapSpan.FromCenterAndRadius(mappedPosition, radius));

is replaced with what?
