### ISSUE TITLE
Bindings broken Xamarin Forms

### ISSUE THREAD

**Issue by HamishBrowne** [TorbenK/TK.CustomMap#278]
SetBinding is failing with:

Argument 1: cannot convert from 'Xamarin.Forms.BindablePropertyKey' to 'Xamarin.Forms.BindableProperty'	MapTest.Android	C:\Projects\MapTest\MapTest\MapTest\MainPage.xaml.cs	

Argument 2: cannot convert from 'string' to 'Xamarin.Forms.BindingBase'	MapTest.Android	C:\Projects\MapTest\MapTest\MapTest\MainPage.xaml.cs

Xamarin.Forms & Xamarin.Forms.Maps (v2.5.0.121934)
TK.CustomMap (v2.0.0-pre2)

public partial class MainPage : ContentPage
	{
		public MainPage()
		{
			InitializeComponent();

            var theMap = new TKCustomMap();
            theMap.SetBinding(TKCustomMap.MapCenterProperty, "MapCenter");
        }

Cheers

**Comment by TorbenK** [comment]
Bindings are not broken. `MapCenter` was made read-only as stated in the release notes.

Anyway, `MapCenterProperty` should not be public. This will be changedin the stable release.

**Comment by HamishBrowne** [comment]
Cheers, I'd better read the release notes!

**Comment by sinclas** [comment]
What is the best method to observe when the map is moved by the user?  UserLocationChanged?  I was binding to the MapCenterProperty prior.
Thanks!
