### ISSUE TITLE
Offline Maps?

### ISSUE THREAD

**Issue by BillyMartin1964** [TorbenK/TK.CustomMap#280]
Is it possible to store offline maps?

Someone on the web suggested OsmSharp, but I don't know much about it.
https://github.com/OsmSharp

Someone else said that neither Google nor Apple allow offline map storage. Is anyone familiar with this issue?

**Comment by ghost** [comment]
I'm interested in this too.

**Comment by TorbenK** [comment]
That is not possible and requires ALOT of work.

**Comment by BillyMartin1964** [comment]
Well, I navigated my various map pages, zooming in and out while online. Then I went offline and the maps were still there. I even shut off the phone, waited a few, and turned it back on. They were still there, which makes me think they're in some persistent cache somewhere.

I wonder how long the maps will stay on the device. This was an Android. Haven't tried iPhone yet.
