### ISSUE TITLE
Click on callout crashes iOS app with NullReferenceException in new 2.0.0-pre3

### ISSUE THREAD

**Issue by nbsoftware** [TorbenK/TK.CustomMap#286]
I tested my app with the new 2.0.0-pre3.
iOS crashes when I click on the callout.
Android works fine though.
I slightly modified the sample provided in the source to reproduce the issue and indeed it crashes in  `GetPinByAnnotation`

<img width="833" alt="screen shot 2017-12-11 at 17 23 26" src="https://user-images.githubusercontent.com/1502008/33843048-8f254c36-de9c-11e7-9a3c-4a5e0863758e.png">

In my case the cast as `CKCluster` in `var customAnnotation = annotation as CKCluster;` results in a null value. I had to cast it as simple `TKCustomMapAnnotation` to make it work.

Below, the code quickly modified to make it work:

```C#
        protected TKCustomMapPin GetPinByAnnotation(IMKAnnotation annotation)
        {
            var customCKAnnotation = annotation as CKCluster;
            if (customCKAnnotation?.Annotations.Count() > 1)
            {
                return FormsMap.GetClusteredPin?.Invoke(null, customCKAnnotation.Annotations.OfType<TKCustomMapAnnotation>().Select(i => i.CustomPin));
            }

            var customAnnotation = annotation as TKCustomMapAnnotation;
            return customAnnotation?.CustomPin;
        }
```

By the way, I did not test with clustering, but shouldn't it be `>0` rather than `>1`?

Thanks

**Comment by GrumpyMan** [comment]
I just noted the same problem.

**Comment by nbsoftware** [comment]
Hello,
May I ask when do you think you'll be able to work on this issue?

**Comment by TorbenK** [comment]
Hello,
I'm currently(again) too busy. Maybe during vacation, but don't quote me on this. I really want to get 2.5 stable asap.

**Comment by nbsoftware** [comment]
Hi Torben,
Any update?
Thanks

**Comment by vivekshah-zymr** [comment]
I am also facing the same issue with 2.0.0-pre3 on iOS 11. It crashes randomly on a touch of a pin. Did any of you find any solution regarding this?

**Comment by nbsoftware** [comment]
Well the solution / fix is at the beginning of this thread.
You'd need to fork the repository, fix the code, remove all references to the binary package, and then include all the necessary source project references.
Tedious, I know, but there is no other option until the author includes the fix himself and releases a package.
Any update on that Torben?

**Comment by TorbenK** [comment]
fix included in 2.0

**Comment by tuyen-vuduc** [comment]
It isn't fixed. I will create a PR.

**Comment by joeygraves222** [comment]
This still isn't fixed. I'm using version 2.0.1 and I'm still getting the same exception. It works great on android though.
