### ISSUE TITLE
Maps does not work on iOS 

### ISSUE THREAD

**Issue by acaliaro** [TorbenK/TK.CustomMap#29]
I have an iPhone 6.
If I connect the iPhone to my MAC and debug your demo app, it works (I can search an address, do long tapping...) but if I create an IPA and install the IPA, it does not work (no search, no long tap), only the map is visualized...
Where is the problem?
Thanks

**Comment by TorbenK** [comment]
That sounds like a linker issue, but it's really hard to tell where the problem is based on this little information.

**Comment by acaliaro** [comment]
What can I do to help you?

**Comment by TorbenK** [comment]
So you took the sample app and created an IPA? Did you use a distribution profile and used Testflight or what exactly did you do? What is your linker setting? Can you start the simulation functionality of the sample?

**Comment by acaliaro** [comment]
Yes I use your demo
Yes I use a distribution profile ad hoc
Linker settings... I have touched nothing
Simulation is the button on upper right corner? No it does not work. Appears only the question Do you want start test

**Comment by TorbenK** [comment]
Oh, wait, the simulation is currently only available in the development branch.

I can't really tell why this is not working for you, I have an app in the store using it without any problems. If the linker removes any neccessary dependencies I would also expect a crash too, but that's not the case right?

**Comment by acaliaro** [comment]
No crash, only the map visualize Rome... In debug it visualize New York...

**Comment by acaliaro** [comment]
If you create an ipa with your demo source, dote IT world in a iPhone 6 with ios9?

**Comment by TorbenK** [comment]
I don't know, I never tried it. But yes, I would expect it to work. I currently can't test it, I am at a customers desk without any mac or build server available.

You can try to switch of linking completely and deploy again.

**Comment by acaliaro** [comment]
If you have time, this is the IPA

https://www.dropbox.com/s/7mg0fntglp48ion/TK.CustomMap.ipa?dl=0

this is my linker situation

https://www.dropbox.com/s/m1jw61q0cw57zop/Screenshot%202016-02-22%2016.59.27.png?dl=0

**Comment by TorbenK** [comment]
Thank you for providing this. I will look at it as soon as I find some time, which is, unfortunately, not that easy at the moment.

**Comment by acaliaro** [comment]
Thanks. One OOT. Does this plugin support windows phone?

**Comment by TorbenK** [comment]
No, sorry.

**Comment by fransjan** [comment]
Hi,

I just got my shipped app approved by Apple and have the same problem as mentioned above.
No error messages/exception, map is displayed, map is even zooming to my pinpoints and lines, however, they are not visible.
Linker settings set to Link SDK assemblies only. In Debug mode, with same linker settings, everything is working fine on both devices (tested on iPhone 6s, iPad mini 1 and iPad Air1) and simulators (tested multiple iOS versions and device types).

Please tell me if I can assist you.

Thanks!
EJ

**Comment by TorbenK** [comment]
That's unfortunate. There seems to be an issue that the renderer is not loaded. Did you test you app in TestFlight before submitting it?

**Comment by fransjan** [comment]
Hi,

No I did not :(

EJ

**Comment by TorbenK** [comment]
Do you call `TKCustomMapRenderer.InitMapRenderer();` in your `AppDelegate`?

**Comment by TorbenK** [comment]
I tried about an hour to reproduce this but no luck..My time is unfortunately pretty limited at the moment..

**Comment by acaliaro** [comment]
Have you tried creating an iPa starting from your github demo and install it on a device? Does it work?

Inviato da iPhone

**Comment by TorbenK** [comment]
Ok I was able to reproduce this. And it is indeed the linker which rips out the renderer, the `Init()` function I initially added to prevent this seems not to be enough.

The only workaround I have currently is to create an instance of the renderer(and the native places api if you want to use it) in your `AppDelegate` `FinishedLaunching`. 

``` CSharp
var dummy = new TKCustomMapRenderer();
var dummy2 = new NativePlacesApi();
```

**Comment by acaliaro** [comment]
@TorbenK thanks, it works.

**Comment by MithrilMan** [comment]
i confirm this problem and that the solution works, btw since i "hate" applying patches without knowing what caused this behaviour, do you have a clue about what's going wrong with the classical PreserveAttribute failing here?

could be a namespace problem? it seems that IOS looks for PreserveAttribute defined in Xamarin.iOS.Foundation.Preserve

https://developer.xamarin.com/guides/ios/advanced_topics/linker/#Preserving_Code

**Comment by ahmedkhan25** [comment]
Hi -Great library thanks for this btw!!

I too had the same issue (worked in debug but not in release) and resolved it via above mentioned workaround

  workaround : is to create an instance of the renderer(and the native places api if you want to use it) in your AppDelegate FinishedLaunching.

var dummy = new TKCustomMapRenderer();
var dummy2 = new NativePlacesApi();
