### ISSUE TITLE
TKCustomMapPin not showing

### ISSUE THREAD

**Issue by denmusic1992** [TorbenK/TK.CustomMap#290]
I just wanted to add TKCustomMapPin to myMap. In XAML:
`<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:maps="clr-namespace:Xamarin.Forms.Maps;assembly=Xamarin.Forms.Maps"
             xmlns:customMap="clr-namespace:TK.CustomMap;assembly=TK.CustomMap"
             xmlns:local="clr-namespace:Autoselect;assembly=Autoselect"
             x:Class="Autoselect.MapsActivity">
    <ContentPage.Content>
.......
<customMap:TKCustomMap Grid.Column="0" Grid.Row="1" MapType="Street" x:Name="MyMap" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" IsShowingUser="True" />....`
In cs:
ObservableCollection<TKCustomMapPin> pins = new ObservableCollection<TKCustomMapPin>();
            MyMap.CustomPins = pins;
            TKCustomMapPin pin = new TKCustomMapPin()
            {
                //position = IssoPosition.Ahead,
                DefaultPinColor = Color.Red,
                Position = new Xamarin.Forms.Maps.Position(0, 0),
                ShowCallout = true,
                Title = "a",
                Subtitle = "b",
            };
            pins.Add(pin);

But there is no pin on the map..
What's wrong?
I use 1.6.1 lib.

**Comment by TFreudi1** [comment]
Your Position is 0,0, this is in the atlantic oceon, did you look there?
![pos0](https://user-images.githubusercontent.com/4739177/34604762-4ff218d4-f209-11e7-8c49-59520b0c4283.png)
