### ISSUE TITLE
Prevent Pin (map marker) from rotating with map on Android?

### ISSUE THREAD

**Issue by TouchBoarder** [TorbenK/TK.CustomMap#294]
Since marker.Flat(true); has been added her: https://github.com/TorbenK/TK.CustomMap/commit/8946aa97f187226fe12b8e65bf85a25370313473

I hope you can make it possible to set this value to false to prevent the pin from rotating with the map in the next release?

**Comment by vincentcastagna** [comment]
Perhaps you can do something with Anchor when rotating ?

**Comment by TouchBoarder** [comment]
@Umar3x the map supports this, and the "flat" marker options was false before the commit i referred to. And it only affected Android, it's still rotating on iOS!? There is no need to do anything with the Anchor? That is just a Point, you probably meant the rotation property of the map marker (pin) :/

**Comment by TorbenK** [comment]
fix included in 2.0
