### ISSUE TITLE
System.MissingMethodException: Method 'Xamarin.Forms.Maps.Android.MapRenderer.OnCameraChange' not found.

### ISSUE THREAD

**Issue by filaulet** [TorbenK/TK.CustomMap#296]
Hi TK, Thanks for your great job.

I have downloaded 2.0.0-pre3 version.
I got following exception when setting up a customMap in my project.

System.MissingMethodException: Method 'Xamarin.Forms.Maps.Android.MapRenderer.OnCameraChange' not found.

01-02 12:16:52.693 W/DynamiteModule(14464): Local module descriptor class for com.google.android.gms.googlecertificates not found.
01-02 12:16:52.723 I/DynamiteModule(14464): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:4
01-02 12:16:52.725 I/DynamiteModule(14464): Selected remote version of com.google.android.gms.googlecertificates, version >= 4
01-02 12:16:52.744 W/System  (14464): ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/00000022/n/arm64-v8a
01-02 12:16:55.240 D/Mono    (14464): DllImport attempting to load: '/system/lib64/liblog.so'.
01-02 12:16:55.243 D/Mono    (14464): DllImport loaded library '/system/lib64/liblog.so'.
01-02 12:16:55.243 D/Mono    (14464): DllImport searching in: '/system/lib64/liblog.so' ('/system/lib64/liblog.so').
01-02 12:16:55.243 D/Mono    (14464): Searching for '__android_log_print'.
01-02 12:16:55.243 D/Mono    (14464): Probing '__android_log_print'.
01-02 12:16:55.244 D/Mono    (14464): Found as '__android_log_print'.
01-02 12:16:55.257 I/MonoDroid(14464): UNHANDLED EXCEPTION:
01-02 12:16:55.264 I/MonoDroid(14464): System.MissingMethodException: Method 'Xamarin.Forms.Maps.Android.MapRenderer.OnCameraChange' not found.
01-02 12:16:55.264 I/MonoDroid(14464):   at Android.Gms.Maps.GoogleMap+IOnCameraChangeListenerImplementor.OnCameraChange (Android.Gms.Maps.Model.CameraPosition position) [0x00017] in <bcb3af9a0115492baaa7a2e17d504257>:0 
01-02 12:16:55.264 I/MonoDroid(14464):   at Android.Gms.Maps.GoogleMap+IOnCameraChangeListenerInvoker.n_OnCameraChange_Lcom_google_android_gms_maps_model_CameraPosition_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_position) [0x0000f] in <bcb3af9a0115492baaa7a2e17d504257>:0 
01-02 12:16:55.264 I/MonoDroid(14464):   at (wrapper dynamic-method) System.Object:7009dc08-4222-45ac-b181-33e688dabd3b (intptr,intptr,intptr)
01-02 12:16:55.277 W/art     (14464): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
01-02 12:16:55.283 D/Mono    (14464): DllImport searching in: '__Internal' ('(null)').
01-02 12:16:55.283 D/Mono    (14464): Searching for 'java_interop_jnienv_throw'.
01-02 12:16:55.283 D/Mono    (14464): Probing 'java_interop_jnienv_throw'.
01-02 12:16:55.283 D/Mono    (14464): Found as 'java_interop_jnienv_throw'.
An unhandled exception occured.

01-02 12:16:56.065 E/mono    (14464): 
01-02 12:16:56.065 E/mono    (14464): Unhandled Exception:
01-02 12:16:56.065 E/mono    (14464): System.MissingMethodException: Method 'Xamarin.Forms.Maps.Android.MapRenderer.OnCameraChange' not found.
01-02 12:16:56.065 E/mono    (14464):   at (wrapper dynamic-method) System.Object:7009dc08-4222-45ac-b181-33e688dabd3b (intptr,intptr,intptr)
01-02 12:16:56.066 E/mono-rt (14464): [ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: Method 'Xamarin.Forms.Maps.Android.MapRenderer.OnCameraChange' not found.
01-02 12:16:56.066 E/mono-rt (14464):   at (wrapper dynamic-method) System.Object:7009dc08-4222-45ac-b181-33e688dabd3b (intptr,intptr,intptr)
01-02 12:16:56.263 I/TMSDISP (14464): AcsAndroidVirtualDisplayIntfImpl::~AcsAndroidVirtualDisplayIntfImpl - Enter
01-02 12:16:56.263 I/TMSDISP (14464): AcsAndroidVirtualDisplayIntfImpl::~AcsAndroidVirtualDisplayIntfImpl - Enter2
01-02 12:16:56.263 I/TMSDISP (14464): AcsAndroidVirtualDisplayIntfImpl::~AcsAndroidVirtualDisplayIntfImpl - mSource2
01-02 12:16:56.263 I/TMSDISP (14464): AcsAndroidVirtualDisplayIntfImpl::~AcsAndroidVirtualDisplayIntfImpl - Exit

In XAML file I wrote:

`<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:LimolaneMobile;assembly=LimolaneMobile"
             xmlns:conveters="clr-namespace:LimolaneMobile"
	     xmlns:customMap="clr-namespace:TK.CustomMap;assembly=TK.CustomMap"
	     x:Class="LimolaneMobile.ViaggioTab">`

and in my Grid

`<customMap:TKCustomMap x:Name="Map" Grid.Row="5" Grid.ColumnSpan="4" IsVisible="{Binding ViaggioItem.IsTransfer}"/>`

Am I missing something?

**Comment by vincentcastagna** [comment]
Check here => https://github.com/TorbenK/TK.CustomMap/issues/269
