### ISSUE TITLE
iOS 2.0.0 pre3 device location not displaying

### ISSUE THREAD

**Issue by jycribbs** [TorbenK/TK.CustomMap#298]
Once I upgraded to 2.0.0 pre3, the device location (blue dot) no longer appears on the map in iOS.  I have the proper permissions, the device location is known (i default my map to zoom into the device location, and it does still zoom in), but the blue dot doesn't show.

Anybody else having this problem?  Any solutions/resolutions?

Also, any estimate on when 2.0.0 will be released to Stable?

**Comment by jycribbs** [comment]
I just tested the location marker on a xamarin forms map.  It does display, which makes me lean more towards a TKCustomMap problem.

**Comment by vivekshah-zymr** [comment]
@jycribbs 
Do you have any working iOS/android demo for TKCustomMap using NuGet package?
I tried to implement it as per demo's ReadMe file but it doesn't work.

**Comment by jycribbs** [comment]
Still hoping someone can verify whether or not the User Location marker displays for them on iOS using 2.0.0 pre-3.

**Comment by vivekshah-zymr** [comment]
I have same problem, TKCustomMap 2.0.0 pre-3 iOS 11 doesn't show user's current location with blue dot. I have make IsShowingUser flag true, But location still doesn't display.

` IsShowingUser="true"`

**Comment by jycribbs** [comment]
So I'm not sure what changed, but this morning I noticed the device location is no longer appearing in Android either.  :(

**Comment by TorbenK** [comment]
Sorry for beeing late again. I'm still searching for time to fix the last few issues. I hope to get it done this month.

**Comment by geoffwc** [comment]
These 4 lines are missing from the iOS renderer in OnElementChanged:

UpdateMapType();
                UpdateIsShowingUser();
                UpdateHasZoomEnabled();
                UpdateHasScrollEnabled();

**Comment by TorbenK** [comment]
fix included in 2.0
