### ISSUE TITLE
Pin title (address) doesn't update after drag and drop of pin.

### ISSUE THREAD

**Issue by vivekshah-zymr** [TorbenK/TK.CustomMap#299]
I am using 2.0.0-pre3, and once use drag and drop the pin. I get the drop end event from PinDragEnd and get the updated latitude and longitude for it. But I want to update the title address for the pin too, Does anybody know how to get address details from latitude-longitude?
I am using PlacesApi.Google.

**Comment by TorbenK** [comment]
Reverse geocoding is not supported.
