### ISSUE TITLE
Feature: setVisibleMapRect or the ability to zoom to map to view the entire route

### ISSUE THREAD

**Issue by CliffCawley** [TorbenK/TK.CustomMap#30]
It would be really great to have a way to zoom and move (animated would be a bonus) the map to either a specified region or to simply focus on the calculated route so that it fills the view rectangle.

i.e. iOS native you can do something like:

```
        var zoomRect = MKMapRectNull

        for overlay in overlays {
            zoomRect = MKMapRectUnion(overlay.boundingMapRect, zoomRect)
        }

        let updatedMapRect = self.mapView.mapRectThatFits(zoomRect)

        self.mapView.setVisibleMapRect(updatedMapRect, edgePadding: UIEdgeInsetsMake(mapPadding, mapPadding, mapPadding, mapPadding), animated: true)
```

Allowing either the helper function to zoom/focus on the route or providing helper functions to help with the calculations would be great. Right now I can only choose  a center position and zoom level.

**Comment by TorbenK** [comment]
To zoom to one specific route you can use the `Bounds` property of the `TKRoute`. 

But I think what you are doing is calculating a route with multiple legs, which are basically multiple `TKRoute` instances. This is indeed not possible to zoom to in the current release.

But, in the 1.4.0 release I will introduce the following function, which is already available in the development branch:

`public void FitMapRegionToPositions(IEnumerable<Position> positions, bool animate = false)`

With that function you should be able to zoom to all positions of each leg, which will fit the entire route. Another cool thing to mention is that it will not even be neccessary to pass a instance of the control to your ViewModel(if you use MVVM). You can bind a property called `MapFunctions` which is a type of `IRendererFunctions` which will let you call all this functions from your ViewModel without passing the control. You can see that in the development branch too.

**Comment by TorbenK** [comment]
When I think about it this will probably not work in cases where the route goes around a specific position. I will think about adding a functionality to zoom to a collection of `MapSpan`.

**Comment by CliffCawley** [comment]
Ah sweet, in that case you read my mind! :)

As you assumed, I did want to do a route with multiple legs and show the entire trip sized to view.

Nice work on the property binding, I have been passing an instance of the map control to my view model so that will work great.

It would be great to have the functionality to zoom to a collection of MapSpan. Then I can build the MapSpans from the TKRoutes as you stated.

**Comment by CliffCawley** [comment]
Btw, just used the FitMapRegionToPositions from the Development, it's great, except definitely need one which fits to each TKRoute because the routes can easily go outside the View as they navigate around various roads :+1:

**Comment by TorbenK** [comment]
Introduced `FitToMapRegions` in 1.4.0
