### ISSUE TITLE
TKCustomMapRenderer OnDidSelectAnnotationView

### ISSUE THREAD

**Issue by jorgemrht** [TorbenK/TK.CustomMap#306]
Hello, 

I just update the custom map (version 2.0.0). When I click at some pin in my map, crash the app. Anyone having the same problem?

I change my code, and now I put this in the XAML:

    <tk:TKCustomMap
        CalloutClickedCommand="{Binding CalloutClickedCommand}"
        MapRegion="{Binding MapRegion}"
        PinSelectedCommand="{Binding PinSelectedCommand}"
        Pins="{Binding Pins}"
        SelectedPin="{Binding SelectedPin}" />

In my view model I load my pins, and set region. With the version 1.6 I do not have problemas, I only update the version and put the code in XMAL instead of the code behind.

![screenshot 2018-01-23 01 40 05](https://user-images.githubusercontent.com/6632773/35252259-e76aa88c-ffdf-11e7-911d-8ce25947b2f8.png)

**Comment by doancong** [comment]
I have that Problem to. Help me

**Comment by TorbenK** [comment]
Fixed in 2.0.1
