### ISSUE TITLE
MyMap.MoveToMapRegion(ms); Throwing Null Exception

### ISSUE THREAD

**Issue by sinclas** [TorbenK/TK.CustomMap#307]
Hi,

I have updated my project with VS mac using NuGet to TK.CustomMap v 2.0.  Its a Xamarin forms project.  I am calling MyMap.MoveToMapRegion(ms); and getting a null reference exception.   I have verified the Map and MapSpan objects.   

trace:    at TK.CustomMap.TKCustomMap.MoveToMapRegion (TK.CustomMap.MapSpan region, System.Boolean animate) [0x00006] in <86216605714a4751a6a20303e74da2bc>:0 
  at bounte.BounteWatchEditor+<InitMap>d__29.MoveNext () [0x001de]

Where can I start to resolve this?

**Comment by sinclas** [comment]
This "MoveToMapRegion" method of the map object was executing in an Init method in the constructor.  Not a good idea.  OnAppearing event of the XAML form is the best place to get the map to center with the span.  Not sure what changed but this works after moving this method out of the constructor.

**Comment by TorbenK** [comment]
You should be able to use `MapReady `event/command.
