### ISSUE TITLE
Issues with Route Calculation

### ISSUE THREAD

**Issue by filaulet** [TorbenK/TK.CustomMap#308]
Hi @TorbenK and developers!
I have encountered some issues with Route:
1) In Android:  
if I already have source and detination adresses before loading the page (so even the map), I calculate Positions, and the pins and route appear correctly on the map. 
If I load the page (so even the map) and then I get the addresses from google places api, I calculate Positions, the pins appear correctly on the map but `IsCalculated` of the Route remains `false` and so it doesn't appear on the Map.
2) In iOS: Route doesn't appear in neither of the two previous cases.

I tried to intercept `RouteCalculationFailed` event but it seems to be never raised.
In iOS I replaced `TKCustomMapRenderer.InitMapRenderer();` with 
`var dummy = new TKCustomMapRenderer();` as suggested in https://github.com/TorbenK/TK.CustomMap/issues/29#issuecomment-188826339, but it doesn't work for me.
What could be the problem?
Thanks

**Comment by TorbenK** [comment]
Fixed in 2.0.1. Thanks for reporting.

**Comment by filaulet** [comment]
Hi @TorbenK !
Thanks for your work.
I upgraded to v2.0.1 and I 've noticed some differences with previous version, about issues explained in this post:

1. In Android nothing as changed  
2. In iOS is a little bit better than earlier: 
    Now if page and Map is already loaded, route is calculated and is correctly drawn on the map with the 
    pins.
    If I already have source and destination addresses before loading the page (so even the map), I'm not 
    able to calculate positions and center the map because I call these functions in eventhandler of 
    MapReady event but this event seems to be never raised (only in iOS).
    
    My code in iOS and Android is:
    `Map.MapReady += (sender, args) =>
     {
	 SetCenterOfMap(); // set the center of the map
	 GetDirections(); // calculate positions and route
     };`
