### ISSUE TITLE
Not compatible with the new GooglePlayServices 60.1142.11

### ISSUE THREAD

**Issue by BillyMartin1964** [TorbenK/TK.CustomMap#325]
I converted my app to .net 2.0 and had to use the newest Google play services 60.1142.1 for AdMob to work. It wouldn't install until I uninstalled TK.CustomMap, and now TK.CustomMap won't reinstall because it only want to use GooglePlayServices 42.1021.1

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1107	Version conflict detected for Xamarin.GooglePlayServices.Tasks. Reference the package directly from the project to resolve this issue. 
 HunterTracker.Android -> Xamarin.GooglePlayServices.Base 60.1142.1 -> Xamarin.GooglePlayServices.Tasks (= 60.1142.1) 
 HunterTracker.Android -> HunterTracker -> TK.CustomMap 2.0.1 -> Xamarin.GooglePlayServices.Location 42.1021.1 -> Xamarin.GooglePlayServices.Tasks (= 42.1021.1).

**Comment by TravisFleenor** [comment]
Hey Billy,

Did you ever find any resolution to this? Any kind of workaround?

**Comment by TravisFleenor** [comment]
Figured out a workaround for this in case anyone needs to know. See the answer to my own question at stackoverflow.

https://stackoverflow.com/questions/51127699/tkcustommap-version-conflict/51146253#51146253
