### ISSUE TITLE
NullReferenceException in UpdateMapRegion Android

### ISSUE THREAD

**Issue by squibel** [TorbenK/TK.CustomMap#326]
When the map region is bound to a field in a ViewModel, there are 2 issues:
1. If the bound field is not initialized in the constructor, the UpdateMapRegion method throws a NullReferenceException.
2. When navigating to a new page with absolute navigation, the viewmodel of the current page is destroyed. When this happens, the same NullReferenceException in UpdateMapRegion is thrown, causing the page destruction to fail and possibly causing a memory leak.

Both issues are only on android, as it is happening in the android custom renderer. Tested this on iOS and the issues do not arise. Can't say anything about UWP or other platforms because our current project does not support these.

**Comment by ChaseFlorell** [comment]
How did you end up working around this? Did you do it in the ViewModel constructor or the Page constructor, or did you extend the cross platform TKCustomMaps and do it in that constructor?

**Comment by squibel** [comment]
For the first case I just set the binding to a default map region to solve the problem.
The second problem though was a bit more hacky to work around. I used the following code in the code behind file of the view where I used the map:
```
protected override void OnBindingContextChanged()
{
            if (Device.RuntimePlatform == Device.Android)
            {
                if (BindingContext != null)
                {
                    base.OnBindingContextChanged();
                }
            }
            else
            {
                base.OnBindingContextChanged();
            }
}
```
I don't think this solution is ideal, but for the moment it is the best I could come up with to get things running while waiting for the bug to be fixed.

**Comment by ChaseFlorell** [comment]
I submitted a PR, hoping he merges
