### ISSUE TITLE
NullReferenceException when selecting a pin

### ISSUE THREAD

**Issue by Sagariouz** [TorbenK/TK.CustomMap#333]
Hi Guys

I'm on the newest 2.0.1 version and I'm receiving a NullReferenceException when tapping on a pin, but only 60% of the time. Is there a work around, fix or a possible solution that I'm missing - have looked around in the closed ticket section.

**Comment by AmineSellami** [comment]
I confirm it this happens when clustering is enabled

**Comment by tuyen-vuduc** [comment]
#312 it's fixed
