### ISSUE TITLE
[!] Maintenance Help

### ISSUE THREAD

**Issue by ChaseFlorell** [TorbenK/TK.CustomMap#343]
I'm willing to pitch-in in a limited capacity.
I've submitted a PR that I really need merged, and I figure I can't ask for that without offering to help a little more. This is a great project with great potential.

I'm ok to review the odd PR, test as necessary. Triaging issues would be a little more cumbersome, but I'll see what I can do.

**Comment by dylanberry** [comment]
I would be more than willing to contribute as well.

**Comment by DanielCauser** [comment]
I'm hereby making my self available to help out in this project too. I'm using this Lib in one of my projects and I would love to help out maintaining this lib.

**Comment by TorbenK** [comment]
thanks guys. Invites are pending.

**Comment by ChaseFlorell** [comment]
@TorbenK we also need a simple way to push new packages. How is that all setup?

**Comment by TorbenK** [comment]
@ChaseFlorell I'll can give you an api key to publish, just give me an email or PM me on the xamarin forum.
