### ISSUE TITLE
CalloutClickedCommand

### ISSUE THREAD

**Issue by angelru** [TorbenK/TK.CustomMap#353]
Hello,

I don't understand, this command to active when I go load de maps...

does not have to be activated when I click on the information window of the selected pin?

I'm confused, any solution?

**Comment by angelru** [comment]
I'm sorry, this mistake was mine! all ready.

**Comment by pamela032709** [comment]
I don't understand this command. it is supposed to get triggered when you click the pin correct? I would like to open a different view when they click on the Callout command. any ideas?
