### ISSUE TITLE
Exception when I do click in pin with cluster 

### ISSUE THREAD

**Issue by angelru** [TorbenK/TK.CustomMap#354]
Hello,

When I have pins in cluster and I do click:

> [MonoDroid] UNHANDLED EXCEPTION:
> [MonoDroid] System.NullReferenceException: Object reference not set to an instance of an object.
> [MonoDroid]   at TK.CustomMap.Droid.TKCustomMapRenderer+<>c__DisplayClass36_0.<OnMarkerClick>b__0 (System.Collections.Generic.KeyValuePair`2[TKey,TValue] i) [0x0000c] in <049552a95b6c4893b0e95427a7a9c30d>:0 
> [MonoDroid]   at System.Linq.Enumerable.SingleOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x0002c] in <53973c2861a54e179ce4682966ad03c2>:0 
> [MonoDroid]   at TK.CustomMap.Droid.TKCustomMapRenderer.OnMarkerClick (System.Object sender, Android.Gms.Maps.GoogleMap+MarkerClickEventArgs e) [0x00016] in <049552a95b6c4893b0e95427a7a9c30d>:0 
> [MonoDroid]   at Android.Gms.Maps.GoogleMap+IOnMarkerClickListenerImplementor.OnMarkerClick (Android.Gms.Maps.Model.Marker marker) [0x00017] in <edd902d5391542adb87c92c0219e00cb>:0 
> [MonoDroid]   at Android.Gms.Maps.GoogleMap+IOnMarkerClickListenerInvoker.n_OnMarkerClick_Lcom_google_android_gms_maps_model_Marker_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_marker) [0x00011] in <edd902d5391542adb87c92c0219e00cb>:0 

any solution? What am I doing wrong?

**Comment by ssrodnas** [comment]
Hi,

Is there any update on this issue? 

Thanks,
S.
