### ISSUE TITLE
iOS Crash: NullReferenceException after VS 2019 update. 

### ISSUE THREAD

**Issue by busec0** [TorbenK/TK.CustomMap#363]
I'm encountering an issue on iOS after the update to VS 2019. I'm using XF 3.6.0 and Xamarin.iOS 12.8.0.0. It happens when an instance of TKCustomMap gets disposed. 

Within the iOS's `TKCustomMapRenderer` the app crashes with `NullReferenceException` when `base.Dispose(disposing)` is called in the overridden method: `protected override void Dispose(bool disposing)`

It can easily be reproduced by `pushing` a page which contains a Map instance and then `popping` it from the Navigation. 

You can download a sample app from here:

[TKMaps_DisposeFailsSampleProject.zip](https://github.com/TorbenK/TK.CustomMap/files/3084935/TKMaps_DisposeFailsSampleProject.zip)

It opens two different pages:

1. A Map Page using the default TKCustomMap implementation. Pushing and then popping the page will crash with NullReferenceException.
2. Custom Maps Page. I've manually added the content from TKCustomMapRenderer in my iOS project (named it `MapViewRenderer.cs`) and commented out the call to `base.Dispose()` within the `protected override void Dispose(bool disposing)`. App wont crash now.

The same issue is also opened here:
https://github.com/xamarin/xamarin-macios/issues/5899

**Comment by pamela032709** [comment]
Have you found any workaround for this issue?

**Comment by busec0** [comment]
Unfortunately no. In my debug builds I've manually added the iOS map view renderer and commented out the call to `base.Dispose()` (you can check my sample app, did the same thing there). 

It will prevent it from crashing and let me work "normally", but it is not a reliable solution for production builds.

I'm still waiting for a fix and hope we'll get one soon, might be an issue with Xamarin.iOS as it worked just fine with the previous version.

**Comment by pamela032709** [comment]
same here! android is fine as well just tested.  
lets just hope they can provide a fix. but not to enthusiastic about it since they havent provide any update or release in about a year.

**Comment by busec0** [comment]
Closing this as it was a Xamarin.iOS bug, the fix is ready and will soon be released. 

Check for more info: 
https://github.com/xamarin/xamarin-macios/issues/5899
