### ISSUE TITLE
Android - RequestDenied

### ISSUE THREAD

**Issue by CliffCawley** [TorbenK/TK.CustomMap#39]
I realise this is probably something I'm doing wrong but I've been banging my head against this wall for many hours and I'm not sure how else I can open a discussion with you @TorbenK 

I've Enabled the Places API, I've enabled Android Maps support, I've generated an Android Key and locked it to my package, verified the SHA-1 is correct and verified that the apk I'm using was signed correctly.

For the init calls in your sample you use:

```
GmsPlace.Init("YOUR API KEY");
            GmsDirection.Init("YOUR API KEY");
```

Am I supposed to have 2 seperate API keys there or are they the same key? Right now I just seem to have the 1 key which I use for both (Credentials ->CreateCredentials->ApiKey->Android Key). I've also tried leaving off the GmsPlace call since I only really need the Direction Api.

I've also updated my Android.manifest with:

```
<meta-data android:name="com.google.android.geo.API_KEY" android:value="YOUR API KEY" />
```

Again, is this the same API KEY I'm using in the above 2 calls?

If doesn't matter if I switch this to com.google.android.maps.v2.API_KEY instead of com.google.android.geo.API_KEY, I still get RequestDenied.

If I look in the Developer console at my Google Maps API usage, I can see that the calls are coming through and they all have 'Success' next to them. The Google Maps Directions API usage though has Client Errors (4xx) next to all of them though.

I was following the checklist from here: http://stackoverflow.com/a/25374435/10957 (Even though it's for the web service)

Any other ideas? Is there a better error log I can look at to see what the real problem is?

**Comment by TorbenK** [comment]
Does it work with the sample app and your key? Did you try with simulator or on a device? 

If you only need the directions api, all you need to do is call `GmsDirection.Init` and you don't necessarily need 2 seperate keys, you can handle all APIs with one key. Just make sure you activated the directions api.

**Comment by CliffCawley** [comment]
No, it doesn't work in the Sample app either. I realise that points to something I've got setup wrong in the developer console, but I just can't figure it out :(

The places api works, I can type an address and it comes back with results. I can search a location and it moves to that location, but when I attempt the directions it just comes back with RequestDenied. I've tried both on a virtual machine (with play services installed) and a device and I just get the same results.

I have the directions api activated too.

The services I have are:
Google Maps Android API 
Google Maps Directions API 
Google Places API for Android 
Google Places API Web Service (I was testing everything)
(and some other ones such as cloud sql, bigquery, etc)

Any other ideas?

**Comment by CliffCawley** [comment]
Okay, I figured I should be debugging the request you do and got some more details:

```
{
   "error_message" : "This IP, site or mobile application is not authorized to use this API key. Request received from IP address x.x.x.116, with empty referer",
   "routes" : [],
   "status" : "REQUEST_DENIED"
}
```

So you just log the Status as the error, but the error_message seems much more useful! Now I just have to figure out how to fix that :)

**Comment by CliffCawley** [comment]
Alright, finally got it figured out.

For GmsPlace.Init and com.google.android.geo.API_KEY in the AndroidManifest.xml you have to use the Android Api key.

But for GmsDirection.Init you have to create a Browser key, otherwise you get the above error. It doesn't make sense why that's the case, since the Browser key needs no referrers set, which means anyone can do queries with your key, but that's the only way I've gotten it to work :/

**Comment by TorbenK** [comment]
Doh, yes, of course you need the browser key I simply use the browser API for the route calculation. Seems like I don't know my own library.
