### ISSUE TITLE
iOS: Possible to remove 'Legal' text?

### ISSUE THREAD

**Issue by CliffCawley** [TorbenK/TK.CustomMap#40]
Is it possible to remove the 'legal' text from the iOS map? It looks like a tappable link but you can't tap on it.

Instead we will be showing all legal information in the About screen and don't need it on the map.

![screen shot 2016-03-03 at 9 24 53 am](https://cloud.githubusercontent.com/assets/6046554/13479339/d4e1b77a-e121-11e5-8338-ee8ccdf18fbd.png)

**Comment by TorbenK** [comment]
Well, yes this is possible by creating a custom renderer but Apple will probably reject your app if you do that.

**Comment by CliffCawley** [comment]
In that case, should the legal link do something when tapped?

**Comment by CliffCawley** [comment]
All good, the click event is being blocked because I've contained the map in a listview header.
