### ISSUE TITLE
iPad problem

### ISSUE THREAD

**Issue by MauSamba** [TorbenK/TK.CustomMap#43]
Hi all,

I really like your work but i have a problem

I included your package to my xamarin forms project and i've created a page where:
1) I get the device position
2) I center the tkcustommap to my position
3) I place the mapspan to mapspan(myPosition,distance.fromkilometers(1))
4) I place a pin to myPosition
5) I place a circle centered in myPosition with radius driven by a slider

all of this work on Android and iPhone but on iPad the mapspan is always equal to default and nothing appear(pin and circle)

One thing to notice:
sometimes my app work on iPad if i build it in debug or ad-hoc mode
if I build in AppStore mode it doesn't work on iPad

Ty for your work

**Comment by TorbenK** [comment]
Check out this: https://github.com/TorbenK/TK.CustomMap/issues/29

**Comment by MauSamba** [comment]
Sorry i skipped that issue because on some devices everything works well

I'll try with the istance

Thank you

**Comment by MauSamba** [comment]
It works

Thank you
