### ISSUE TITLE
TKCustomMapPin anchor different on Android vs iOS

### ISSUE THREAD

**Issue by CliffCawley** [TorbenK/TK.CustomMap#45]
I just came across this, but it looks like when using TKCustomMapPin on Android, your pin is anchored at the bottom of the image, but on iOS it's anchored in the center of the image.

Is this expected?

It would be great if it were the same for both platforms and potentially customizable

**Comment by TorbenK** [comment]
This is the default for Android and iOS. Added as future enhancement to make i configurable.
