### ISSUE TITLE
Double tap is triggering MapClickedCommand

### ISSUE THREAD

**Issue by scastria** [TorbenK/TK.CustomMap#46]
A user should be able to double tap the map to zoom in without triggering the MapClickedCommand.  Therefore, the tap listener needs to wait to make sure it isn't a double tap event before firing the MapClickedCommand.

**Comment by TorbenK** [comment]
Is this the same behavior on Android and iOS? I will mark this as a bug.

**Comment by scastria** [comment]
Only bug on iOS.  Android works fine.
