### ISSUE TITLE
Release iOS does not respond to MapClick

### ISSUE THREAD

**Issue by scastria** [TorbenK/TK.CustomMap#47]
Strange thing on iOS only.  My MapClick command is not triggering when I build the iOS app in Release mode.  Debug mode works fine.

I tried turning off the Linker in Release mode just to see if it was a linking issue and that made no difference.  I have my Debug and Release builds identical in settings and only the Release mode build does not trigger the MapClick.

Any ideas?

**Comment by TorbenK** [comment]
Check out this: https://github.com/TorbenK/TK.CustomMap/issues/29

**Comment by scastria** [comment]
Switching from the renderer init method to constructing a dummy instance works.  If it is a linker issue, I don't understand why turning off the linker didn't fix it as well.  Strange.

Maybe you should mention this in the readme on the main page of this github project.

**Comment by TorbenK** [comment]
Well, it doesn't seem to be the Xamarin linker which rips it out, it seems to be the xCode compiler.
