### ISSUE TITLE
Development branch: iOS Custom pins no longer show correctly

### ISSUE THREAD

**Issue by CliffCawley** [TorbenK/TK.CustomMap#49]
I merged your development changes into my fork because I needed the fix for the unrecognised selector and saw that you also had done the anchor points work! Thanks!

However I noticed that on iOS I see the markers flicker on the view for a moment as the map calculates the route, then when the route is rendered, the markers disappear. If I don't use a custom image for the markers, the standard pins animate in and show just fine.

On Android it seems to be working just fine.

I use the following in the RouteCalculationFinishedCommand:

``` csharp
if (Route.All(i => i.IsCalculated))
{
    MapView.FitToMapRegions(Route.Select(i => i.Bounds), false);
}
```

Just to add to this, if the map is scrolled to a location not within the pins/route, I'll see a couple of flickers of the custom pin graphics and the route and then the pins disappear.

If I refresh the pins/route collection (and the rectangle is still the same), the pins appear and stay on the screen this time.

If the view rectangle is already over the pins/route when the collection changes, the pins update correctly (including adding new pins)

**Comment by TorbenK** [comment]
That sounds very strange. Would be great to if you can get a repro project as I can't seem to reproduce that.

**Comment by CliffCawley** [comment]
Okay, I've narrowed this one down to the SvgImage control I was using. I switched to using baked graphics and there are no problems. Closing as it's not your bug :)
