### ISSUE TITLE
iOS - Pin needs to be clicked twice to open

### ISSUE THREAD

**Issue by kolchy** [TorbenK/TK.CustomMap#5]
Hey Torben,

Another small issue I found. On iOS, you need to click the pin twice to get the callout to show. I added a PinSelectedCommand that just shows Debug.WriteLine("Pin clicked"), and if I tap the pin once, I see the message, then tap again and the call out shows?

Cheers,
Kolchy

**Comment by TorbenK** [comment]
Hey,

thanks for the report. I will check. But if you look at the video, it doesn't seem to happen in the sample. At the moment I do not have a build server so I cannot confirm.

**Comment by kolchy** [comment]
Hey Torben,

I think this is a problem at my end - I have a custom pin that inherits from your TKCustomMapPin, and was interchanging the types in different parts of the code. I'll close this for now and keep an eye out :)

Cheers,
Kolchy
