### ISSUE TITLE
iOS: Sequence contains more than one matching element in OnRoutePropertyChanged

### ISSUE THREAD

**Issue by CliffCawley** [TorbenK/TK.CustomMap#50]
In OnRoutePropertyChanged you do

``` csharp
var item = this._routes.SingleOrDefault(i => i.Value.Overlay.Equals(route));
```

Sometimes because of a race condition, this _routes list will have multiple of the same route and therefore this will assert.

As far as I can tell, this happens from the AddRoute function where it's added in the completion handler of the CalculateDirections call.

I'm still trying to reproduce it 100% so I can create a test project or fix it myself and send a pull request.

I think it might be if you change the route data while it's still calculating a previous route, but that's a guess.

**Comment by TorbenK** [comment]
Well it makes no sence to pass the same instance twice into the list though.

**Comment by CliffCawley** [comment]
I think what's happened is that the list was cleared, and then items re-added while an existing CalculateDirections was still running in the background, it then got added again.

**Comment by TorbenK** [comment]
I'm wondering on how to proceed with this one

**Comment by CliffCawley** [comment]
Yeah, I'm not sure. Perhaps just close the issue until I can either get it in a project to you, or can fix the issue myself and I'll submit a PR. I raised it because I though you might take a look at the code and immediately see the problem

**Comment by CliffCawley** [comment]
Looks like this is related to #60 as for me OnRouteCollectionChanged is called multiple times for the same changed notification, which results in multiple AddRoute calls for the same route!

In the MapLoaded event you call UpdateRoutes which has firstUpdate = true by default. So when you get multiple MapLoaded events, the following code starts stacking events because the CollectionChanged is already bound to OnRouteCollectionChanged:

```
if (firstUpdate)
 {
    var observAble = this.FormsMap.Routes as INotifyCollectionChanged;
    if (observAble != null)
    {
        observAble.CollectionChanged += OnRouteCollectionChanged;
    }
}
```

A quick fix would be to unbind before binding but this should possibly be solved in a better way.

```
if (firstUpdate)
{
    var observAble = this.FormsMap.Routes as INotifyCollectionChanged;
    if (observAble != null)
    {
        observAble.CollectionChanged -= OnRouteCollectionChanged;
        observAble.CollectionChanged += OnRouteCollectionChanged;
    }
}
```
