### ISSUE TITLE
Pins do not appear in release mode (IOS)

### ISSUE THREAD

**Issue by TioWidow** [TorbenK/TK.CustomMap#51]
I'm having this problem and I am using your CustomMap and CustomPin.
Can you have something to do?

https://forums.xamarin.com/discussion/63003/pins-do-not-appear-in-release-mode?new=1

I've tried using the default image pins and a picture and none of the two cases worked.

**Comment by TorbenK** [comment]
Check #29

**Comment by TioWidow** [comment]
I solved the problem by copying all settings DEBUG to RELEASE mode as well. Unfortunately the IPA has doubled in size.

Recalling that the problem occurred only in IPHONE 6 and IPHONE 6 PLUS and only in the RELEASE mode (also the IPA file).

This fully functional in IPHONE 5 and 5C.

So the problem was solved for me, but if you are willing to investigate the problem I'll be at your disposal.

**Comment by TioWidow** [comment]
I believe in the possibility of the problem is Xamarin not in your TK.CustomMap

But

Evidence
![ca96d654-3902-499e-b0af-a1865df998ff](https://cloud.githubusercontent.com/assets/4378980/13919048/efbb5bb0-ef49-11e5-993f-6e3129077182.jpeg)

Thanks for All..

**Comment by TorbenK** [comment]
You should definitely NOT copy your debug configuration over to your release configuration. Check the issue #29 and use the workaround documentated in there.
