### ISSUE TITLE
IPlaceResult is too simple

### ISSUE THREAD

**Issue by scastria** [TorbenK/TK.CustomMap#52]
The items returned from INativePlacesApi are too simple.  As best as possible, each property of the underlying native API should be kept separate in IPlaceResult and not all combined together in the Description.  Also, the important Name property is not being put inside the Description return value.  So if I search for "Donuts" in the sample app, I expect to get back things like "Dunkin Donuts", but I just get back the addresses since the Name is not put inside the Description property.

**Comment by TorbenK** [comment]
I can do that, but I really dont have any time at the moment. Anyway, that should be very easy to do so feel free to create a pull request. Thanks!
