### ISSUE TITLE
TKCustomMapRenderer - Unable to add a route

### ISSUE THREAD

**Issue by tecodutra** [TorbenK/TK.CustomMap#55]
I was unable to add a route on the map because the latitude and longitude were added to the URI with a comma instead of point (eg.: origin=40,7830603,-73,9712488&destination=40,7127837,-74,0059413). The problem occurs in TK.CustomMap.Extensios.AsString(Position).

**Comment by TorbenK** [comment]
Yes, that is known. @Falco20019 already fixed that in a pull request. Will be added to the next release.
