### ISSUE TITLE
TKCustomMapPin BindableObject

### ISSUE THREAD

**Issue by tizianomanni** [TorbenK/TK.CustomMap#56]
Hello,
I sorry for my bad English.

I need to make the TK Custom Map in a Bindable Object to create the Location property, Title, etc. Bindable. To do this I need the TKCustomMapPin inherit from bindableobject class.
You could make this change?
Thank you Regards
Manni Tiziano

**Comment by TorbenK** [comment]
I don't see any reason why we could not do that.
