### ISSUE TITLE
Dependencies issues

### ISSUE THREAD

**Issue by JeanCollas** [TorbenK/TK.CustomMap#57]
When installing the nuget, it requires some dependencies, on which Microsoft.Net.Http, which depends on Microsoft.Bcl.Build. This is not available for iOS projects.
Is there a way to solve that? (I have just added the nuget manually to the iOS project, don't know yet if it works...)

**Comment by TorbenK** [comment]
Microsoft.Bcl.Build can be installed on iOS projects. Try to update your NuGet if it fails.

**Comment by JeanCollas** [comment]
I haven't been able to. However to solve the issue I have used directly the source projects in my solution.
