### ISSUE TITLE
CustomMap on a TabbedPage does not render

### ISSUE THREAD

**Issue by JeanCollas** [TorbenK/TK.CustomMap#58]
I have tried to embbed the map into a TabbedPage.
It works fine on Android, however it fails on iPhone (the map is white/not displaying). An idea why?

(Setting the BindingContext before displaying also causes a lot of troubles!)

**Comment by danderwald** [comment]
Hey JeanCollas,
I am using a tabbed page on iOS and have no problems.

It seems that your info.plist needs an update:
add the following lines to your info.plist

`<key>NSLocationAlwaysUsageDescription</key>
    <string>Can we use your location</string>
<key>NSLocationWhenInUseUsageDescription</key>
    <string>We are using your location</string>`

find a description here:
https://developer.xamarin.com/guides/xamarin-forms/working-with/maps/

**Comment by JeanCollas** [comment]
Hello,
I think it is not my info.plist as the rendering works if I start directly on the page, but if I put a tabbed page around, the map is white and does not load (or render).
I have the following lines in the info.plist, it seems ok :
    <key>NSLocationWhenInUseUsageDescription</key>
    <string>You are using location!</string>
    <key>NSLocationAlwaysUsageDescription</key>
    <string>You are about to use location!</string>

**Comment by JeanCollas** [comment]
And I have the init in the starting function (anyway without the tabbed page the map works)

**Comment by JeanCollas** [comment]
Ok, I found a workaround.....
It has to be encapsulated into a NavigationPage, then the map appears.

If it can help someone, I don't understand why, but here is my solution, it works using:
NavigationPage > TabbedPage > ContentPage > TKCustomMap

or 
ContentPage > TKCustomMap

But **not** 
TabbedPage > ContentPage > TKCustomMap

**Comment by TorbenK** [comment]
Doesn't seem to be related to the control. Closed.
