### ISSUE TITLE
iOS registering FormsMap.PropertyChanged several times

### ISSUE THREAD

**Issue by CliffCawley** [TorbenK/TK.CustomMap#60]
This only happens on iOS as on Android you're doing the FormsMap.PropertyChanged event registration call in OnElementChanged.

On iOS however it seems the MapLoaded can be called multiple times. For me it can get called 2-3 times without any calls to OnElementChanged. Once when the map is first initialized and again when it's finished animating to it's destination MapCenter

```
            this.FormsMap.PropertyChanged += OnMapPropertyChanged;
```

As a test I unregistered right before

```
            this.FormsMap.PropertyChanged -= OnMapPropertyChanged;
            this.FormsMap.PropertyChanged += OnMapPropertyChanged;
```

and I no longer get multiple PropertyChanged notifications

**Comment by TorbenK** [comment]
Same root as #61
