### ISSUE TITLE
Google Maps in ios TK.CustomMap 

### ISSUE THREAD

**Issue by mehdyhaghy** [TorbenK/TK.CustomMap#65]
Is there anyway to show Google Maps in TK.CustomMap on iOS?

**Comment by TorbenK** [comment]
No, sorry. It's possible to add this, but it requires a fair amount of time which I don't have currently.

**Comment by charlenni** [comment]
You only want to show tiles rendered by Google Maps or you would like to have Google MapView? The first is only an URL, the later much work ;)

**Comment by TorbenK** [comment]
If you want GoogleMaps, use: https://github.com/amay077/Xamarin.Forms.GoogleMaps/
