### ISSUE TITLE
Zoom Level

### ISSUE THREAD

**Issue by tecodutra** [TorbenK/TK.CustomMap#66]
How do I change the zoom level by the code?

**Comment by TorbenK** [comment]
There is nothing like a zoom level. You can zoom to a specified `Radius`. For example zoom to 200m on the current center:

`MapSpan newRegion = MapSpan.FromCenterAndRadius(MapRegion.Center, Distance.FromMeters(200));`

And then either set the `MapRegion` or call `MoveToMapRegion`.

**Comment by JeanCollas** [comment]
This may help if you need the zoomlevel:
http://stackoverflow.com/a/21034310
However I find the radius approach more convenient. 
Zoom++ should correspond to Radius/=2

**Comment by jamie-steele** [comment]
Sorry to reply to a closed thread, but I am having some trouble getting this to work is it possible you could provide a more complete example?

I tried this but it doesn't zoom to the right place 
`myMap.MapRegion = MapSpan.FromCenterAndRadius(new Position(49.289124, -123.116498), Distance.FromMeters(200));`

**Comment by JeanCollas** [comment]
That should bring you to Vancouvert, however 200 is very low for a distance, you should try a higher value (like several kilometers to start).

**Comment by jamie-steele** [comment]
Regardless of what I set it to it too the map moves to near Africa just less zoomed in, is this perhaps a bug?

**Comment by JeanCollas** [comment]
Try "MainMap.MoveToRegion()"

Or maybe you could try that:
                    var loc = await Plugin.Geolocator.CrossGeolocator.Current.GetPositionAsync(3000);
                    MainMap.MoveToRegion(MapSpan.FromCenterAndRadius(new Xamarin.Forms.Maps.Position(loc.Latitude, loc.Longitude),
                            Distance.FromKilometers(10))
                        );

With the relevant nugget package.
It works fine for me

**Comment by jamie-steele** [comment]
Stilll does the same thing, when I use stock maps that function worked fine though.
