### ISSUE TITLE
google play location v26 causes link error

### ISSUE THREAD

**Issue by Haukinger** [TorbenK/TK.CustomMap#67]
Can we change the dependency on google location services from "exactly 26" to "at least 26"?
If I install v26 in my project I get an "already added" exception from java when building, because two different google play services are installed (26 and 29).

**Comment by TorbenK** [comment]
If you use the latest pre release of Xamarin Forms this is possible, otherwise you need to install exactly 26.

**Comment by InquisitorJax** [comment]
updated the latest xamarin forms release that adds support for 29 - but Google Play location doesn't update because TK.Maps set to exactly 26. Not sure if it's related, but then my Android AppCompat theming files don't compile. 
There an issue with making the package >= 26?

**Comment by TorbenK** [comment]
Hi, I will update the dependencies and release a new version by tomorrow hopefully.
