### ISSUE TITLE
Getting issue in iOS phone

### ISSUE THREAD

**Issue by sdoulaghar** [TorbenK/TK.CustomMap#68]
Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[MKMapView setShowsTraffic:]: unrecognized selector sent to instance 0x16752770
Native stack trace:
    0   CoreFoundation                      0x29df114f <redacted> + 150
    1   libobjc.A.dylib                     0x3827bc77 objc_exception_throw + 38
    2   CoreFoundation                      0x29df65fd <redacted> + 0
    3   CoreFoundation                      0x29df44d9 <redacted> + 712
    4   CoreFoundation                      0x29d239d8 _CF_forwarding_prep_0 + 24
    5   ODISMemberiOS                       0x00cb72a8 wrapper_managed_to_native_ObjCRuntime_Messaging_void_objc_msgSend_bool_intptr_intptr_bool + 128
    6   ODISMemberiOS                       0x00c1f364 MapKit_MKMapView_set_ShowsTraffic_bool + 88
    7   ODISMemberiOS                       0x017e23ec TK_CustomMap_iOSUnified_TKCustomMapRenderer_UpdateShowTraffic + 408
    8   ODISMemberiOS                       0x017cd078 TK_CustomMap_iOSUnified_TKCustomMapRenderer_OnElementChanged_Xamarin_Forms_Platform_iOS_ElementChangedEventArgs_1_Xamarin_Forms_View + 5720
    9   ODISMemberiOS                       0x00ac5a58 Xamarin_Forms_Platform_iOS_VisualElementRenderer_1_TElement_REF_SetElement_TElement_REF + 2276
    10  ODISMemberiOS                       0x00ac512c Xamarin_Forms_Platform_iOS_VisualElementRenderer_1_TElement_REF_Xamarin_Forms_Platform_iOS_IVisualElementRenderer_SetElement_Xamarin_Forms_VisualElement + 160
    11  ODISMemberiOS                       0x00ab46f0 Xamarin_Forms_Platform_iOS_Platform_CreateRenderer_Xamarin_Forms_VisualElement + 416
    12  ODISMemberiOS                       0x00ac38f0 Xamarin_Forms_Platform_iOS_VisualElementPackager_OnChildAdded_Xamarin_Forms_VisualElement + 116
    13  ODISMemberiOS                       0x00ac2388 Xamarin_Forms_Platform_iOS_VisualElementPackager_Load + 484
    14  ODISMemberiOS                       0x00ac5860 Xamarin_Forms_Platform_iOS_VisualElementRenderer_1_TElement_REF_SetElement_TElement_REF + 1772
    15  ODISMemberiOS                       0x00ac512c Xamarin_Forms_Platform_iOS_VisualElementRenderer_1_TElement_REF_Xamarin_Forms_Platform_iOS_IVisualElementRenderer_SetElement_Xamarin_Forms_VisualElement + 160
    16  ODISMemberiOS                       0x00ab46f0 Xamarin_Forms_Platform_iOS_Platform_CreateRenderer_Xamarin_Forms_VisualElement + 416
    17  ODISMemberiOS                       0x00ac38f0 Xamarin_Forms_Platform_iOS_VisualElementPackager_OnChildAdded_Xamarin_Forms_VisualElement + 116
    18  ODISMemberiOS                       0x00ac2388 Xamarin_Forms_Platform_iOS_VisualElementPackager_Load + 484
    19  ODISMemberiOS                       0x00ac5860 Xamarin_Forms_Platform_iOS_VisualElementRenderer_1_TElement_REF_SetElement_TElement_REF + 1772
    20  ODISMemberiOS                       0x00ac512c Xamarin_Forms_Platform_iOS_VisualElementRenderer_1_TElement_REF_Xamarin_Forms_Platform_iOS_IVisualElementRenderer_SetElement_Xamarin_Forms_VisualElement + 160
    21  ODISMemberiOS                       0x00ab46f0 Xamarin_Forms_Platform_iOS_Platform_CreateRenderer_Xamarin_Forms_VisualElement + 416
    22  ODISMemberiOS                       0x00ac38f0 Xamarin_Forms_Platform_iOS_VisualElementPackager_OnChildAdded_Xamarin_Forms_VisualElement + 116
    23  ODISMemberiOS                       0x00ac382c Xamarin_Forms_Platform_iOS_VisualElementPackager_OnChildAdded_object_Xamarin_Forms_ElementEventArgs + 292
    24  ODISMemberiOS                       0x004c6dd4 Xamarin_Forms_Element_OnChildAdded_Xamarin_Forms_Element + 572
    25  ODISMemberiOS                       0x004eaa64 Xamarin_Forms_VisualElement_OnChildAdded_Xamarin_Forms_Element + 120
    26  ODISMemberiOS                       0x004d0b58 Xamarin_Forms_Layout_1_T_REF_OnChildAdded_Xamarin_Forms_Element + 120
    27  ODISMemberiOS                       0x004d2e28 Xamarin_Forms_Layout_OnInternalAdded_Xamarin_Forms_View + 132
    28  ODISMemberiOS                       0x004d25f4 Xamarin_Forms_Layout_InternalChildrenOnCollectionChanged_object_System_Collections_Specialized_NotifyCollectionChangedEventArgs + 1888
    29  ODISMemberiOS                       0x008007cc wrapper_delegate_invoke__Module_invoke_void_object_NotifyCollectionChangedEventArgs_object_System_Collections_Specialized_NotifyCollectionChangedEventArgs + 216
    30  ODISMemberiOS                       0x006f7f80 System_Collections_ObjectModel_ObservableCollection_1_T_REF_OnCollectionChanged_System_Collections_Specialized_NotifyCollectionChangedEventArgs + 96
    31  ODISMemberiOS                       0x006f8180 System_Collections_ObjectModel_ObservableCollection_1_T_REF_OnCollectionChanged_System_Collections_Specialized_NotifyCollectionChangedAction_object_int + 104
    32  ODISMemberiOS                       0x006f7bb4 System_Collections_ObjectModel_ObservableCollection_1_T_REF_InsertItem_int_T_REF + 120
    33  ODISMemberiOS                       0x000b1174 System_Collections_ObjectModel_Collection_1_T_REF_Add_T_REF + 180
    34  ODISMemberiOS                       0x004ce378 Xamarin_Forms_ObservableWrapper_2_TKey_REF_TValue_REF_Add_TValue_REF + 600
    35  ODISMemberiOS                       0x00f46eb4 ODISMember_Pages_Index_RefreshWorkspace_int + 2728
    36  ODISMemberiOS                       0x00f48f54 ODISMember_Pages_Index__EventDispatcher_OnRefreshd__3_MoveNext + 4968
    37  ODISMemberiOS                       0x00140480 System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_T_REF_T_REF_ + 252
    38  ODISMemberiOS                       0x0013f560 System_Runtime_CompilerServices_AsyncVoidMethodBuilder_Start_T_REF_T_REF_ + 64
    39  ODISMemberiOS                       0x00f463d8 ODISMember_Pages_Index_EventDispatcher_OnRefresh_object_ODISMember_Helpers_UIHelpers_RefreshEventArgs + 564
    40  ODISMemberiOS                       0x00fb4a14 wrapper_delegate_invoke_System_EventHandler_1_ODISMember_Helpers_UIHelpers_RefreshEventArgs_invoke_void_object_TEventArgs_object_ODISMember_Helpers_UIHelpers_RefreshEventArgs + 712
    41  ODISMemberiOS                       0x00f15014 ODISMember_Helpers_UIHelpers_EventDispatcher_RaiseEvent_object_ODISMember_Helpers_UIHelpers_RefreshEventArgs + 288
    42  ODISMemberiOS                       0x00f49c34 ODISMember_Pages_RootPage_NavigateTo_ODISMember_Model_CustomMenuItem + 2060
    43  ODISMemberiOS                       0x00f49eac ODISMember_Pages_RootPage___ctorb__0_0_object_Xamarin_Forms_SelectedItemChangedEventArgs + 224
    44  ODISMemberiOS                       0x005ac6fc wrapper_delegate_invoke_System_EventHandler_1_Xamarin_Forms_SelectedItemChangedEventArgs_invoke_void_object_TEventArgs_object_Xamarin_Forms_SelectedItemChangedEventArgs + 712
    45  ODISMemberiOS                       0x00422be0 Xamarin_Forms_ListView_OnSelectedItemChanged_Xamarin_Forms_BindableObject_object_object + 340
    46  ODISMemberiOS                       0x0038c9a8 Xamarin_Forms_BindableObject_SetValueActual_Xamarin_Forms_BindableProperty_Xamarin_Forms_BindableObject_BindablePropertyContext_object_bool_Xamarin_Forms_BindableObject_SetValueFlags_bool + 2124
    47  ODISMemberiOS                       0x0038bf3c Xamarin_Forms_BindableObject_SetValueCore_Xamarin_Forms_BindableProperty_object_Xamarin_Forms_BindableObject_SetValueFlags_Xamarin_Forms_BindableObject_SetValuePrivateFlags + 2456
    48  ODISMemberiOS                       0x00388810 Xamarin_Forms_BindableObject_SetValue_Xamarin_Forms_BindableProperty_object_bool_bool + 1108
    49  ODISMemberiOS                       0x00388120 Xamarin_Forms_BindableObject_SetValue_Xamarin_Forms_BindableProperty_object + 148
    50  ODISMemberiOS                       0x0041f60c Xamarin_Forms_ListView_set_SelectedItem_object + 136
    51  ODISMemberiOS                       0x00f4b7f8 ODISMember_Pages_MenuPage_selectMenuItem_int + 1024
    52  ODISMemberiOS                       0x00f4b394 ODISMember_Pages_MenuPage_EventDispatcher_OnRefresh_object_ODISMember_Helpers_UIHelpers_RefreshEventArgs + 364
    53  ODISMemberiOS                       0x00fb4a14 wrapper_delegate_invoke_System_EventHandler_1_ODISMember_Helpers_UIHelpers_RefreshEventArgs_invoke_void_object_TEventArgs_object_ODISMember_Helpers_UIHelpers_RefreshEventArgs + 712
    54  ODISMemberiOS                       0x00f15014 ODISMember_Helpers_UIHelpers_EventDispatcher_RaiseEvent_object_ODISMember_Helpers_UIHelpers_RefreshEventArgs + 288
    55  ODISMemberiOS                       0x00f478dc ODISMember_Pages_Index___ctorb__1_2 + 220
    56  ODISMemberiOS                       0x004479e8 Xamarin_Forms_Command__c__DisplayClass4_0___ctorb__0_object + 128
    57  ODISMemberiOS                       0x00447608 Xamarin_Forms_Command_Execute_object + 132
    58  ODISMemberiOS                       0x003b45dc Xamarin_Forms_TapGestureRecognizer_SendTapped_Xamarin_Forms_View + 432
    59  ODISMemberiOS                       0x00b42004 Xamarin_Forms_Platform_iOS_EventTracker__c__DisplayClass3_0__GetNativeRecognizerb__0_UIKit_UITapGestureRecognizer + 752
    60  ODISMemberiOS                       0x00c23c58 UIKit_UITapGestureRecognizer_Callback_Activated_UIKit_UITapGestureRecognizer + 52
    61  ODISMemberiOS                       0x002f79cc wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 256
    62  ODISMemberiOS                       0x018f7fcf mono_jit_runtime_invoke + 1130
    63  ODISMemberiOS                       0x0193a495 mono_runtime_invoke + 88
    64  ODISMemberiOS                       0x01887859 _ZL30native_to_managed_trampoline_1P11objc_objectP13objc_selectorPP11_MonoMethodS0_PKcS7_S7_ + 268
    65  ODISMemberiOS                       0x01895781 -[**UITapGestureRecognizer target:] + 80
    66  UIKit                               0x2d5cebbf <redacted> + 294
    67  UIKit                               0x2d47dd0d <redacted> + 668
    68  UIKit                               0x2d897991 <redacted> + 48
    69  UIKit                               0x2d446cc5 <redacted> + 216
    70  UIKit                               0x2d444c3f <redacted> + 2950
    71  UIKit                               0x2d47c0dd <redacted> + 784
    72  UIKit                               0x2d47b9cd <redacted> + 520
    73  UIKit                               0x2d451ba5 <redacted> + 196
    74  UIKit                               0x2d6c82bf <redacted> + 14538
    75  UIKit                               0x2d4505a7 <redacted> + 1350
    76  CoreFoundation                      0x29db722f <redacted> + 14
    77  CoreFoundation                      0x29db6643 <redacted> + 222
    78  CoreFoundation                      0x29db4cc1 <redacted> + 768
    79  CoreFoundation                      0x29d009a1 CFRunLoopRunSpecific + 476
    80  CoreFoundation                      0x29d007b3 CFRunLoopRunInMode + 106
    81  GraphicsServices                    0x316c21a9 GSEventRunModal + 136
    82  UIKit                               0x2d4b1635 UIApplicationMain + 1440
    83  ODISMemberiOS                       0x00cc392c wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr + 272
    84  ODISMemberiOS                       0x00c16c50 UIKit_UIApplication_Main_string___intptr_intptr + 52
    85  ODISMemberiOS                       0x00c16c10 UIKit_UIApplication_Main_string___string_string + 204
    86  ODISMemberiOS                       0x0007d4a0 ODISMember_iOS_Application_Main_string** + 192
    87  ODISMemberiOS                       0x002f79cc wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 256
    88  ODISMemberiOS                       0x018f7fcf mono_jit_runtime_invoke + 1130
    89  ODISMemberiOS                       0x0193a495 mono_runtime_invoke + 88
    90  ODISMemberiOS                       0x0193d7c1 mono_runtime_exec_main + 284
    91  ODISMemberiOS                       0x019a9ff0 xamarin_main + 2072
    92  ODISMemberiOS                       0x0189fe51 main + 112
    93  libdyld.dylib                       0x38849aaf <redacted> + 2

  at ObjCRuntime.Runtime.ThrowNSException (IntPtr ns_exception) [0x00000] in /Users/builder/data/lanes/3051/5f11db87/source/maccore/src/ObjCRuntime/Runtime.cs:234 
  at ObjCRuntime.Runtime.throw_ns_exception (IntPtr exc) <0xc3ad24 + 0x0001b> in <filename unknown>:0 
  at (wrapper native-to-managed) ObjCRuntime.Runtime:throw_ns_exception (intptr)
  at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, IntPtr principal, IntPtr delegate) [0x00005] in /Users/builder/data/lanes/3051/5f11db87/source/maccore/src/UIKit/UIApplication.cs:77 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0001c] in /Users/builder/data/lanes/3051/5f11db87/source/maccore/src/UIKit/UIApplication.cs:60 
  at ODISMember.iOS.Application.Main (System.String[] args) [0x00002] in D:\TFS\pinnacleps.visualstudio.com\ODIS\ODIS-Enhancements-EF6-dev-PinnacleVP\Mobile\ODISMember\ODISMember.iOS\Main.cs:20   0   CoreFoundation                      0x29df114f <redacted> + 150
    1   libobjc.A.dylib                     0x3827bc77 objc_exception_throw + 38
    2   CoreFoundation                      0x29df65fd <redacted> + 0
    3   CoreFoundation                      0x29df44d9 <redacted> + 712
    4   CoreFoundation                      0x29d239d8 _CF_forwarding_prep_0 + 24
    5   ODISMemberiOS                       0x00cb72a8 wrapper_managed_to_native_ObjCRuntime_Messaging_void_objc_msgSend_bool_intptr_intptr_bool + 128
    6   ODISMemberiOS                       0x00c1f364 MapKit_MKMapView_set_ShowsTraffic_bool + 88
    7   ODISMemberiOS                       0x017e23ec TK_CustomMap_iOSUnified_TKCustomMapRenderer_UpdateShowTraffic + 408
    8   ODISMemberiOS                       0x017cd078 TK_CustomMap_iOSUnified_TKCustomMapRenderer_OnElementChanged_Xamarin_Forms_Platform_iOS_ElementChangedEventArgs_1_Xamarin_Forms_View + 5720
    9   ODISMemberiOS                       0x00ac5a58 Xamarin_Forms_Platform_iOS_VisualElementRenderer_1_TElement_REF_SetElement_TElement_REF + 2276
    10  ODISMemberiOS                       0x00ac512c Xamarin_Forms_Platform_iOS_VisualElementRenderer_1_TElement_REF_Xamarin_Forms_Platform_iOS_IVisualElementRenderer_SetElement_Xamarin_Forms_VisualElement + 160
    11  ODISMemberiOS                       0x00ab46f0 Xamarin_Forms_Platform_iOS_Platform_CreateRenderer_Xamarin_Forms_VisualElement + 416
    12  ODISMemberiOS                       0x00ac38f0 Xamarin_Forms_Platform_iOS_VisualElementPackager_OnChildAdded_Xamarin_Forms_VisualElement + 116
    13  ODISMemberiOS                       0x00ac2388 Xamarin_Forms_Platform_iOS_VisualElementPackager_Load + 484
    14  ODISMemberiOS                       0x00ac5860 Xamarin_Forms_Platform_iOS_VisualElementRenderer_1_TElement_REF_SetElement_TElement_REF + 1772
    15  ODISMemberiOS                       0x00ac512c Xamarin_Forms_Platform_iOS_VisualElementRenderer_1_TElement_REF_Xamarin_Forms_Platform_iOS_IVisualElementRenderer_SetElement_Xamarin_Forms_VisualElement + 160
    16  ODISMemberiOS                       0x00ab46f0 Xamarin_Forms_Platform_iOS_Platform_CreateRenderer_Xamarin_Forms_VisualElement + 416
    17  ODISMemberiOS                       0x00ac38f0 Xamarin_Forms_Platform_iOS_VisualElementPackager_OnChildAdded_Xamarin_Forms_VisualElement + 116
    18  ODISMemberiOS                       0x00ac2388 Xamarin_Forms_Platform_iOS_VisualElementPackager_Load + 484
    19  ODISMemberiOS                       0x00ac5860 Xamarin_Forms_Platform_iOS_VisualElementRenderer_1_TElement_REF_SetElement_TElement_REF + 1772
    20  ODISMemberiOS                       0x00ac512c Xamarin_Forms_Platform_iOS_VisualElementRenderer_1_TElement_REF_Xamarin_Forms_Platform_iOS_IVisualElementRenderer_SetElement_Xamarin_Forms_VisualElement + 160
    21  ODISMemberiOS                       0x00ab46f0 Xamarin_Forms_Platform_iOS_Platform_CreateRenderer_Xamarin_Forms_VisualElement + 416
    22  ODISMemberiOS                       0x00ac38f0 Xamarin_Forms_Platform_iOS_VisualElementPackager_OnChildAdded_Xamarin_Forms_VisualElement + 116
    23  ODISMemberiOS                       0x00ac382c Xamarin_Forms_Platform_iOS_VisualElementPackager_OnChildAdded_object_Xamarin_Forms_ElementEventArgs + 292
    24  ODISMemberiOS                       0x004c6dd4 Xamarin_Forms_Element_OnChildAdded_Xamarin_Forms_Element + 572
    25  ODISMemberiOS                       0x004eaa64 Xamarin_Forms_VisualElement_OnChildAdded_Xamarin_Forms_Element + 120
    26  ODISMemberiOS                       0x004d0b58 Xamarin_Forms_Layout_1_T_REF_OnChildAdded_Xamarin_Forms_Element + 120
    27  ODISMemberiOS                       0x004d2e28 Xamarin_Forms_Layout_OnInternalAdded_Xamarin_Forms_View + 132
    28  ODISMemberiOS                       0x004d25f4 Xamarin_Forms_Layout_InternalChildrenOnCollectionChanged_object_System_Collections_Specialized_NotifyCollectionChangedEventArgs + 1888
    29  ODISMemberiOS                       0x008007cc wrapper_delegate_invoke__Module_invoke_void_object_NotifyCollectionChangedEventArgs_object_System_Collections_Specialized_NotifyCollectionChangedEventArgs + 216
    30  ODISMemberiOS                       0x006f7f80 System_Collections_ObjectModel_ObservableCollection_1_T_REF_OnCollectionChanged_System_Collections_Specialized_NotifyCollectionChangedEventArgs + 96
    31  ODISMemberiOS                       0x006f8180 System_Collections_ObjectModel_ObservableCollection_1_T_REF_OnCollectionChanged_System_Collections_Specialized_NotifyCollectionChangedAction_object_int + 104
    32  ODISMemberiOS                       0x006f7bb4 System_Collections_ObjectModel_ObservableCollection_1_T_REF_InsertItem_int_T_REF + 120
    33  ODISMemberiOS                       0x000b1174 System_Collections_ObjectModel_Collection_1_T_REF_Add_T_REF + 180
    34  ODISMemberiOS                       0x004ce378 Xamarin_Forms_ObservableWrapper_2_TKey_REF_TValue_REF_Add_TValue_REF + 600
    35  ODISMemberiOS                       0x00f46eb4 ODISMember_Pages_Index_RefreshWorkspace_int + 2728
    36  ODISMemberiOS                       0x00f48f54 ODISMember_Pages_Index__EventDispatcher_OnRefreshd__3_MoveNext + 4968
    37  ODISMemberiOS                       0x00140480 System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_T_REF_T_REF_ + 252
    38  ODISMemberiOS                       0x0013f560 System_Runtime_CompilerServices_AsyncVoidMethodBuilder_Start_T_REF_T_REF_ + 64
    39  ODISMemberiOS                       0x00f463d8 ODISMember_Pages_Index_EventDispatcher_OnRefresh_object_ODISMember_Helpers_UIHelpers_RefreshEventArgs + 564
    40  ODISMemberiOS                       0x00fb4a14 wrapper_delegate_invoke_System_EventHandler_1_ODISMember_Helpers_UIHelpers_RefreshEventArgs_invoke_void_object_TEventArgs_object_ODISMember_Helpers_UIHelpers_RefreshEventArgs + 712
    41  ODISMemberiOS                       0x00f15014 ODISMember_Helpers_UIHelpers_EventDispatcher_RaiseEvent_object_ODISMember_Helpers_UIHelpers_RefreshEventArgs + 288
    42  ODISMemberiOS                       0x00f49c34 ODISMember_Pages_RootPage_NavigateTo_ODISMember_Model_CustomMenuItem + 2060
    43  ODISMemberiOS                       0x00f49eac ODISMember_Pages_RootPage___ctorb__0_0_object_Xamarin_Forms_SelectedItemChangedEventArgs + 224
    44  ODISMemberiOS                       0x005ac6fc wrapper_delegate_invoke_System_EventHandler_1_Xamarin_Forms_SelectedItemChangedEventArgs_invoke_void_object_TEventArgs_object_Xamarin_Forms_SelectedItemChangedEventArgs + 712
    45  ODISMemberiOS                       0x00422be0 Xamarin_Forms_ListView_OnSelectedItemChanged_Xamarin_Forms_BindableObject_object_object + 340
    46  ODISMemberiOS                       0x0038c9a8 Xamarin_Forms_BindableObject_SetValueActual_Xamarin_Forms_BindableProperty_Xamarin_Forms_BindableObject_BindablePropertyContext_object_bool_Xamarin_Forms_BindableObject_SetValueFlags_bool + 2124
    47  ODISMemberiOS                       0x0038bf3c Xamarin_Forms_BindableObject_SetValueCore_Xamarin_Forms_BindableProperty_object_Xamarin_Forms_BindableObject_SetValueFlags_Xamarin_Forms_BindableObject_SetValuePrivateFlags + 2456
    48  ODISMemberiOS                       0x00388810 Xamarin_Forms_BindableObject_SetValue_Xamarin_Forms_BindableProperty_object_bool_bool + 1108
    49  ODISMemberiOS                       0x00388120 Xamarin_Forms_BindableObject_SetValue_Xamarin_Forms_BindableProperty_object + 148
    50  ODISMemberiOS                       0x0041f60c Xamarin_Forms_ListView_set_SelectedItem_object + 136
    51  ODISMemberiOS                       0x00f4b7f8 ODISMember_Pages_MenuPage_selectMenuItem_int + 1024
    52  ODISMemberiOS                       0x00f4b394 ODISMember_Pages_MenuPage_EventDispatcher_OnRefresh_object_ODISMember_Helpers_UIHelpers_RefreshEventArgs + 364
    53  ODISMemberiOS                       0x00fb4a14 wrapper_delegate_invoke_System_EventHandler_1_ODISMember_Helpers_UIHelpers_RefreshEventArgs_invoke_void_object_TEventArgs_object_ODISMember_Helpers_UIHelpers_RefreshEventArgs + 712
    54  ODISMemberiOS                       0x00f15014 ODISMember_Helpers_UIHelpers_EventDispatcher_RaiseEvent_object_ODISMember_Helpers_UIHelpers_RefreshEventArgs + 288
    55  ODISMemberiOS                       0x00f478dc ODISMember_Pages_Index___ctorb__1_2 + 220
    56  ODISMemberiOS                       0x004479e8 Xamarin_Forms_Command__c__DisplayClass4_0___ctorb__0_object + 128
    57  ODISMemberiOS                       0x00447608 Xamarin_Forms_Command_Execute_object + 132
    58  ODISMemberiOS                       0x003b45dc Xamarin_Forms_TapGestureRecognizer_SendTapped_Xamarin_Forms_View + 432
    59  ODISMemberiOS                       0x00b42004 Xamarin_Forms_Platform_iOS_EventTracker__c__DisplayClass3_0__GetNativeRecognizerb__0_UIKit_UITapGestureRecognizer + 752
    60  ODISMemberiOS                       0x00c23c58 UIKit_UITapGestureRecognizer_Callback_Activated_UIKit_UITapGestureRecognizer + 52
    61  ODISMemberiOS                       0x002f79cc wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 256
    62  ODISMemberiOS                       0x018f7fcf mono_jit_runtime_invoke + 1130
    63  ODISMemberiOS                       0x0193a495 mono_runtime_invoke + 88
    64  ODISMemberiOS                       0x01887859 _ZL30native_to_managed_trampoline_1P11objc_objectP13objc_selectorPP11_MonoMethodS0_PKcS7_S7_ + 268
    65  ODISMemberiOS                       0x01895781 -[**UITapGestureRecognizer target:] + 80
    66  UIKit                               0x2d5cebbf <redacted> + 294
    67  UIKit                               0x2d47dd0d <redacted> + 668
    68  UIKit                               0x2d897991 <redacted> + 48
    69  UIKit                               0x2d446cc5 <redacted> + 216
    70  UIKit                               0x2d444c3f <redacted> + 2950
    71  UIKit                               0x2d47c0dd <redacted> + 784
    72  UIKit                               0x2d47b9cd <redacted> + 520
    73  UIKit                               0x2d451ba5 <redacted> + 196
    74  UIKit                               0x2d6c82bf <redacted> + 14538
    75  UIKit                               0x2d4505a7 <redacted> + 1350
    76  CoreFoundation                      0x29db722f <redacted> + 14
    77  CoreFoundation                      0x29db6643 <redacted> + 222
    78  CoreFoundation                      0x29db4cc1 <redacted> + 768
    79  CoreFoundation                      0x29d009a1 CFRunLoopRunSpecific + 476
    80  CoreFoundation                      0x29d007b3 CFRunLoopRunInMode + 106
    81  GraphicsServices                    0x316c21a9 GSEventRunModal + 136
    82  UIKit                               0x2d4b1635 UIApplicationMain + 1440
    83  ODISMemberiOS                       0x00cc392c wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr + 272
    84  ODISMemberiOS                       0x00c16c50 UIKit_UIApplication_Main_string___intptr_intptr + 52
    85  ODISMemberiOS                       0x00c16c10 UIKit_UIApplication_Main_string___string_string + 204
    86  ODISMemberiOS                       0x0007d4a0 ODISMember_iOS_Application_Main_string** + 192
    87  ODISMemberiOS                       0x002f79cc wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 256
    88  ODISMemberiOS                       0x018f7fcf mono_jit_runtime_invoke + 1130
    89  ODISMemberiOS                       0x0193a495 mono_runtime_invoke + 88
    90  ODISMemberiOS                       0x0193d7c1 mono_runtime_exec_main + 284
    91  ODISMemberiOS                       0x019a9ff0 xamarin_main + 2072
    92  ODISMemberiOS                       0x0189fe51 main + 112
    93  libdyld.dylib                       0x38849aaf <redacted> + 2

please do the need full

**Comment by TorbenK** [comment]
This should be fixed in the next release which I hopefully will release tomorrow.
