### ISSUE TITLE
Callout with hidden "i" button

### ISSUE THREAD

**Issue by TioWidow** [TorbenK/TK.CustomMap#75]
I'm testing the latest version and tried to add a button through the event "MapLongPress" recently available, however on the callout not appear the button with the "i".

```
map.MapLongPress += async (sender, args) =>
            {
                var newPin = args.Value;     
var pin = new TKCustomMapPin
                                {
                                    Position = new Xamarin.Forms.Maps.Position(newPin.Latitude, newPin.Longitude),
                                    DefaultPinColor = Color.Blue,
                                    Title = "(New Point)",
                                    Subtitle = "Test SubTitle",
                                    ShowCallout = true,
                                    IsDraggable = true,

                                };
                                ObservableCollection<TKCustomMapPin> obPin =new ObservableCollection<TKCustomMapPin>();
                                obPin.Add(pin);

                                IEnumerable<TKCustomMapPin>  pinList = map.CustomPins;
                                map.CustomPins= map.CustomPins.Concat(obPin);
}
```

Previously used by a ViewModel for this event following his Sample.

IOS 9.3

**Comment by TorbenK** [comment]
Oh yea well, the callout disclosure button is only added when the `CalloutClickedCommand` is not null, this is something I need to change. Thanks for reporting.

**Comment by JeanCollas** [comment]
I also got this issue. I found that it is actually because some signatures of commands have changed. Use something like that instead of your code:

`public Command<TKCustomMapPin> PinSelectedCommand
        {
            get
            {
                return new Command<TKCustomMapPin>(( TKCustomMapPin mp) =>
                {
`
`public Command<TKCustomMapPin> CalloutClickedCommand
        {
            get
            {
                return new Command<TKCustomMapPin>((TKCustomMapPin mp) =>
               {
`

If you provide a simple 'Command', it is not a good type, so it considers that you haven't provided anything => there is no binded command

**Comment by TorbenK** [comment]
All `Commands<T>`will be changed to `ICommand` in the next release, this will make the parameter optional and gives more flexibility. On top of that there will be a new property on the pin which sets whether its callout is clickable or not.

**Comment by willowvil** [comment]
Hi TorbenK,

is there any progress with this?

Thank you!

**Comment by TioWidow** [comment]
Call the event that way it will work:

            map.CalloutClickedCommand = new Command<TKCustomMapPin>(p =>
            {
                // Your Code
            });

**Comment by willowvil** [comment]
Thanks TioWidow, but it seems that the event does not get fired on pin click

```
map.CalloutClickedCommand = new Command<TKCustomMapPin>(p =>
                {
                    DisplayAlert("The PIN", p.Title, "OK");
                });
```

**Comment by TioWidow** [comment]
In my code it has worked this way:

```
    map.MapLongPressCommand = new Command<Xamarin.Forms.Maps.Position>(p =>
    {

            DisplayAlert("New Point", "Action", "Add New", "Cancel")
                .ContinueWith(t =>
                {
                    if (t.Result)
                    {
                            map.MapRegion = new MapSpan(new Xamarin.Forms.Maps.Position(p.Latitude, p.Longitude), 0.001, 0.001);
                            var pin = new TKCustomMapPin
                            {
                                Position = p,
                                DefaultPinColor = Color.Green,
                                Title = "()",
                                Subtitle = "Press i",
                                ShowCallout = true,
                                IsDraggable = true
                            };
                            Device.BeginInvokeOnMainThread(() =>
                            {
                                (map.CustomPins as ICollection<TKCustomMapPin>)?.Add(pin);
                            });
                    
                    }

                }, TaskScheduler.FromCurrentSynchronizationContext());
    });


        map.CalloutClickedCommand = new Command<TKCustomMapPin>(p =>
        {
            //my Code
        });

```

**Comment by willowvil** [comment]
OK, the calloutclicked works fine! I will use this method until the PinSelectedCommand release.

Do you know how to assign an ID to each pin to identify them on the CalloutClickedCommand?

Thank you!
