### ISSUE TITLE
Error after updatingTKCustomMap

### ISSUE THREAD

**Issue by tecodutra** [TorbenK/TK.CustomMap#76]
After updated the TKCustomMap, I needed to update other components of my project, including Xamarin.Forms. Thus, the compilation started giving the following errors:

> Error CS0117  'Resource.Styleable' does not contain a definition for 'Theme_windowNoTitle'    ProjectName.Droid   C:....\Droid\Resources\Resource.designer.cs    1574
> Error CS0117    'Resource.Styleable' does not contain a definition for 'Theme_windowMinWidthMinor'  ProjectName.Droid   C:....\Droid\Resources\Resource.designer.cs 1573
> Error CS0117    'Resource.Styleable' does not contain a definition for 'Theme_windowMinWidthMajor'  ProjectName.Droid   C:....\Droid\Resources\Resource.designer.cs    1572
> Error CS0117    'Resource.Styleable' does not contain a definition for 'Theme_windowFixedWidthMinor'    ProjectName.Droid   C:....\Droid\Resources\Resource

It has over 148 resource errors.

**Comment by TorbenK** [comment]
This is not related to the control. Try to clean and rebuild your Android project, that helps most of the time.
