### ISSUE TITLE
Is it possible to animate a pin?

### ISSUE THREAD

**Issue by hopewise** [TorbenK/TK.CustomMap#78]
Dragging a pin via user is very useful, but what if I want to animate the pin via code? 
For example, live tracking a car, the car presenting the pin would be moving by updating its location, is this possible?

**Comment by TorbenK** [comment]
If you change the `Position` of a pin, it will also change on the map. This is not really an animation but should be something to start with. I will add the idea of animating pins to the enhancement list.

**Comment by hopewise** [comment]
That's very good, I can handle the animation by keep changing the pin location, it should be easy to do.

But, do I have to refresh the map after changing the pin location?

**Comment by TorbenK** [comment]
No. As soon as you change the `Position` if will change on the map.

**Comment by MumenAlsharif** [comment]
I have tried to change position its changed on the map for android but when I try on iOS its not working, is there any way to refresh the map to see the pin position changing in iOS?

**Comment by TorbenK** [comment]
This will be fixed in the next release.

**Comment by TorbenK** [comment]
1.5.1.
