### ISSUE TITLE
Feature Request - Drawing capabilities with finger

### ISSUE THREAD

**Issue by gotnull** [TorbenK/TK.CustomMap#89]
Is it possible to draw on the map with your finger in order to create a Polyline or Polygon?

**Comment by TorbenK** [comment]
I don't think this is something which should happen directly on the map control. 

Consider something like this:

Add a transparent overlay which consumes the gesture and draw a line on the map. If the user is done, convert the pixel coordinates to geo coordinates and add a polyline/polygon. I will think about adding a function to handle the conversion.

**Comment by TorbenK** [comment]
1.5.1.
