### ISSUE TITLE
Map Pin not showing on Long Press in iOS : Second Map on different page  

### ISSUE THREAD

**Issue by pottabathini** [TorbenK/TK.CustomMap#90]
We are facing issue related to adding pin when we have multiple maps in multiple screens in the same navigation stack.

**Issue:**
1. Map pin not showing on log press on the second map. We have 2 map components in 2 different pages on same navigation stack
2. Only pin not showing but map returning lat and lng successfully
3. When we zoom in on the map again pin showing succssfully
4. We are facing this issue with the second map on second page. We are facing this issue with iOS in all versions.

**Repo Application**
Fully working reproducible demo has been attached in below link
https://drive.google.com/file/d/0B_2BQvCl6AQASjFrTjYyUWlMU1E/view?usp=sharing

**Repo Steps**
1. Download Application form link
2. Build and Run on iOS physical device or iOS simulator any version (We run above  iOS 9)
3. Application Opens with Screen 1 page long press on map it will put pin
4. Click on Send button on top of search box it will take you to screen 2
5. Try to long press on map in screen 2 it won't show pin (issue)

We tried another scenario by disabling map on first page and second page have map this scenario working fine and able to pin on map

**Repo Steps**
1. Remove map on Screen 1
2. Run the application
3. It will open empty page with send button click on send button
4. It will open second map long press on map it will put pin successfully.

Screenshots: 
Repo 1 Step 1:
https://drive.google.com/file/d/0B3NSyNxpw3ZASGhFd05ia20zZDg/view?usp=sharing

Repo 1 Step 2:
https://drive.google.com/file/d/0B3NSyNxpw3ZAX0NtdTA2ei1WMGs/view?usp=sharing

Repo 2 Step 1:
https://drive.google.com/file/d/0B3NSyNxpw3ZAZ01BWHE3VHRTY2s/view?usp=sharing

Repo 2 Step 2:
https://drive.google.com/file/d/0B3NSyNxpw3ZAbzBqU2xSNDJsQXc/view?usp=sharing

Waiting to hear from you back :-)

**Comment by TorbenK** [comment]
Thanks for the detailed information. I will look at it, I just don't know when this will be.

**Comment by afrokick** [comment]
@TorbenK in 1.5.1-pre1 it works well! Thanks!

**Comment by TorbenK** [comment]
1.5.1.
