### ISSUE TITLE
Route not showing in Xamarin Forms XAML

### ISSUE THREAD

**Issue by dimeom** [TorbenK/TK.CustomMap#91]
HI there,

I have this code: But the route is not showing.
Am I missing something?

```
            List<TKRoute> routes = new List<TKRoute>();

            var route = new TKRoute();
            route.TravelMode = TKRouteTravelMode.Driving;
            var myposition = new Position(double.Parse(Globals.myPos.Latitude.ToString()), double.Parse(Globals.myPos.Longitude.ToString()));
            var toposition = new Position(double.Parse(Globals.Distances[0].Location.Latitude.ToString()), double.Parse(Globals.Distances[0].Location.Longitude.ToString()));

            route.Source = myposition;
            route.Destination = toposition;
            route.Color = Color.Blue;
            route.TravelMode = TKRouteTravelMode.Any;
            route.LineWidth = 2;

            routes.Add(route);
            MyMap.Routes = routes;
            List<MapSpan> ms = new List<MapSpan>();
            MapSpan m = new MapSpan(new Position(Globals.myPos.Latitude, Globals.myPos.Longitude), Globals.myPos.Latitude, Globals.myPos.Longitude);
            ms.Add(m);
            MyMap.FitToMapRegions(ms, true);
```

**Comment by TorbenK** [comment]
Which platform? Make sure you have a valid api key for route calculations on Android(see readme).

Check for `RouteCaluclationFinished` or `RouteCalculationFailed`.

**Comment by dimeom** [comment]
Hi, 
Thanks for your answer!!

I have checked, and it seems that the route has been calculated, but it is not being displayed in the map.

I moved this:

List<MapSpan> ms = new List<MapSpan>();
            MapSpan m = new MapSpan(new Position(Globals.myPos.Latitude, Globals.myPos.Longitude), Globals.myPos.Latitude, Globals.myPos.Longitude);
            ms.Add(m);
            MyMap.FitToMapRegions(ms, true);

to the RouteCaluclationFinished event to see if anything happens there. Everything seems alright, but the route is not being displayed. :(

The RouteCalculationFailed event is not trigger.

**Comment by TorbenK** [comment]
can you try this in `RouteCalculationFinished`:

`MyMap.MapRegion = yourCalculatedRoute.Bounds;`

**Comment by TorbenK** [comment]
Closed due to inactivity.

**Comment by brian593** [comment]
I have the same problem I do not see the routes but in the event in RouteCalculationFailed return "ZeroResults"
