### ISSUE TITLE
iOS: GetSnapshot is async but UIKit needs access to UI Thread

### ISSUE THREAD

**Issue by CliffCawley** [TorbenK/TK.CustomMap#92]
I was trying to use GetSnapshot on iOS. Android works fine.

GetSnapshot is async so my calling function needs to be async so I can await on it.

```
                var snapshot = await MapView.GetSnapshot();
```

However when I call this I get 'UIKit Consistency error: you are calling a UIKit method that can only be invoked from the UI thread."

This works fine on Android, what should I be doing differently for iOS?

**Comment by TorbenK** [comment]
I will take a look.

**Comment by TorbenK** [comment]
1.5.1.
