### ISSUE TITLE
The searchBar in my project does not display similar the one in sample project

### ISSUE THREAD

**Issue by RimVo** [TorbenK/TK.CustomMap#94]
![image](https://cloud.githubusercontent.com/assets/19484386/15817595/00c1392a-2c03-11e6-87e4-6d93b9360107.png)
Hi friend,

Please take a look the difference between 2 searchbars, the first one is from in Tk.CustomMap sample project and the second is from my project. Could you please tell me what causes the differences?
I just want to change searchbar background color and make it without border

**Comment by TorbenK** [comment]
You need to change up your xaml and probably use AppCompat. This is not related to the control at all. Closed.
