### ISSUE TITLE
CalloutClicked and CalloutClickedCommand on info button click only

### ISSUE THREAD

**Issue by ghost** [TorbenK/TK.CustomMap#95]
CalloutClicked or CalloutClickedCommand only get called when clicking the info button. Although the callout reacts to a click by turning gray for a moment it does not fire the event. Is that by design or did I do something wrong?

```
_map.CalloutClickedCommand = new Command<TKCustomMapPin>(pin =>
            {
               ...
            });
```

**Comment by TorbenK** [comment]
That is intended.
