### ISSUE TITLE
Have to tap pin twice in order to open pin information.

### ISSUE THREAD

**Issue by ghost** [TorbenK/TK.CustomMap#98]
Hi Torben,

I am experiencing a problem with custom pins in your maps, which I really love and appreciate that you have created those!

On iOS for some reason i have to tap the pin twice to open the pin information. Android works as expected just after one tap.

Please find video showing the issue here:
https://www.dropbox.com/s/3okel6d830cfv7j/CustomPinTapIssueTKCustomMaps.mov?dl=0

Any ideas?

Thank you very much for your help in advance!

Kind regards,
Nikolai

**Comment by TorbenK** [comment]
Thank you for the video! I wasn't able to reproduce it though. Are you using the latest NuGet?

**Comment by ghost** [comment]
Hi Torben. Thank you very much for your reply love your maps by the way. Great enhancement to the Xamarin default. 

I have updated to the latest version of all my Xamarin references as well as your package and now the behaviour is correct. 

Wanted to reply to my post today to mention that it was fixed by updating everything. 

You can close the ticket. 

Thanks and all the best,
Nikolai

**Comment by ghost** [comment]
Fixed after updating to latest version.
